/* v1.9 student activity summary + authenticated score/star ledgers. */
(()=>{
  const panel=document.querySelector('#record-panel');if(!panel)return;const REQUEST_TIMEOUT_MS=5000;
  const labels={vocabulary:{icon:'📚',subject:'국어',topic:'어휘',name:'책마루 · 낱말 뜻 맞추기'},riddle:{icon:'❓',subject:'기타',topic:'수수께끼',name:'도전관 · 수수께끼'}};
  const section=document.createElement('section');section.className='activity-summary-box';section.innerHTML='<div class="activity-summary-head"><h3>📚 과목·주제별 점수</h3><span id="activity-summary-count">0개 활동</span></div><p class="activity-summary-guide">과목이나 주제를 눌러 점수 기록을 확인해 보세요.</p><div id="activity-summary-list" class="activity-summary-list"><p class="activity-summary-empty">아직 저장된 활동 기록이 없어요.</p></div>';const reward=panel.querySelector('.reward-box');if(reward)reward.before(section);else panel.appendChild(section);
  const ledger=document.createElement('section');ledger.className='activity-summary-box';ledger.innerHTML='<div class="activity-summary-head"><h3>🧾 내 점수 장부</h3><span id="score-ledger-count">최근 0건</span></div><p class="activity-summary-guide">언제 어떤 활동에서 점수가 늘거나 줄었는지 확인할 수 있어요.</p><div id="score-ledger-list" class="activity-summary-list"><p class="activity-summary-empty">아직 점수 변경 기록이 없어요.</p></div>';section.after(ledger);
  const stars=document.createElement('section');stars.className='activity-summary-box';stars.innerHTML='<div class="activity-summary-head"><h3>⭐ 내 별 장부</h3><span id="star-balance">0별</span></div><p class="activity-summary-guide">별을 언제 얻고 어디에 사용했는지 확인할 수 있어요.</p><div id="star-ledger-list" class="activity-summary-list"><p class="activity-summary-empty">아직 별 기록이 없어요.</p></div>';ledger.after(stars);
  const list=section.querySelector('#activity-summary-list'),count=section.querySelector('#activity-summary-count'),ledgerList=ledger.querySelector('#score-ledger-list'),ledgerCount=ledger.querySelector('#score-ledger-count'),starList=stars.querySelector('#star-ledger-list'),starBalance=stars.querySelector('#star-balance'),headers=()=>window.StudyVillageAuth?.authHeaders?.()||{},labelFor=id=>labels[id]||{icon:'🎯',subject:'기타',topic:id?String(id).replace(/-/g,' '):'전체',name:id?String(id).replace(/-/g,' '):'전체 기록'};
  function rowsFor(player={}){const rows=Array.isArray(player.activities)?[...player.activities]:[];if(!rows.some(a=>a.activityId==='riddle')&&(Number(player.attempts)||0)>0)rows.unshift({activityId:'riddle',attempts:Number(player.attempts)||0,bestScore:Number(player.bestScore)||0,lastScore:Number(player.lastScore)||0,totalScore:Number(player.totalScore)||0,legacy:true});return rows}
  function render(player={}){const rows=rowsFor(player);count.textContent=`${rows.length}개 활동`;list.innerHTML='';if(!rows.length){list.innerHTML='<p class="activity-summary-empty">아직 저장된 활동 기록이 없어요. 첫 활동에 도전해 보세요! 🌱</p>';return}const groups=new Map();for(const row of rows){const meta=labelFor(row.activityId||'activity'),key=meta.subject||'기타';if(!groups.has(key))groups.set(key,[]);groups.get(key).push({row,meta})}for(const[subject,items]of groups){const total=items.reduce((sum,x)=>sum+(Number(x.row.totalScore)||0),0),group=document.createElement('details');group.className='activity-subject-group';group.innerHTML=`<summary><span>📘 ${subject}</span><strong>누적 ${total}점</strong></summary><div class="activity-subject-items"></div>`;const holder=group.querySelector('.activity-subject-items');items.forEach(({row:a,meta})=>{const card=document.createElement('article');card.className='activity-summary-card';card.innerHTML=`<div class="activity-summary-title"><span>${meta.icon}</span><div><strong>${meta.topic}</strong><small>${meta.name}</small></div></div><div class="activity-summary-stats"><span>도전 <b>${Number(a.attempts)||0}회</b></span><span>최고 <b>${Number(a.bestScore)||0}점</b></span><span>최근 <b>${Number(a.lastScore)||0}점</b></span><span>누적 <b>${Number(a.totalScore)||0}점</b></span></div>`;holder.appendChild(card)});list.appendChild(group)}}
  const fmtTime=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?String(v||''):d.toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})};
  function renderLedger(entries=[]){const rows=entries.filter(e=>e.field==='total_score');ledgerCount.textContent=`최근 ${rows.length}건`;ledgerList.innerHTML='';if(!rows.length){ledgerList.innerHTML='<p class="activity-summary-empty">아직 점수 변경 기록이 없어요.</p>';return}rows.forEach(e=>{const meta=labelFor(e.activityId),delta=Number(e.delta)||0,card=document.createElement('article');card.className='activity-summary-card score-ledger-row';card.innerHTML=`<div class="activity-summary-title"><span>${e.activityId?meta.icon:'⭐'}</span><div><strong>${e.activityId?`${meta.subject} · ${meta.topic}`:'전체 점수'}</strong><small>${fmtTime(e.createdAt)}</small></div><b class="score-ledger-delta ${delta<0?'is-minus':'is-plus'}">${delta>0?'+':''}${delta}점</b></div><div class="score-ledger-balance">${Number(e.beforeValue)||0}점 → <strong>${Number(e.afterValue)||0}점</strong></div>`;ledgerList.appendChild(card)})}
  function renderStars(data={}){const balance=Math.max(0,Number(data.balance)||0),rows=Array.isArray(data.entries)?data.entries:[];starBalance.textContent=`${balance}별`;starList.innerHTML='';if(!rows.length){starList.innerHTML='<p class="activity-summary-empty">아직 별 기록이 없어요.</p>';return}rows.forEach(e=>{const delta=Number(e.delta)||0,card=document.createElement('article');card.className='activity-summary-card score-ledger-row';card.innerHTML=`<div class="activity-summary-title"><span>⭐</span><div><strong>${e.detail||e.kind||'별 변경'}</strong><small>${fmtTime(e.createdAt)}</small></div><b class="score-ledger-delta ${delta<0?'is-minus':'is-plus'}">${delta>0?'+':''}${delta}별</b></div><div class="score-ledger-balance">${Number(e.beforeValue)||0}별 → <strong>${Number(e.afterValue)||0}별</strong></div>`;starList.appendChild(card)})}
  async function load(){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const [me,history,starHistory]=await Promise.all([fetch('/api/player/me',{headers:headers(),cache:'no-store',signal:controller.signal}),fetch('/api/player/me/score-ledger?limit=100',{headers:headers(),cache:'no-store',signal:controller.signal}),fetch('/api/player/me/stars?limit=100',{headers:headers(),cache:'no-store',signal:controller.signal})]);if(me.ok){const d=await me.json();render(d.player||{})}if(history.ok){const d=await history.json();renderLedger(d.entries||[])}if(starHistory.ok){const d=await starHistory.json();renderStars(d)}}catch{}finally{clearTimeout(timeout)}}
  document.querySelector('#record-button')?.addEventListener('click',()=>setTimeout(load,0));window.addEventListener('studyvillage:library-complete',()=>setTimeout(load,0));window.addEventListener('studyvillage:activity-record-refresh',load);
})();