/* v1.9 student activity gate.
   Teacher open/close state and configured attempt limits are checked before an activity starts.
   Existing checkpoints are preserved; repeated gate input is suppressed. */
(()=>{
  const activityState=()=>window.StudyVillageActivityState;
  const recordIds={'riddle-demo':'riddle','library-vocabulary':'vocabulary'};
  let bypassRiddle=false,lastNoticeAt=0;const pending=new Set(),NOTICE_COOLDOWN_MS=1800;
  function blockedByPanel(){return[...document.querySelectorAll('#dialogue,#quiz-panel,#record-panel,#customize-panel,#library-game-panel')].some(el=>el&&!el.hidden)}
  function nearQuizHall(){const player=document.querySelector('#player'),hall=document.querySelector('#quiz-hall');if(!player||!hall)return false;const p=player.getBoundingClientRect(),h=hall.getBoundingClientRect();return Math.hypot(p.left+p.width/2-(h.left+h.width/2),p.top+p.height/2-(h.top+h.height/2))<170}
  async function checkAttemptLimit(id,name){try{const headers=window.StudyVillageAuth?.authHeaders?.()||{},[policyRes,meRes]=await Promise.all([fetch(`/api/activity-attempt-policy/${encodeURIComponent(id)}`,{cache:'no-store'}),fetch('/api/player/me',{headers,cache:'no-store'})]);if(!policyRes.ok||!meRes.ok)return{ok:true};const policy=(await policyRes.json()).policy||{mode:'unlimited'},player=(await meRes.json()).player||{},recordId=recordIds[id]||id,record=(player.activities||[]).find(a=>a.activityId===recordId),attempts=Number(record?.attempts)||0;if(policy.mode==='unlimited')return{ok:true};const limit=policy.mode==='once'?1:Math.max(1,Number(policy.limit)||1),remaining=Math.max(0,limit-attempts);if(remaining>0)return{ok:true,remaining};return{ok:false,message:`🔒 ${name}의 도전 횟수를 모두 사용했어요.\n선생님이 추가 도전을 허용하면 다시 참여할 수 있어요.`}}catch{return{ok:true}}}
  async function allow(id,name){if(pending.has(id))return false;pending.add(id);try{const state=activityState();if(state){const open=await state.requireOpen(id,name);if(!open.ok){const now=Date.now();if(now-lastNoticeAt>=NOTICE_COOLDOWN_MS){lastNoticeAt=now;alert(open.message)}return false}}const attempts=await checkAttemptLimit(id,name);if(attempts.ok)return true;const now=Date.now();if(now-lastNoticeAt>=NOTICE_COOLDOWN_MS){lastNoticeAt=now;alert(attempts.message)}return false}finally{pending.delete(id)}}
  window.addEventListener('studyvillage:open-library-game',e=>{if(e.detail?.gateApproved)return;e.stopImmediatePropagation();if(blockedByPanel())return;(async()=>{if(await allow('library-vocabulary','책마루 · 낱말 뜻 맞추기'))window.dispatchEvent(new CustomEvent('studyvillage:open-library-game',{detail:{gateApproved:true}}))})()});
  window.addEventListener('keydown',e=>{if(bypassRiddle){bypassRiddle=false;return}if(e.code!=='Space'||!nearQuizHall()||blockedByPanel())return;e.preventDefault();e.stopImmediatePropagation();(async()=>{if(await allow('riddle-demo','도전관 · 수수께끼')){bypassRiddle=true;window.dispatchEvent(new KeyboardEvent('keydown',{key:' ',code:'Space',bubbles:true,cancelable:true}))}})()},true);
  document.addEventListener('click',e=>{const button=e.target.closest?.('#talk-button');if(!button||!nearQuizHall()||blockedByPanel())return;if(bypassRiddle){bypassRiddle=false;return}e.preventDefault();e.stopImmediatePropagation();(async()=>{if(await allow('riddle-demo','도전관 · 수수께끼')){bypassRiddle=true;button.click()}})()},true);
})();