/* v1.9 student activity record summary + topic score drill-down. Chronological ledger will use an authenticated endpoint later. */
(()=>{
  const panel=document.querySelector('#record-panel');if(!panel)return;const REQUEST_TIMEOUT_MS=5000;
  const labels={vocabulary:{icon:'📚',subject:'국어',topic:'어휘',name:'책마루 · 낱말 뜻 맞추기'},riddle:{icon:'❓',subject:'기타',topic:'수수께끼',name:'도전관 · 수수께끼'}};
  const section=document.createElement('section');section.className='activity-summary-box';section.innerHTML='<div class="activity-summary-head"><h3>📚 과목·주제별 점수</h3><span id="activity-summary-count">0개 활동</span></div><p class="activity-summary-guide">과목이나 주제를 눌러 점수 기록을 확인해 보세요.</p><div id="activity-summary-list" class="activity-summary-list"><p class="activity-summary-empty">아직 저장된 활동 기록이 없어요.</p></div>';const reward=panel.querySelector('.reward-box');if(reward)reward.before(section);else panel.appendChild(section);
  const list=section.querySelector('#activity-summary-list'),count=section.querySelector('#activity-summary-count'),headers=()=>window.StudyVillageAuth?.authHeaders?.()||{},labelFor=id=>labels[id]||{icon:'🎯',subject:'기타',topic:id.replace(/-/g,' '),name:id.replace(/-/g,' ')};
  function rowsFor(player={}){const rows=Array.isArray(player.activities)?[...player.activities]:[];if(!rows.some(a=>a.activityId==='riddle')&&(Number(player.attempts)||0)>0)rows.unshift({activityId:'riddle',attempts:Number(player.attempts)||0,bestScore:Number(player.bestScore)||0,lastScore:Number(player.lastScore)||0,totalScore:Number(player.totalScore)||0,legacy:true});return rows}
  function render(player={}){const rows=rowsFor(player);count.textContent=`${rows.length}개 활동`;list.innerHTML='';if(!rows.length){list.innerHTML='<p class="activity-summary-empty">아직 저장된 활동 기록이 없어요. 첫 활동에 도전해 보세요! 🌱</p>';return}const groups=new Map();for(const row of rows){const meta=labelFor(row.activityId||'activity'),key=meta.subject||'기타';if(!groups.has(key))groups.set(key,[]);groups.get(key).push({row,meta})}for(const[subject,items]of groups){const total=items.reduce((sum,x)=>sum+(Number(x.row.totalScore)||0),0),group=document.createElement('details');group.className='activity-subject-group';group.innerHTML=`<summary><span>📘 ${subject}</span><strong>누적 ${total}점</strong></summary><div class="activity-subject-items"></div>`;const holder=group.querySelector('.activity-subject-items');items.forEach(({row:a,meta})=>{const card=document.createElement('article');card.className='activity-summary-card';card.innerHTML=`<div class="activity-summary-title"><span>${meta.icon}</span><div><strong>${meta.topic}</strong><small>${meta.name}</small></div></div><div class="activity-summary-stats"><span>도전 <b>${Number(a.attempts)||0}회</b></span><span>최고 <b>${Number(a.bestScore)||0}점</b></span><span>최근 <b>${Number(a.lastScore)||0}점</b></span><span>누적 <b>${Number(a.totalScore)||0}점</b></span></div>`;holder.appendChild(card)});list.appendChild(group)}}
  async function load(){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const r=await fetch('/api/player/me',{headers:headers(),cache:'no-store',signal:controller.signal});if(!r.ok)return;const d=await r.json();render(d.player||{})}catch{}finally{clearTimeout(timeout)}}
  document.querySelector('#record-button')?.addEventListener('click',()=>setTimeout(load,0));window.addEventListener('studyvillage:library-complete',()=>setTimeout(load,0));window.addEventListener('studyvillage:activity-record-refresh',load);
})();