/* v1.10 teacher star balance/ledger adjustment panel. No window.prompt: classroom/Electron/Naver-safe in-page controls. */
(()=>{
  const headers=json=>{const token=sessionStorage.getItem('studyvillage-admin-token')||'';return token?{Authorization:`Bearer ${token}`,...(json?{'Content-Type':'application/json'}:{})}:{...(json?{'Content-Type':'application/json'}:{})}};
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const REQUEST_TIMEOUT_MS=5000;
  let panel,select,balance,list,status,amountInput,reasonInput,adjusting=false,studentsLoading=null,selectedLoadSeq=0;
  async function timedFetch(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
  function ensure(){if(panel)return;const app=document.querySelector('#admin-app');if(!app)return;panel=document.createElement('section');panel.id='admin-star-panel';panel.className='panel';panel.innerHTML=`<div class="panel-head"><div><h2>⭐ 별 관리</h2><p>학생별 별을 지급하거나 차감합니다. 모든 변경은 별 장부에 사유와 함께 남습니다.</p></div><span id="admin-star-balance" class="overview-count">0별</span></div><div class="sv-star-controls"><label>학생<select id="admin-star-student"><option value="">학생 선택</option></select></label><label>별 개수<input id="admin-star-amount" type="number" min="1" max="1000000" value="1" inputmode="numeric"></label><label class="sv-star-reason">변경 이유<input id="admin-star-reason" type="text" maxlength="200" value="교사 확인 후 별 조정" placeholder="변경 이유"></label><div class="sv-star-buttons"><button id="admin-star-add">+ 별 지급</button><button id="admin-star-subtract">- 별 차감</button><button id="admin-star-refresh">새로고침</button></div><span id="admin-star-status" class="status">준비됨</span></div><div id="admin-star-list"><p class="empty">학생을 선택하면 별 이력이 표시됩니다.</p></div>`;const anchor=document.querySelector('#student-activity-panel');anchor?.before(panel);if(!anchor)app.appendChild(panel);const style=document.createElement('style');style.textContent='.sv-star-controls{display:grid;grid-template-columns:minmax(150px,1fr) 120px minmax(220px,2fr);gap:10px;align-items:end;margin-bottom:12px}.sv-star-controls label{display:grid;gap:5px;font-weight:900;color:#45604b}.sv-star-controls select,.sv-star-controls input{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #cbdacb;border-radius:10px;background:#fff;font:inherit}.sv-star-buttons{display:flex;gap:7px;flex-wrap:wrap;grid-column:1/-1}.sv-star-buttons button{padding:9px 13px;border:1px solid #c9ddc9;border-radius:10px;background:#fff;color:#31583c;font-weight:900;cursor:pointer}.sv-star-buttons #admin-star-add{background:#eef8e9}.sv-star-buttons #admin-star-subtract{background:#fff2ef}.sv-star-controls .status{grid-column:1/-1}@media(max-width:720px){.sv-star-controls{grid-template-columns:1fr 1fr}.sv-star-reason{grid-column:1/-1}}';document.head.appendChild(style);select=panel.querySelector('#admin-star-student');balance=panel.querySelector('#admin-star-balance');list=panel.querySelector('#admin-star-list');status=panel.querySelector('#admin-star-status');amountInput=panel.querySelector('#admin-star-amount');reasonInput=panel.querySelector('#admin-star-reason');panel.querySelector('#admin-star-refresh').addEventListener('click',loadSelected);panel.querySelector('#admin-star-add').addEventListener('click',()=>adjust(1));panel.querySelector('#admin-star-subtract').addEventListener('click',()=>adjust(-1));select.addEventListener('change',loadSelected)}
  function setAdjusting(value){adjusting=value;for(const id of ['#admin-star-add','#admin-star-subtract']){const b=panel?.querySelector(id);if(b)b.disabled=value}}
  async function loadStudents(){ensure();if(studentsLoading)return studentsLoading;studentsLoading=(async()=>{try{const r=await timedFetch('/api/admin/players',{headers:headers(),cache:'no-store'});if(r.status===401){status.textContent='관리자 로그인이 필요합니다.';return}const d=await r.json();if(!r.ok||!d.ok)return;const current=select.value;select.innerHTML='<option value="">학생 선택</option>'+d.players.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current}catch{}finally{studentsLoading=null}})();return studentsLoading}
  async function loadSelected(){ensure();const name=select.value,seq=++selectedLoadSeq;if(!name){balance.textContent='0별';list.innerHTML='<p class="empty">학생을 선택하면 별 이력이 표시됩니다.</p>';status.textContent='준비됨';return}status.textContent='불러오는 중…';try{const r=await timedFetch(`/api/admin/stars/${encodeURIComponent(name)}?limit=50`,{headers:headers(),cache:'no-store'});if(seq!==selectedLoadSeq||select.value!==name)return;if(r.status===401){status.textContent='관리자 로그인이 필요합니다.';list.innerHTML='<p class="empty">관리자 로그인이 필요합니다.</p>';return}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.code||'불러오기 실패');balance.textContent=`${Number(d.balance)||0}별`;const rows=d.entries||[];list.innerHTML=rows.length?rows.map(e=>`<article class="attention-card"><div class="attention-card-head"><strong>${Number(e.delta)>0?'⭐ 지급':'🛒 사용/차감'} ${Number(e.delta)>0?'+':''}${Number(e.delta)||0}별</strong><span>${esc(new Date(e.createdAt).toLocaleString('ko-KR'))}</span></div><p>${esc(e.detail||e.kind||'별 변경')}</p><small>${Number(e.beforeValue)||0}별 → ${Number(e.afterValue)||0}별</small></article>`).join(''):'<div class="attention-clear">아직 별 변경 이력이 없습니다.</div>';status.textContent='불러옴'}catch(err){if(seq!==selectedLoadSeq||select.value!==name)return;status.textContent=err?.name==='AbortError'?'불러오기 시간 초과':'불러오기 실패';list.innerHTML=`<p class="empty">${esc(err?.name==='AbortError'?'서버 응답 시간이 초과되었습니다.':err.message||err)}</p>`}}
  async function adjust(direction){ensure();if(adjusting)return;const name=select.value;if(!name){status.textContent='학생을 먼저 선택하세요.';select.focus();return}const amount=Number(amountInput.value),reason=reasonInput.value.trim();if(!Number.isInteger(amount)||amount<=0||amount>1000000){status.textContent='별 개수는 1 이상의 정수로 입력하세요.';amountInput.focus();return}if(reason.length<2){status.textContent='변경 이유를 입력하세요.';reasonInput.focus();return}const delta=direction*amount;if(!confirm(`${name} 학생의 별을 ${delta>0?'+':''}${delta}별 변경할까요?\n\n사유: ${reason}`))return;setAdjusting(true);status.textContent='저장 중…';try{const r=await timedFetch(`/api/admin/stars/${encodeURIComponent(name)}/adjust`,{method:'POST',headers:headers(true),body:JSON.stringify({delta,reason})});if(r.status===401){status.textContent='관리자 로그인이 필요합니다.';alert('관리자 로그인이 만료되었습니다. 다시 로그인해 주세요.');return}const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.code==='insufficient-stars'?'보유 별보다 많이 차감할 수 없습니다.':d.code||'저장 실패');status.textContent=`저장 완료 · ${Number(d.afterValue??d.balance)||0}별`;await loadSelected();window.dispatchEvent(new CustomEvent('studyvillage:admin-stars-updated',{detail:{name,delta,balance:Number(d.afterValue??d.balance)||0}}))}catch(err){status.textContent=`저장 실패 · ${err?.name==='AbortError'?'시간 초과':err.message||err}`;alert(`별 변경 실패: ${err?.name==='AbortError'?'서버 응답 시간이 초과되었습니다.':err.message||err}`)}finally{setAdjusting(false)}}
  async function boot(){ensure();await loadStudents();await loadSelected()}
  window.addEventListener('load',()=>setTimeout(boot,600));document.querySelector('#refresh-button')?.addEventListener('click',()=>setTimeout(boot,250));new MutationObserver(()=>{const app=document.querySelector('#admin-app');if(app&&!app.hidden)boot()}).observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['hidden']});
})();
