/* v1.9 teacher shop configuration panel with bounded request waits. */
(()=>{
  const headers=json=>{const token=sessionStorage.getItem('studyvillage-admin-token')||'';return token?{Authorization:`Bearer ${token}`,...(json?{'Content-Type':'application/json'}:{})}:{...(json?{'Content-Type':'application/json'}:{})}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const REQUEST_TIMEOUT_MS=5000;
  let panel,status,toggle,list,saveButton,saving=false,loading=false;
  async function timedFetch(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
  function ensure(){if(panel)return;const app=document.querySelector('#admin-app');if(!app)return;panel=document.createElement('section');panel.id='shop-admin-panel';panel.className='panel';panel.innerHTML=`<div class="panel-head"><div><h2>🛍️ 상점 설정</h2><p>학생 상점의 사용 여부와 아이템 가격을 설정합니다. 변경 내용은 백업 설정에 함께 저장됩니다.</p></div><span id="shop-admin-status" class="status">불러오는 중…</span></div><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:12px"><label style="display:flex;align-items:center;gap:6px;font-weight:900"><input id="shop-admin-enabled" type="checkbox"> 학생 상점 사용</label><button id="shop-admin-save">설정 저장</button></div><div id="shop-admin-list" class="teacher-activity-grid"></div>`;const anchor=document.querySelector('#star-admin-panel');anchor?.after(panel);if(!anchor)app.prepend(panel);status=panel.querySelector('#shop-admin-status');toggle=panel.querySelector('#shop-admin-enabled');list=panel.querySelector('#shop-admin-list');saveButton=panel.querySelector('#shop-admin-save');saveButton.addEventListener('click',save)}
  function setSaving(value){saving=value;if(saveButton){saveButton.disabled=value;saveButton.textContent=value?'저장 중…':'설정 저장'}}
  function render(data){ensure();toggle.checked=!!data.enabled;list.innerHTML='';for(const item of data.items||[]){const id=String(item.id??''),row=document.createElement('article');row.className='attention-card';row.innerHTML=`<div class="attention-card-head"><strong>${esc(item.name)}</strong><span>${esc(id)}</span></div><label style="display:flex;align-items:center;gap:8px;margin-top:8px"><span style="min-width:54px">가격</span><input data-shop-price="${esc(id)}" type="number" min="0" max="100000" step="1" value="${Number(item.price)||0}" style="max-width:120px"> <b>별</b></label><label style="display:flex;align-items:center;gap:8px;margin-top:10px;font-weight:900"><input data-shop-available="${esc(id)}" type="checkbox" ${item.available===false?'':'checked'}> 판매 중</label>`;list.appendChild(row)}const onSale=(data.items||[]).filter(item=>item.available!==false).length;status.textContent=data.enabled?`상점 ON · ${onSale}개 판매 중`:'상점 OFF'}
  async function load(){ensure();if(loading)return;loading=true;status.textContent='불러오는 중…';try{const r=await timedFetch('/api/admin/shop',{headers:headers(),cache:'no-store'});if(r.status===401){status.textContent='관리자 로그인이 필요합니다.';return}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'불러오기 실패');render(d)}catch(err){status.textContent=err?.name==='AbortError'?'불러오기 시간 초과':'불러오기 실패'}finally{loading=false}}
  async function save(){ensure();if(saving)return;const prices={},availability={};for(const input of list.querySelectorAll('[data-shop-price]')){const value=Number(input.value);if(!Number.isInteger(value)||value<0||value>100000)return alert('가격은 0~100000 사이의 정수로 입력해 주세요.');prices[input.dataset.shopPrice]=value}for(const input of list.querySelectorAll('[data-shop-available]'))availability[input.dataset.shopAvailable]=input.checked;const onSale=Object.values(availability).filter(Boolean).length;if(!confirm(`${toggle.checked?'상점을 켜고':'상점을 끄고'} ${onSale}개 아이템을 판매하도록 저장할까요?\n판매 중지 아이템도 이미 가진 학생은 계속 장착할 수 있습니다.`))return;setSaving(true);status.textContent='저장 중…';try{const r=await timedFetch('/api/admin/shop',{method:'PUT',headers:headers(true),body:JSON.stringify({enabled:toggle.checked,prices,availability})});if(r.status===401){status.textContent='관리자 로그인이 필요합니다.';alert('관리자 로그인 시간이 만료되었습니다. 다시 로그인한 뒤 저장해 주세요.');return}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||d.code||'저장 실패');render(d);alert('상점 설정이 저장되었습니다.')}catch(err){status.textContent='저장 실패';alert(`상점 설정 저장 실패: ${err?.name==='AbortError'?'서버 응답 시간이 초과되었습니다.':err.message||err}`)}finally{setSaving(false)}}
  window.addEventListener('load',()=>{ensure();setTimeout(load,550)});document.querySelector('#refresh-button')?.addEventListener('click',()=>setTimeout(load,350));
})();
