/* v0.9.8 teacher-side grouped error report viewer */
(()=>{
  const app=document.querySelector('#admin-app');
  if(!app)return;
  const token=()=>sessionStorage.getItem('studyvillage-admin-token')||'';
  const headers=()=>token()?{Authorization:`Bearer ${token()}`}:{},esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const section=document.createElement('section');section.className='panel';section.innerHTML=`<div class="panel-head"><div><h2>🛠️ 자동 오류 수집</h2><p>학생 기기 오류를 자동 수집하고, 같은 오류는 묶어서 보여줍니다. 학생은 따로 누를 것이 없습니다.</p></div><div class="actions"><span id="teacher-error-count" class="overview-count">0건</span><button id="teacher-error-refresh">새로고침</button><button id="teacher-error-export">JSON 내보내기</button><button id="teacher-error-clear">기록 비우기</button></div></div><div id="teacher-error-summary" style="padding:0 22px 8px;color:#607266;font-weight:800"></div><div id="teacher-error-list" style="padding:10px 22px 22px"><p class="empty">오류 기록을 불러오는 중입니다.</p></div>`;
  const recent=[...app.querySelectorAll('.panel')].find(p=>p.textContent.includes('최근 활동'));if(recent)recent.before(section);else app.appendChild(section);
  const count=section.querySelector('#teacher-error-count'),summary=section.querySelector('#teacher-error-summary'),list=section.querySelector('#teacher-error-list'),refresh=section.querySelector('#teacher-error-refresh'),exportBtn=section.querySelector('#teacher-error-export'),clearBtn=section.querySelector('#teacher-error-clear');
  function fmt(v){if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?'-':d.toLocaleString('ko-KR')}
  function keyOf(e){return`${e.kind||'error'}\n${e.message||''}\n${e.page||''}\n${e.version||''}`}
  function groupRows(rows){const map=new Map();for(const e of rows){const key=keyOf(e),g=map.get(key)||{kind:e.kind||'error',message:e.message||'오류 메시지 없음',page:e.page||'/',version:e.version||'?',count:0,players:new Set(),latest:e.createdAt,latestId:e.id};g.count++;if(e.playerName)g.players.add(e.playerName);if((e.id||0)>(g.latestId||0)){g.latest=e.createdAt;g.latestId=e.id}map.set(key,g)}return[...map.values()].sort((a,b)=>(b.latestId||0)-(a.latestId||0))}
  async function load(){if(!token())return;try{const r=await fetch('/api/admin/errors',{headers:headers(),cache:'no-store'});if(!r.ok)return;const rows=(await r.json()).errors||[],groups=groupRows(rows);count.textContent=`${rows.length}건`;summary.textContent=rows.length?`같은 오류를 묶어 ${groups.length}종류로 표시 · 영향 학생 ${new Set(rows.map(e=>e.playerName).filter(Boolean)).size}명`:'현재 수집된 오류가 없습니다.';list.innerHTML='';if(!rows.length){list.innerHTML='<p class="empty">수집된 오류가 없습니다. 🌱</p>';return}groups.slice(0,50).forEach(g=>{const names=[...g.players],card=document.createElement('article');card.style.cssText='border:1px solid #eadfd5;border-radius:14px;padding:13px 14px;margin-bottom:10px;background:#fffdf9';card.innerHTML=`<div style="display:flex;gap:8px;justify-content:space-between;flex-wrap:wrap"><strong>${esc(g.kind)} · ${g.count}회</strong><small>최근 ${fmt(g.latest)} · v${esc(g.version)}</small></div><div style="margin-top:7px;font-weight:700">${esc(g.message)}</div><small style="display:block;margin-top:6px;color:#78857c">영향 학생 ${names.length}명${names.length?` · ${esc(names.slice(0,6).join(', '))}${names.length>6?' 외':''}`:''} · ${esc(g.page)}</small>`;list.appendChild(card)})}catch{list.innerHTML='<p class="empty">오류 기록을 불러오지 못했습니다.</p>'}}
  async function exportErrors(){try{const r=await fetch('/api/admin/errors/export',{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error();const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Studyvillage-server-errors-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch{alert('오류 리포트를 내보내지 못했습니다.')}}
  async function clearErrors(){if(!confirm('교사 PC에 모인 오류 기록을 모두 비울까요?'))return;const r=await fetch('/api/admin/errors',{method:'DELETE',headers:headers()});if(r.ok)load()}
  refresh.onclick=load;exportBtn.onclick=exportErrors;clearBtn.onclick=clearErrors;
  const observer=new MutationObserver(()=>{if(!app.hidden&&token())load()});observer.observe(app,{attributes:true,attributeFilter:['hidden']});setTimeout(load,700);
})();