/* v1.9 teacher shop configuration panel. */
(()=>{
  const headers=json=>{const token=sessionStorage.getItem('studyvillage-admin-token')||'';return token?{Authorization:`Bearer ${token}`,...(json?{'Content-Type':'application/json'}:{})}:{...(json?{'Content-Type':'application/json'}:{})}};
  let panel,status,toggle,list;
  function ensure(){if(panel)return;const app=document.querySelector('#admin-app');if(!app)return;panel=document.createElement('section');panel.id='shop-admin-panel';panel.className='panel';panel.innerHTML=`<div class="panel-head"><div><h2>🛍️ 상점 설정</h2><p>학생 상점의 사용 여부와 아이템 가격을 설정합니다. 변경 내용은 백업 설정에 함께 저장됩니다.</p></div><span id="shop-admin-status" class="status">불러오는 중…</span></div><div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:12px"><label style="display:flex;align-items:center;gap:6px;font-weight:900"><input id="shop-admin-enabled" type="checkbox"> 학생 상점 사용</label><button id="shop-admin-save">설정 저장</button></div><div id="shop-admin-list" class="teacher-activity-grid"></div>`;const anchor=document.querySelector('#star-admin-panel');anchor?.after(panel);if(!anchor)app.prepend(panel);status=panel.querySelector('#shop-admin-status');toggle=panel.querySelector('#shop-admin-enabled');list=panel.querySelector('#shop-admin-list');panel.querySelector('#shop-admin-save').addEventListener('click',save)}
  function render(data){ensure();toggle.checked=!!data.enabled;list.innerHTML='';for(const item of data.items||[]){const row=document.createElement('article');row.className='attention-card';row.innerHTML=`<div class="attention-card-head"><strong>${item.name}</strong><span>${item.id}</span></div><label style="display:flex;align-items:center;gap:8px;margin-top:8px"><span style="min-width:54px">가격</span><input data-shop-price="${item.id}" type="number" min="0" max="100000" step="1" value="${Number(item.price)||0}" style="max-width:120px"> <b>별</b></label>`;list.appendChild(row)}status.textContent=data.enabled?'상점 ON':'상점 OFF'}
  async function load(){ensure();try{const r=await fetch('/api/admin/shop',{headers:headers(),cache:'no-store'});if(r.status===401)return;const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'불러오기 실패');render(d)}catch{status.textContent='불러오기 실패'}}
  async function save(){ensure();const prices={};for(const input of list.querySelectorAll('[data-shop-price]')){const value=Number(input.value);if(!Number.isInteger(value)||value<0||value>100000)return alert('가격은 0~100000 사이의 정수로 입력해 주세요.');prices[input.dataset.shopPrice]=value}if(!confirm(`${toggle.checked?'상점을 켜고':'상점을 끄고'} 현재 가격표를 저장할까요?`))return;status.textContent='저장 중…';try{const r=await fetch('/api/admin/shop',{method:'PUT',headers:headers(true),body:JSON.stringify({enabled:toggle.checked,prices})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||d.code||'저장 실패');render(d);alert('상점 설정이 저장되었습니다.')}catch(err){status.textContent='저장 실패';alert(`상점 설정 저장 실패: ${err.message||err}`)}}
  window.addEventListener('load',()=>{ensure();setTimeout(load,550)});document.querySelector('#refresh-button')?.addEventListener('click',()=>setTimeout(load,350));
})();
