/* v0.9.10 teacher-side grouped/prioritized error viewer + ChatGPT-ready diagnostic export */
(()=>{
  const app=document.querySelector('#admin-app');
  if(!app)return;
  const VERSION='0.9.10';
  const token=()=>sessionStorage.getItem('studyvillage-admin-token')||'';
  const headers=()=>token()?{Authorization:`Bearer ${token()}`}:{},esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const section=document.createElement('section');section.className='panel';section.innerHTML=`<div class="panel-head"><div><h2>🛠️ 자동 오류 수집</h2><p>학생 기기 오류를 자동 수집합니다. 문제가 생기면 진단 파일을 내려받아 ChatGPT에 올려주세요.</p></div><div class="actions"><span id="teacher-error-count" class="overview-count">0건</span><button id="teacher-error-refresh">새로고침</button><button id="teacher-error-export">🤖 진단 파일 내보내기</button><button id="teacher-error-clear">기록 비우기</button></div></div><div id="teacher-error-summary" style="padding:0 22px 8px;color:#607266;font-weight:800"></div><div id="teacher-error-list" style="padding:10px 22px 22px"><p class="empty">오류 기록을 불러오는 중입니다.</p></div>`;
  const recent=[...app.querySelectorAll('.panel')].find(p=>p.textContent.includes('최근 활동'));if(recent)recent.before(section);else app.appendChild(section);
  const count=section.querySelector('#teacher-error-count'),summary=section.querySelector('#teacher-error-summary'),list=section.querySelector('#teacher-error-list'),refresh=section.querySelector('#teacher-error-refresh'),exportBtn=section.querySelector('#teacher-error-export'),clearBtn=section.querySelector('#teacher-error-clear');
  function fmt(v){if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?'-':d.toLocaleString('ko-KR')}
  function keyOf(e){return`${e.kind||'error'}\n${e.message||''}\n${e.page||''}\n${e.version||''}`}
  function priorityOf(g){const players=g.players.size,count=g.count,kind=String(g.kind||'');if(kind==='api-error'||count>=5||players>=3)return{rank:3,label:'높음',icon:'🔴',bg:'#fff0f0',fg:'#9a3434'};if(kind==='unhandled-rejection'||kind==='window-error'||count>=2||players>=2)return{rank:2,label:'보통',icon:'🟠',bg:'#fff7e8',fg:'#8a5a12'};return{rank:1,label:'낮음',icon:'🟢',bg:'#eef8ef',fg:'#376044'}}
  function groupRows(rows){const map=new Map();for(const e of rows){const key=keyOf(e),g=map.get(key)||{kind:e.kind||'error',message:e.message||'오류 메시지 없음',page:e.page||'/',version:e.version||'?',count:0,players:new Set(),latest:e.createdAt,latestId:e.id};g.count++;if(e.playerName)g.players.add(e.playerName);if((e.id||0)>(g.latestId||0)){g.latest=e.createdAt;g.latestId=e.id}map.set(key,g)}const groups=[...map.values()];groups.forEach(g=>g.priority=priorityOf(g));return groups.sort((a,b)=>b.priority.rank-a.priority.rank||(b.latestId||0)-(a.latestId||0))}
  async function fetchJson(url){const r=await fetch(url,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.json()}
  async function load(){if(!token())return;try{const d=await fetchJson('/api/admin/errors'),rows=d.errors||[],groups=groupRows(rows),affected=new Set(rows.map(e=>e.playerName).filter(Boolean)).size,high=groups.filter(g=>g.priority.rank===3).length,medium=groups.filter(g=>g.priority.rank===2).length;count.textContent=`${rows.length}건`;summary.textContent=rows.length?`오류 ${groups.length}종류 · 영향 학생 ${affected}명 · 우선 확인 ${high}종류 · 보통 ${medium}종류`:'현재 수집된 오류가 없습니다.';list.innerHTML='';if(!rows.length){list.innerHTML='<p class="empty">수집된 오류가 없습니다. 🌱</p>';return}groups.slice(0,50).forEach(g=>{const names=[...g.players],p=g.priority,card=document.createElement('article');card.style.cssText=`border:1px solid #eadfd5;border-radius:14px;padding:13px 14px;margin-bottom:10px;background:${p.bg}`;card.innerHTML=`<div style="display:flex;gap:8px;justify-content:space-between;flex-wrap:wrap;align-items:center"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span style="padding:4px 8px;border-radius:999px;background:#fff;color:${p.fg};font-size:11px;font-weight:900">${p.icon} ${p.label}</span><strong>${esc(g.kind)} · ${g.count}회</strong></div><small>최근 ${fmt(g.latest)} · v${esc(g.version)}</small></div><div style="margin-top:7px;font-weight:700">${esc(g.message)}</div><small style="display:block;margin-top:6px;color:#78857c">영향 학생 ${names.length}명${names.length?` · ${esc(names.slice(0,6).join(', '))}${names.length>6?' 외':''}`:''} · ${esc(g.page)}</small>`;list.appendChild(card)})}catch{list.innerHTML='<p class="empty">오류 기록을 불러오지 못했습니다.</p>'}}
  async function exportDiagnostics(){exportBtn.disabled=true;exportBtn.textContent='진단 파일 만드는 중…';try{const[errorData,playerData,activityData]=await Promise.all([fetchJson('/api/admin/errors'),fetchJson('/api/admin/players'),fetchJson('/api/admin/activity')]);const errors=errorData.errors||[],players=playerData.players||[],activities=activityData.activities||[],groups=groupRows(errors).map(g=>({priority:g.priority.label,kind:g.kind,message:g.message,page:g.page,version:g.version,count:g.count,affectedPlayers:[...g.players],latest:g.latest}));const safePlayers=players.map(p=>({name:p.name,level:p.level,xp:p.xp,totalScore:p.totalScore,attempts:p.attempts,bestScore:p.bestScore,lastScore:p.lastScore,loginCount:p.loginCount,lastLoginAt:p.lastLoginAt,activities:p.activities}));const bundle={format:'studyvillage-chatgpt-diagnostic',formatVersion:1,appVersion:VERSION,exportedAt:new Date().toISOString(),instructionsForChatGPT:'Analyze the error groups and raw reports, correlate them with recent activity and student state, identify likely root causes, and propose the smallest safe GitHub fix. Preserve existing student data and XP behavior unless directly related to the bug.',privacyNotice:'Passwords, authentication tokens, request bodies, password hashes, salts, and equipment details are excluded from this diagnostic export.',summary:{rawErrorCount:errors.length,errorGroupCount:groups.length,affectedStudentCount:new Set(errors.map(e=>e.playerName).filter(Boolean)).size,registeredStudentCount:safePlayers.length},errorGroups:groups,rawErrors:errors,recentActivity:activities.slice(0,100),studentStateSummary:safePlayers};const blob=new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Studyvillage-ChatGPT-diagnostic-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{alert('진단 파일을 만들지 못했습니다. 서버 상태를 확인한 뒤 다시 시도해 주세요.')}finally{exportBtn.disabled=false;exportBtn.textContent='🤖 진단 파일 내보내기'}}
  async function clearErrors(){if(!confirm('교사 PC에 모인 오류 기록을 모두 비울까요?'))return;const r=await fetch('/api/admin/errors',{method:'DELETE',headers:headers()});if(r.ok)load()}
  refresh.onclick=load;exportBtn.onclick=exportDiagnostics;clearBtn.onclick=clearErrors;
  const observer=new MutationObserver(()=>{if(!app.hidden&&token())load()});observer.observe(app,{attributes:true,attributeFilter:['hidden']});setTimeout(load,700);
})();