(()=>{
  const $=s=>document.querySelector(s),button=$('#customize-button'),panel=$('#customize-panel'),close=$('#customize-close'),save=$('#customize-save'),list=$('#inventory-list'),baseList=$('#base-character-list'),message=$('#customize-message'),game=$('#game-screen');
  if(!button||!panel||!save)return;
  const slots=['hair','outfit','bottom','shoes','bag','hand','pet'],slotNames={hair:'머리카락',outfit:'상의',bottom:'하의',shoes:'신발',bag:'가방',hand:'손 아이템',pet:'친구·이모티콘'},icons={'face-round':'🙂','face-soft':'😊','face-brave':'😌','expression-smile':'😄','expression-calm':'🙂','expression-sparkle':'🤩','cap-blue':'🧢','crown-gold':'👑','glasses-round':'👓','backpack':'🎒','pet-chick':'🐣','pet-cat':'🐱','leaf-cap':'🍃','scholar-cap':'🎓','explorer-goggles':'🥽','star-monocle':'🔭','field-satchel':'🧰','book-pack':'📚','pet-owl':'🦉','pet-fox':'🦊','hair-short':'💇','hair-bob':'👩','hair-ponytail':'👱‍♀️','hair-blue':'🧑‍🎤','hat-wizard':'🧙','hat-pirate':'🏴‍☠️','hat-flower':'🌼','glasses-sun':'🕶️','glasses-heart':'💗','outfit-hoodie':'🧥','outfit-uniform':'👔','outfit-wizard':'🥻','outfit-armor':'🛡️','shoes-sneakers':'👟','shoes-boots':'🥾','shoes-wing':'🪽','bag-art':'🎨','bag-rocket':'🚀','hand-sword':'⚔️','hand-wand':'🪄','hand-book':'📖','hand-magnifier':'🔎','pet-dog':'🐶','pet-rabbit':'🐰','pet-dragon':'🐲','pet-slime':'🟢'},REQUEST_TIMEOUT_MS=6000;
  let playerData=null,shopData={ownedItems:[],equipment:{},items:[]},draft={hair:null,outfit:null,bottom:null,shoes:null,bag:null,hand:null,pet:null},draftBase='student-boy',loadPromise=null;
  const headers=()=>window.StudyVillageAuth?.authHeaders?.()||{};
  function ensureFaceLayers(){for(const [hostSelector,prefix,layerClass] of [['#player','player','avatar-layer'],['.avatar-preview','preview','preview-layer']]){const host=$(hostSelector),base=host?.querySelector(prefix==='player'?'.player-icon':'.preview-base');if(!host||!base)continue;for(const slot of ['face','expression'])if(!host.querySelector(`#${prefix}-${slot}`)){const layer=document.createElement('span');layer.id=`${prefix}-${slot}`;layer.className=`${layerClass} ${prefix}-${slot}`;base.after(layer)}}}
  ensureFaceLayers();
  async function timedFetch(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
  const ownedSet=()=>new Set(Array.isArray(shopData?.ownedItems)?shopData.ownedItems:[]);
  const builtInItem=id=>(playerData?.inventory||[]).find(item=>item.id===id)||null;
  const shopItem=id=>(shopData?.items||[]).find(item=>item.id===id)||null;
  function itemInfo(id){if(!id)return null;const built=builtInItem(id),shop=shopItem(id);return{id,slot:built?.slot||shop?.slot,icon:built?.icon||icons[id]||'🎁',name:built?.name||shop?.name||id,condition:built?.condition||'',builtUnlocked:built?.unlocked===true,owned:ownedSet().has(id)}}
  function usable(id){const item=itemInfo(id);return !!item&&(item.builtUnlocked||item.owned)}
  function normalizeEquipment(raw={}){const out={hair:null,outfit:null,bottom:null,shoes:null,bag:null,hand:null,pet:null};for(const slot of slots){const id=raw?.[slot];if(id&&itemInfo(id)?.slot===slot&&usable(id))out[slot]=id}return out}
  function renderAvatar(){const renderer=window.StudyVillageAvatar;renderer?.paintAvatarBase(document.querySelector('.player-icon'),draftBase);renderer?.paintAvatarBase(document.querySelector('.preview-base'),draftBase);for(const slot of slots){const info=itemInfo(draft[slot]);if(slot==='hair'){renderer?.paintHair(document.querySelector('#player-hair'),info?.id||null,draftBase);renderer?.paintHair(document.querySelector('#preview-hair'),info?.id||null,draftBase);continue}renderer?.paintItem(document.querySelector(`#player-${slot}`),info?.id||null,info?.icon||'');renderer?.paintItem(document.querySelector(`#preview-${slot}`),info?.id||null,info?.icon||'')}}
  function renderBases(){if(!baseList)return;baseList.innerHTML='';for(const c of playerData?.baseCharacters||[]){const b=document.createElement('button');b.type='button';b.className=`inventory-item ${draftBase===c.id?'selected':''}`;b.innerHTML=`<span class="base-choice-preview"></span><strong>${c.name}</strong><small>머리와 얼굴이 포함된 완성형 캐릭터</small>`;window.StudyVillageAvatar?.paintBase(b.querySelector('span'),c.id);b.onclick=()=>{draftBase=c.id;renderBases();renderAvatar()};baseList.appendChild(b)}}
  function allItemsForSlot(slot){const map=new Map();for(const item of playerData?.inventory||[])if(item.slot===slot)map.set(item.id,itemInfo(item.id));for(const item of shopData?.items||[])if(item.slot===slot&&!['physical','effect'].includes(item.slot))map.set(item.id,itemInfo(item.id));return[...map.values()].filter(Boolean)}
  function paintOwnedPreview(button,info,available){if(!available||!window.StudyVillageAvatar?.ASSETS?.[info.id])return;const host=button.querySelector('span');if(!host)return;host.className='item-part-preview';host.replaceChildren();const base=document.createElement('i'),part=document.createElement('i'),renderer=window.StudyVillageAvatar;base.className='shop-preview-base';part.className=`shop-preview-part shop-preview-${info.slot}`;host.append(base);if(info.slot==='hair')renderer.paintAvatarBase(base,draftBase);else renderer.paintBase(base,draftBase);host.append(part);renderer.paintItem(part,info.id)}
  function renderInventory(){if(!list)return;list.innerHTML='';for(const slot of slots){const section=document.createElement('section');section.className='inventory-group';section.innerHTML=`<h3>${slotNames[slot]}</h3>`;const items=document.createElement('div');items.className='inventory-items';const none=document.createElement('button');none.type='button';none.className=`inventory-item ${!draft[slot]?'selected':''}`;none.innerHTML='<span>❌</span><strong>착용 안 함</strong>';none.onclick=()=>{draft[slot]=null;renderInventory();renderAvatar()};items.appendChild(none);for(const info of allItemsForSlot(slot)){const available=info.builtUnlocked||info.owned,b=document.createElement('button');b.type='button';b.disabled=!available;b.className=`inventory-item ${draft[slot]===info.id?'selected':''} ${available?'':'locked'}`;const note=info.owned?'구매 완료 · 사용 가능':info.builtUnlocked?'레벨 보상 · 사용 가능':info.condition||'아직 사용할 수 없어요';b.innerHTML=`<span>${available?info.icon:'🔒'}</span><strong>${info.name}</strong><small>${note}</small>`;if(available)b.onclick=()=>{draft[slot]=info.id;renderInventory();renderAvatar()};paintOwnedPreview(b,info,available);items.appendChild(b)}section.appendChild(items);list.appendChild(section)}}
  async function fetchPlayer(){const r=await timedFetch('/api/player/me',{headers:headers(),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.player)throw new Error('player-load-failed');return d.player}
  async function fetchShop(){const r=await timedFetch('/api/shop',{headers:headers(),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error('shop-load-failed');return d}
  async function load(){if(loadPromise)return loadPromise;loadPromise=(async()=>{try{const next=await fetchPlayer();let shop={ownedItems:[],equipment:{},items:[]};try{shop=await fetchShop()}catch(err){console.warn('[StudyVillage wardrobe shop data]',err)}playerData=next;shopData=shop;draftBase=(next.baseCharacters||[]).some(c=>c.id===next.baseCharacter)?next.baseCharacter:'student-boy';draft=normalizeEquipment({...next.equipment,...shop.equipment});renderBases();renderInventory();renderAvatar();return true}catch{message.textContent='캐릭터 정보를 불러오지 못했어요. 다시 로그인한 뒤 눌러 주세요.';return false}})();try{return await loadPromise}finally{loadPromise=null}}
  async function openPanel(){if(await load()){panel.hidden=false;message.textContent='완성형 캐릭터나 머리·옷·신발·가방·손 아이템·친구를 골라 저장할 수 있어요.'}}
  function closePanel(){if(save.disabled)return;panel.hidden=true}
  async function persistEquipment(legacy,purchased){let lastError=null;for(let attempt=0;attempt<2;attempt++){try{const first=await timedFetch('/api/player/me/equipment',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({baseCharacter:draftBase,equipment:legacy})}),firstData=await first.json().catch(()=>({}));if(!first.ok||!firstData.ok)throw new Error(firstData.code||'legacy-equipment-save-failed');if(Object.keys(purchased).length){const second=await timedFetch('/api/shop/equipment',{method:'PUT',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({equipment:purchased})}),secondData=await second.json().catch(()=>({}));if(!second.ok||!secondData.ok)throw new Error(secondData.code||'shop-equipment-save-failed')}return true}catch(err){lastError=err;if(attempt===1)throw lastError}}throw lastError||new Error('equipment-save-failed')}
  async function saveEquipment({closeAfter=false}={}){if(save.disabled)return false;save.disabled=true;message.textContent='저장 중...';try{const owned=ownedSet(),legacy={hair:null,outfit:null,bottom:null,shoes:null,bag:null,hand:null,pet:null},purchased={};for(const slot of slots){const id=draft[slot],info=itemInfo(id);if(!id)legacy[slot]=null;else if(info?.builtUnlocked)legacy[slot]=id;else legacy[slot]=null;if(id&&owned.has(id)&&!info?.builtUnlocked)purchased[slot]=id}await persistEquipment(legacy,purchased);await load();message.textContent='캐릭터 모습이 저장됐어요! ✨';window.dispatchEvent(new Event('studyvillage:ranking-refresh'));if(closeAfter){panel.hidden=true;button.focus?.()}return true}catch(err){console.warn('[StudyVillage customize save]',err);message.textContent='저장하지 못했어요. 잠시 후 다시 눌러 주세요.';return false}finally{save.disabled=false}}
  async function equipPurchasedNow(itemId,itemName){if(!await load())return;const info=itemInfo(itemId);if(!info||!ownedSet().has(itemId)){message.textContent='구매한 아이템을 찾지 못했어요.';return}if(info.slot==='character'){draftBase=itemId;renderBases()}else if(slots.includes(info.slot)){draft[info.slot]=itemId;renderInventory()}else return;renderAvatar();const ok=await saveEquipment();message.textContent=ok?`✨ ${itemName||info.name}을(를) 바로 장착했어요!`:'구매는 완료됐지만 장착 저장은 다시 시도해 주세요.'}
  button.addEventListener('click',openPanel);close?.addEventListener('click',closePanel);save.addEventListener('click',()=>saveEquipment({closeAfter:true}));window.addEventListener('studyvillage:shop-purchase',()=>setTimeout(()=>load(),0));window.addEventListener('studyvillage:equip-purchased-item',e=>equipPurchasedNow(e.detail?.itemId,e.detail?.itemName));window.addEventListener('keydown',e=>{if(!panel.hidden&&e.key==='Escape'){e.stopImmediatePropagation();closePanel()}},true);if(game)new MutationObserver(()=>{if(game.classList.contains('active')&&panel.hidden)load()}).observe(game,{attributes:true,attributeFilter:['class']});
})();
