(()=>{
  const $=s=>document.querySelector(s),button=$('#customize-button'),panel=$('#customize-panel'),close=$('#customize-close'),save=$('#customize-save'),list=$('#inventory-list'),baseList=$('#base-character-list'),message=$('#customize-message');
  if(!button||!panel)return;
  const slots=['hat','glasses','bag','pet'],slotNames={hat:'모자',glasses:'안경',bag:'가방',pet:'펫'},seenKey='studyvillage-seen-items',REQUEST_TIMEOUT_MS=5000;
  let playerData=null,shopData={ownedItems:[],equipment:{}},draft={hat:null,glasses:null,bag:null,pet:null},draftBase='student-default',lastUnlocked=new Set(),polling=false,loadPromise=null;
  const headers=()=>window.StudyVillageAuth?.authHeaders?.()||{},seenItems=()=>{try{return new Set(JSON.parse(localStorage.getItem(seenKey)||'[]'))}catch{return new Set()}},saveSeen=set=>localStorage.setItem(seenKey,JSON.stringify([...set]));
  async function timedFetch(url,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timeout)}}
  function itemFor(id){return playerData?.inventory?.find(i=>i.id===id)||null}
  function ownedSet(){return new Set(Array.isArray(shopData?.ownedItems)?shopData.ownedItems:[])}
  function usable(item){return !!item&&(!!item.unlocked||ownedSet().has(item.id))}
  function visibleEquipment(raw={}){const known=new Set((playerData?.inventory||[]).map(i=>i.id)),out={hat:null,glasses:null,bag:null,pet:null};for(const slot of slots){const id=raw?.[slot];if(id&&known.has(id))out[slot]=id}return out}
  function renderAvatar(){const renderer=window.StudyVillageAvatar,worldBase=document.querySelector('.player-icon'),previewBase=document.querySelector('.preview-base');if(renderer){renderer.paintBase(worldBase,draftBase);renderer.paintBase(previewBase,draftBase)}for(const slot of slots){const item=itemFor(draft[slot]),id=item?.id||null,fallback=item?.icon||'',world=document.querySelector(`#player-${slot}`),preview=document.querySelector(`#preview-${slot}`);if(renderer){renderer.paintItem(world,id,fallback);renderer.paintItem(preview,id,fallback)}else{if(world)world.textContent=fallback;if(preview)preview.textContent=fallback}}}
  function renderBases(){if(!baseList)return;baseList.innerHTML='';for(const c of playerData?.baseCharacters||[]){const b=document.createElement('button');b.type='button';b.className=`inventory-item ${draftBase===c.id?'selected':''}`;b.innerHTML=`<span>${c.icon}</span><strong>${c.name}</strong><small>기본 캐릭터</small>`;b.onclick=()=>{draftBase=c.id;renderBases();renderAvatar()};baseList.appendChild(b)}}
  function renderInventory(){list.innerHTML='';const groups={},seen=seenItems(),owned=ownedSet();for(const item of playerData?.inventory||[])(groups[item.slot]??=[]).push(item);for(const slot of slots){const section=document.createElement('section');section.className='inventory-group';section.innerHTML=`<h3>${slotNames[slot]}</h3>`;const items=document.createElement('div');items.className='inventory-items';const none=document.createElement('button');none.type='button';none.className=`inventory-item ${!draft[slot]?'selected':''}`;none.innerHTML='<span>❌</span><strong>착용 안 함</strong>';none.onclick=()=>{draft[slot]=null;renderInventory();renderAvatar()};items.appendChild(none);for(const item of groups[slot]||[]){const available=usable(item),isOwned=owned.has(item.id),isNew=available&&!seen.has(item.id),b=document.createElement('button');b.type='button';b.disabled=!available;b.className=`inventory-item ${draft[slot]===item.id?'selected':''} ${available?'':'locked'} ${isNew?'new-item':''}`;const note=isOwned?'구매한 아이템':item.unlocked?'사용 가능':item.condition;b.innerHTML=`<span>${available?item.icon:'🔒'}</span><strong>${item.name}${isNew?' <em>NEW</em>':''}</strong><small>${note}</small>`;if(available)b.onclick=()=>{draft[slot]=item.id;seen.add(item.id);saveSeen(seen);button.classList.toggle('has-new',(playerData.inventory||[]).some(i=>usable(i)&&!seen.has(i.id)));renderInventory();renderAvatar()};items.appendChild(b)}section.appendChild(items);list.appendChild(section)}}
  function detectUnlocks(next){const unlocked=new Set((next.inventory||[]).filter(i=>i.unlocked).map(i=>i.id));if(lastUnlocked.size){const fresh=(next.inventory||[]).filter(i=>i.unlocked&&!lastUnlocked.has(i.id));if(fresh.length){button.classList.add('has-new');window.dispatchEvent(new CustomEvent('studyvillage:items-unlocked',{detail:{items:fresh}}));message.textContent=`🎁 새 아이템 해금! ${fresh.map(i=>`${i.icon} ${i.name}`).join(', ')}`}}lastUnlocked=unlocked}
  async function fetchPlayer(){const r=await timedFetch('/api/player/me',{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error();return(await r.json()).player}
  async function fetchShop(){try{const r=await timedFetch('/api/shop',{headers:headers(),cache:'no-store'}),d=await r.json();return r.ok&&d.ok?d:{ownedItems:[],equipment:{}}}catch{return{ownedItems:[],equipment:{}}}}
  async function load(){if(loadPromise)return loadPromise;loadPromise=(async()=>{try{const[next,shop]=await Promise.all([fetchPlayer(),fetchShop()]);detectUnlocks(next);playerData=next;shopData=shop;draftBase=(playerData.baseCharacters||[]).some(c=>c.id===playerData.baseCharacter)?playerData.baseCharacter:'student-default';draft=visibleEquipment({...playerData.equipment,...shopData.equipment});renderBases();renderInventory();renderAvatar();const unseen=(playerData.inventory||[]).some(i=>usable(i)&&!seenItems().has(i.id));button.classList.toggle('has-new',unseen);return true}catch{message.textContent='꾸미기 정보를 불러오지 못했어요.';return false}})();try{return await loadPromise}finally{loadPromise=null}}
  async function openPanel(){if(await load()){panel.hidden=false;const unseen=(playerData.inventory||[]).filter(i=>usable(i)&&!seenItems().has(i.id));message.textContent=unseen.length?`새로 사용할 수 있는 아이템이 ${unseen.length}개 있어요! ✨`:'기본 캐릭터와 아이템을 골라 나만의 모습을 만들어 보세요.'}}
  function closePanel(){panel.hidden=true;load()}
  async function savePurchasedEquipment(){const owned=ownedSet(),equipment={};for(const slot of slots){const id=draft[slot];if(id&&owned.has(id))equipment[slot]=id;else if(shopData?.equipment?.[slot])equipment[slot]=null}if(!Object.keys(equipment).length)return true;const r=await timedFetch('/api/shop/equipment',{method:'PUT',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({equipment})});if(!r.ok)throw new Error('shop-equipment-save-failed');shopData.equipment=(await r.json()).equipment||shopData.equipment;return true}
  async function saveEquipment(){if(save.disabled)return false;save.disabled=true;message.textContent='저장 중...';try{const owned=ownedSet(),legacy={...draft};for(const slot of slots)if(legacy[slot]&&owned.has(legacy[slot]))legacy[slot]=null;const r=await timedFetch('/api/player/me/equipment',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({baseCharacter:draftBase,equipment:legacy})});if(!r.ok)throw new Error();playerData=(await r.json()).player;await savePurchasedEquipment();await load();message.textContent='캐릭터 모습이 저장됐어요! ✨';return true}catch(err){message.textContent=err?.name==='AbortError'?'저장 시간이 너무 오래 걸렸어요. 연결을 확인한 뒤 다시 저장해 주세요.':'저장하지 못했어요. 서버 연결을 확인해 주세요.';return false}finally{save.disabled=false}}
  async function equipPurchasedNow(itemId,itemName){if(!await load())return;const item=itemFor(itemId);if(!item||!ownedSet().has(itemId)){message.textContent='구매한 아이템을 찾지 못했어요.';return}draft[item.slot]=itemId;renderInventory();renderAvatar();const saved=await saveEquipment();if(saved)message.textContent=`✨ ${itemName||item.name}을(를) 바로 장착했어요!`;else message.textContent='아이템은 구매됐지만 바로 장착하지 못했어요. 꾸미기에서 다시 선택해 주세요.'}
  async function pollUnlocks(){if(polling||document.hidden||!navigator.onLine||!document.querySelector('#game-screen')?.classList.contains('active'))return;polling=true;try{const[next,shop]=await Promise.all([fetchPlayer(),fetchShop()]);detectUnlocks(next);playerData=next;shopData=shop;if(panel.hidden){draftBase=(next.baseCharacters||[]).some(c=>c.id===next.baseCharacter)?next.baseCharacter:'student-default';draft=visibleEquipment({...next.equipment,...shop.equipment})}renderAvatar();const unseen=(next.inventory||[]).some(i=>usable(i)&&!seenItems().has(i.id));button.classList.toggle('has-new',unseen);if(!panel.hidden){renderBases();renderInventory()}}catch{}finally{polling=false}}
  button.addEventListener('click',openPanel);close.addEventListener('click',closePanel);save.addEventListener('click',saveEquipment);window.addEventListener('studyvillage:shop-purchase',()=>setTimeout(load,0));window.addEventListener('studyvillage:equip-purchased-item',e=>equipPurchasedNow(e.detail?.itemId,e.detail?.itemName));window.addEventListener('keydown',e=>{if(!panel.hidden&&e.key==='Escape'){e.stopImmediatePropagation();closePanel()}},true);window.addEventListener('studyvillage:items-unlocked',e=>{const items=e.detail?.items||[];if(items.length){button.classList.add('has-new');button.animate([{transform:'scale(1)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:650,easing:'ease-out'})}});const observer=new MutationObserver(()=>{if(document.querySelector('#game-screen')?.classList.contains('active'))load()});observer.observe(document.querySelector('#game-screen'),{attributes:true,attributeFilter:['class']});setInterval(pollUnlocks,3500)
})();