/* v0.9.54 data service. Classroom server is source of truth; local fallback records are sanitized before use. */
window.StudyVillageData=(()=>{
  const prefix='studyvillage-player:',key=n=>`${prefix}${n}`,REQUEST_TIMEOUT_MS=5000,empty=()=>({totalScore:0,attempts:0,bestScore:0,lastScore:0,xp:0,level:1,xpIntoLevel:0,xpToNext:200,updatedAt:null});
  const num=(v,min=0,max=1e9)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):0};
  function clean(d={}){const xp=num(d.xp,0,1e9);return{totalScore:num(d.totalScore),attempts:num(d.attempts,0,1e6),bestScore:num(d.bestScore),lastScore:num(d.lastScore),xp,level:num(d.level,1,1e6)||Math.floor(xp/200)+1,xpIntoLevel:num(d.xpIntoLevel,0,1e9),xpToNext:num(d.xpToNext,1,1e9)||200,updatedAt:typeof d.updatedAt==='string'?d.updatedAt:null,title:typeof d.title==='string'?d.title:undefined,badges:Array.isArray(d.badges)?d.badges:undefined}}
  async function ready(){return window.StudyVillageAuth?.checkServer?window.StudyVillageAuth.checkServer():false}async function timedFetch(url,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timeout)}}
  async function loadPlayer(name){if(await ready())try{const r=await timedFetch('/api/player/me',{cache:'no-store',headers:window.StudyVillageAuth.authHeaders()});if(r.ok)return{...empty(),...clean((await r.json()).player||{})}}catch{}try{const raw=localStorage.getItem(key(name));return raw?{...empty(),...clean(JSON.parse(raw))}:empty()}catch{try{localStorage.removeItem(key(name))}catch{}return empty()}}
  async function savePlayerConfirmed(record){if(!(await ready()))return null;const payload={totalScore:num(record.totalScore),attempts:num(record.attempts,0,1e6),bestScore:num(record.bestScore),lastScore:num(record.lastScore)};try{const r=await timedFetch('/api/player/me/record',{method:'POST',headers:{'Content-Type':'application/json',...window.StudyVillageAuth.authHeaders()},body:JSON.stringify(payload)});if(!r.ok)return null;return{...empty(),...clean((await r.json()).player||{})}}catch{return null}}
  async function savePlayer(name,record){const confirmed=await savePlayerConfirmed(record);if(confirmed)return confirmed;const xp=num(record.xp),local={totalScore:num(record.totalScore),attempts:num(record.attempts,0,1e6),bestScore:num(record.bestScore),lastScore:num(record.lastScore),xp,level:Math.floor(xp/200)+1,xpIntoLevel:xp%200,xpToNext:200,updatedAt:new Date().toISOString()};try{localStorage.setItem(key(name),JSON.stringify(local))}catch{}return local}
  async function listPlayers(){if(await ready())try{const r=await timedFetch('/api/ranking',{cache:'no-store'});if(r.ok)return((await r.json()).players||[]).map(p=>({...p,...clean(p)}))}catch{}const players=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith(prefix))continue;try{players.push({name:k.slice(prefix.length),...clean(JSON.parse(localStorage.getItem(k)))})}catch{}}return players}
  return{loadPlayer,savePlayer,savePlayerConfirmed,listPlayers,mode:async()=>await ready()?'classroom-server':'local'};
})();