/* v1.3 data service.
   Classroom server is source of truth. Failed writes are kept as a bounded ordered snapshot queue so reconnect can replay each attempt once; retrying an already-applied snapshot does not duplicate XP because server attempts are monotonic. Legacy v1 pending aggregates remain readable and are conservatively merged. */
window.StudyVillageData=(()=>{
  const prefix='studyvillage-player:',pendingPrefix='studyvillage-player-pending:v2:',legacyPendingPrefix='studyvillage-player-pending:v1:',key=n=>`${prefix}${n}`,pendingKey=n=>`${pendingPrefix}${String(n||'').trim().toLowerCase()}`,legacyPendingKey=n=>`${legacyPendingPrefix}${String(n||'').trim().toLowerCase()}`,REQUEST_TIMEOUT_MS=5000,MAX_PENDING_SNAPSHOTS=50,empty=()=>({totalScore:0,attempts:0,bestScore:0,lastScore:0,xp:0,level:1,xpIntoLevel:0,xpToNext:200,updatedAt:null});
  const xpForLevel=level=>{const n=Math.max(0,(Number(level)||1)-1);return 200*n+25*n*(n-1)},progressFromXp=xp=>{const value=Math.max(0,Number(xp)||0);let level=1;while(value>=xpForLevel(level+1))level++;const start=xpForLevel(level),next=xpForLevel(level+1);return{level,xpIntoLevel:value-start,xpToNext:next-start}};
  const num=(v,min=0,max=1e9)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):0};
  function clean(d={}){const xp=num(d.xp,0,1e9),progress=progressFromXp(xp),reward=d.nextGrowthReward;return{totalScore:num(d.totalScore),attempts:num(d.attempts,0,1e6),bestScore:num(d.bestScore),lastScore:num(d.lastScore),xp,level:num(d.level,1,1e6)||progress.level,xpIntoLevel:Number.isFinite(Number(d.xpIntoLevel))?num(d.xpIntoLevel,0,1e9):progress.xpIntoLevel,xpToNext:num(d.xpToNext,1,1e9)||progress.xpToNext,updatedAt:typeof d.updatedAt==='string'?d.updatedAt:null,title:typeof d.title==='string'?d.title:undefined,badges:Array.isArray(d.badges)?d.badges:undefined,nextGrowthReward:reward&&typeof reward==='object'?reward:null,customTitle:typeof d.customTitle==='string'?d.customTitle:null,customTitleAvailable:d.customTitleAvailable===true,customTitleThreshold:num(d.customTitleThreshold,0,1e6),nextCustomTitleLevel:num(d.nextCustomTitleLevel,60,1e6)||60}}
  async function ready(){if(!window.StudyVillageAuth?.checkServer)return false;if(!(await window.StudyVillageAuth.checkServer()))return false;return !!window.StudyVillageAuth?.authHeaders?.().Authorization}
  async function timedFetch(url,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timeout)}}
  function handleAuthExpiry(response){if(response?.status!==401)return false;window.StudyVillageAuth?.clearSession?.();return true}
  function readLocal(name){try{const raw=localStorage.getItem(key(name));return raw?{...empty(),...clean(JSON.parse(raw))}:empty()}catch{try{localStorage.removeItem(key(name))}catch{}return empty()}}
  function readPending(name){
    try{
      const raw=localStorage.getItem(pendingKey(name));
      if(raw){const parsed=JSON.parse(raw),snapshots=Array.isArray(parsed?.snapshots)?parsed.snapshots.map(clean).filter(Boolean).slice(-MAX_PENDING_SNAPSHOTS):[];return{version:2,snapshots}}
      const legacy=localStorage.getItem(legacyPendingKey(name));
      if(legacy){const snapshot=clean(JSON.parse(legacy));return{version:1,snapshots:[snapshot]}}
    }catch{try{localStorage.removeItem(pendingKey(name));localStorage.removeItem(legacyPendingKey(name))}catch{}}
    return{version:2,snapshots:[]};
  }
  function writePending(name,snapshots){const cleanSnapshots=(Array.isArray(snapshots)?snapshots:[]).map(clean).slice(-MAX_PENDING_SNAPSHOTS);try{if(cleanSnapshots.length)localStorage.setItem(pendingKey(name),JSON.stringify({version:2,snapshots:cleanSnapshots,updatedAt:new Date().toISOString()}));else localStorage.removeItem(pendingKey(name));localStorage.removeItem(legacyPendingKey(name))}catch{}return cleanSnapshots}
  function appendPending(name,record){const pending=readPending(name).snapshots,latest=clean(record),last=pending[pending.length-1];if(last&&last.totalScore===latest.totalScore&&last.attempts===latest.attempts&&last.bestScore===latest.bestScore&&last.lastScore===latest.lastScore)return pending;pending.push(latest);return writePending(name,pending)}
  function writeLocal(name,record,{pending=false}={}){const value={...clean(record),updatedAt:new Date().toISOString()};try{localStorage.setItem(key(name),JSON.stringify(value));if(pending)appendPending(name,value)}catch{}return value}
  function clearPending(name){try{localStorage.removeItem(pendingKey(name));localStorage.removeItem(legacyPendingKey(name))}catch{}}
  async function fetchServerPlayer(){const r=await timedFetch('/api/player/me',{cache:'no-store',headers:window.StudyVillageAuth.authHeaders()});if(handleAuthExpiry(r)||!r.ok)return null;const body=await r.json().catch(()=>null);return body?.player?{...empty(),...clean(body.player)}:null}
  async function postRecord(record){const payload={totalScore:num(record.totalScore),attempts:num(record.attempts,0,1e6),bestScore:num(record.bestScore),lastScore:num(record.lastScore)};const r=await timedFetch('/api/player/me/record',{method:'POST',headers:{'Content-Type':'application/json',...window.StudyVillageAuth.authHeaders()},body:JSON.stringify(payload)});if(handleAuthExpiry(r)||!r.ok)return null;const body=await r.json().catch(()=>null);return body?.player?{...empty(),...clean(body.player)}:null}
  function mergeSnapshot(server,snapshot){const pendingIsNewer=!server.updatedAt||!snapshot.updatedAt||String(snapshot.updatedAt)>=String(server.updatedAt);return{totalScore:Math.max(server.totalScore,snapshot.totalScore),attempts:Math.max(server.attempts,snapshot.attempts),bestScore:Math.max(server.bestScore,snapshot.bestScore),lastScore:pendingIsNewer?snapshot.lastScore:server.lastScore}}
  async function flushPending(name){const pending=readPending(name);if(!pending.snapshots.length||!(await ready()))return null;try{let server=await fetchServerPlayer();if(!server)return null;const remaining=[];for(let i=0;i<pending.snapshots.length;i++){
        const snapshot=pending.snapshots[i],merged=mergeSnapshot(server,snapshot),needsWrite=merged.totalScore!==server.totalScore||merged.attempts!==server.attempts||merged.bestScore!==server.bestScore||merged.lastScore!==server.lastScore;
        if(needsWrite){const confirmed=await postRecord(merged);if(!confirmed){remaining.push(...pending.snapshots.slice(i));break}server=confirmed}
      }
      if(remaining.length)writePending(name,remaining);else clearPending(name);writeLocal(name,server);return remaining.length?null:server}catch{return null}}
  async function loadPlayer(name){if(await ready())try{const flushed=await flushPending(name);if(flushed)return flushed;const server=await fetchServerPlayer();if(server){writeLocal(name,server);return server}}catch{}return readLocal(name)}
  async function savePlayerConfirmed(record){if(!(await ready()))return null;try{return await postRecord(record)}catch{return null}}
  async function savePlayer(name,record){const confirmed=await savePlayerConfirmed(record);if(confirmed){clearPending(name);writeLocal(name,confirmed);return confirmed}const xp=num(record.xp),local={totalScore:num(record.totalScore),attempts:num(record.attempts,0,1e6),bestScore:num(record.bestScore),lastScore:num(record.lastScore),xp,...progressFromXp(xp),updatedAt:new Date().toISOString()};return writeLocal(name,local,{pending:true})}
  async function listPlayers(){if(await ready())try{const r=await timedFetch('/api/ranking',{cache:'no-store',headers:window.StudyVillageAuth?.authHeaders?.()||{}});if(handleAuthExpiry(r))return[];if(r.ok)return((await r.json()).players||[]).map(p=>({...p,...clean(p)}))}catch{}const players=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith(prefix)||k.startsWith(pendingPrefix)||k.startsWith(legacyPendingPrefix))continue;try{players.push({name:k.slice(prefix.length),...clean(JSON.parse(localStorage.getItem(k)))})}catch{}}return players}
  return{loadPlayer,savePlayer,savePlayerConfirmed,listPlayers,flushPending,mode:async()=>await ready()?'classroom-server':'local',maxPendingSnapshots:MAX_PENDING_SNAPSHOTS};
})();
