/* v1.16 Bookmaru cumulative bank + checkpoint-safe auto advance + retry-safe save. */
(()=>{
  const game=document.querySelector('#game-screen');
  if(!game)return;
  const ACTIVITY_ID='vocabulary',ROUND_SIZE=7,SAVE_TIMEOUT_MS=5000,QUESTION_TIMEOUT_MS=5000,AUTO_NEXT_MS=850;
  const cloneQuestion=q=>({...q,options:Array.isArray(q.options)?[...q.options]:[],acceptedAnswers:Array.isArray(q.acceptedAnswers)?[...q.acceptedAnswers]:[]});
  const shuffle=values=>{const out=[...values];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
  const allSets=()=>Object.values(window.StudyVillageQuestionSets||{}).filter(set=>set?.bookmaru!==false&&Array.isArray(set?.questions)&&set.questions.length);
  const baseBank=()=>allSets().flatMap(set=>set.questions.map((q,i)=>({...cloneQuestion(q),_sourceActivityId:set.activityId,_sourceNumber:i+1,_subject:set.subject||'',_topic:set.topic||''})));
  function randomizeQuestion(raw){const item=cloneQuestion(raw);if(item.type==='input'||!item.options.length)return item;const correct=item.options[Number(item.answer)],options=shuffle(item.options);return{...item,options,answer:options.indexOf(correct)}}
  const buildRound=bank=>shuffle(bank).slice(0,Math.min(ROUND_SIZE,bank.length)).map(randomizeQuestion);
  let questionBank=baseBank(),questions=buildRound(questionBank),index=0,score=0,correctCount=0,answered=false,saving=false,opening=false,submissionId='',advanceTimer=null;
  if(!questionBank.length){console.error('[Studyvillage] Bookmaru question data missing');return}
  const panel=document.createElement('div');panel.id='library-game';panel.hidden=true;panel.innerHTML=`<div class="library-card"><button id="library-close" class="quiz-close">✕</button><span class="library-badge">📚 책마루</span><h2>일일 책마루 도전</h2><div class="library-status"><span id="library-progress">1 / 7</span><strong id="library-score">0점</strong></div><div class="library-word" id="library-word"></div><p class="library-guide">수수께끼·어휘·상식·교과 문제 중 오늘의 일곱 문제에 도전해요.</p><div id="library-options" class="library-options"></div><p id="library-feedback" class="library-feedback"></p><button id="library-next" class="interior-primary" hidden>다음 문제 ▶</button></div>`;game.appendChild(panel);
  const q=s=>panel.querySelector(s),close=q('#library-close'),progress=q('#library-progress'),scoreEl=q('#library-score'),word=q('#library-word'),options=q('#library-options'),feedback=q('#library-feedback'),next=q('#library-next');
  const headers=()=>window.StudyVillageAuth?.authHeaders?.()||{};
  const playerName=()=>document.querySelector('#profile-name')?.textContent?.trim()||'';
  const checkpoint=()=>window.StudyVillageCheckpoint;
  const validQuestion=item=>!!item&&typeof (item.word||item.question||item.prompt)==='string'&&String(item.word||item.question||item.prompt).trim().length>0&&(item.type==='input'?Array.isArray(item.acceptedAnswers)&&item.acceptedAnswers.length>0&&item.acceptedAnswers.every(v=>typeof v==='string'&&v.trim().length>0):Array.isArray(item.options)&&item.options.length>=2&&item.options.every(v=>typeof v==='string'&&v.trim().length>0)&&Number.isInteger(Number(item.answer))&&Number(item.answer)>=0&&Number(item.answer)<item.options.length);
  const newSubmissionId=()=>globalThis.crypto?.randomUUID?.()||`sv-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,12)}`;
  const percentScore=(correct,total)=>total>0?Math.round(Math.max(0,Math.min(correct,total))/total*100):0;
  async function timedFetch(url,options={},timeoutMs=QUESTION_TIMEOUT_MS){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timeout)}}
  async function loadQuestions(){questionBank=baseBank();try{const r=await timedFetch('/api/question-overrides',{cache:'no-store'});if(!r.ok)throw new Error('override-load-failed');const d=await r.json(),overrides=d?.overrides||{};questionBank=questionBank.map(base=>{const row=overrides[`${base._sourceActivityId}:${base._sourceNumber}`]?.question;if(!row||!validQuestion(row))return base;return {...cloneQuestion({...base,...row,answer:row.type==='input'?null:Number(row.answer)}),_sourceActivityId:base._sourceActivityId,_sourceNumber:base._sourceNumber,_subject:base._subject,_topic:base._topic}})}catch(err){console.warn('[Studyvillage] question override unavailable; using bundled questions',err?.name==='AbortError'?'timeout':err?.message||err)}}
  function saveCheckpoint(){const name=playerName();if(!name||!checkpoint())return;checkpoint().save(name,ACTIVITY_ID,{index,score,correctCount,total:questions.length,questions:questions.map(cloneQuestion),submissionId})}
  function clearCheckpoint(){const name=playerName();if(name&&checkpoint())checkpoint().clear(name,ACTIVITY_ID)}
  function readCheckpoint(){const name=playerName(),saved=name&&checkpoint()?checkpoint().load(name,ACTIVITY_ID):null,p=saved?.progress;if(!p)return null;const restored=Array.isArray(p.questions)?p.questions.map(cloneQuestion):[],savedIndex=Number(p.index),savedScore=Number(p.score);let savedCorrect=Number(p.correctCount);if(!Number.isInteger(savedCorrect))savedCorrect=Math.round(Math.max(0,Math.min(savedScore,100))/100*restored.length);if(!restored.length||restored.length>ROUND_SIZE||!restored.every(validQuestion)||!Number.isInteger(savedIndex)||savedIndex<0||savedIndex>=restored.length||!Number.isFinite(savedScore)||savedScore<0||savedScore>100||!Number.isInteger(savedCorrect)||savedCorrect<0||savedCorrect>restored.length)return null;return{index:savedIndex,score:percentScore(savedCorrect,restored.length),correctCount:savedCorrect,questions:restored,submissionId:typeof p.submissionId==='string'?p.submissionId:'',updatedAt:saved.updatedAt}}
  async function open(){if(opening||!panel.hidden)return;opening=true;try{index=0;score=0;correctCount=0;answered=false;saving=false;submissionId='';clearTimeout(advanceTimer);await loadQuestions();const saved=readCheckpoint();if(saved&&confirm(`이전에 풀던 책마루 기록이 있어요. ${saved.index+1}번 문제부터 이어서 할까요?`)){questions=saved.questions;index=saved.index;score=saved.score;correctCount=saved.correctCount;submissionId=saved.submissionId||''}else{if(saved)clearCheckpoint();questions=buildRound(questionBank)}panel.hidden=false;render()}finally{opening=false}}
  function render(){clearTimeout(advanceTimer);const item=questions[index];answered=false;saveCheckpoint();progress.textContent=`${index+1} / ${questions.length}`;scoreEl.textContent=`${score}점`;word.textContent=item.word||item.question||item.prompt||'';feedback.textContent='';feedback.className='library-feedback';next.hidden=true;next.onclick=null;options.innerHTML='';if(item.type==='input'){const input=document.createElement('input'),submit=document.createElement('button');input.className='library-answer-input';input.type='text';input.maxLength=80;input.autocomplete='off';input.placeholder='정답을 입력하세요';submit.className='library-option';submit.textContent='정답 확인 ✓';submit.onclick=()=>answer(input.value);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();submit.click()}});options.append(input,submit);setTimeout(()=>input.focus(),0)}else item.options.forEach((text,i)=>{const b=document.createElement('button');b.className='library-option';b.textContent=`${i+1}. ${text}`;b.onclick=()=>answer(i);options.appendChild(b)})}
  function answer(response){if(answered)return;const item=questions[index],isCorrect=window.StudyVillageQuestionResponse?.correct(item,response)===true;answered=true;const buttons=[...options.querySelectorAll('button')];buttons.forEach((b,j)=>{b.disabled=true;if(item.type!=='input'&&j===item.answer)b.classList.add('correct');if(item.type!=='input'&&j===response&&j!==item.answer)b.classList.add('wrong')});const input=options.querySelector('input');if(input){input.disabled=true;input.classList.add(isCorrect?'correct':'wrong')}if(isCorrect){correctCount++;feedback.textContent='정답이에요! 🌟';feedback.classList.add('success')}else{const correctText=item.type==='input'?item.acceptedAnswers[0]:item.options[item.answer];feedback.textContent=`아쉬워요. 정답은 “${correctText}”예요.`;feedback.classList.add('error')}score=percentScore(correctCount,questions.length);scoreEl.textContent=`${score}점`;saveCheckpoint();advanceTimer=setTimeout(()=>{if(panel.hidden)return;if(index===questions.length-1)finish();else{index++;render()}},AUTO_NEXT_MS)}
  async function saveActivity(){submissionId=submissionId||newSubmissionId();score=percentScore(correctCount,questions.length);saveCheckpoint();const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),SAVE_TIMEOUT_MS);try{const r=await fetch('/api/player/me/activity',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({activityId:ACTIVITY_ID,score,submissionId}),signal:controller.signal});if(!r.ok)throw new Error('save-failed');return r.json()}finally{clearTimeout(timeout)}}
  async function finish(){if(saving)return;saving=true;clearTimeout(advanceTimer);progress.textContent='완료';score=percentScore(correctCount,questions.length);word.textContent=score===100?'책마루 박사! 🏆':'책마루 도전 완료!';options.innerHTML='';feedback.textContent='기록 저장 중...';feedback.className='library-feedback';next.hidden=true;try{const result=await saveActivity();clearCheckpoint();submissionId='';const record=result.record||{},xp=result.gainedXp||0,stars=Number(result.activityStars)||0;feedback.textContent=`${questions.length}문제 중 ${correctCount}문제 정답 · ${score}점 · +${xp} XP · +${stars}별\n책마루 누적 ${record.attempts||1}회 · 오늘 ${record.periodAttempts||1}회`;feedback.className='library-feedback success';window.dispatchEvent(new CustomEvent('studyvillage:library-complete',{detail:{score,correct:correctCount,total:questions.length,gainedXp:xp,stars,record,player:result.player}}));window.dispatchEvent(new Event('studyvillage:stars-refresh'));next.hidden=false;next.textContent='책마루로 돌아가기';next.onclick=()=>{panel.hidden=true;next.onclick=null}}catch{saveCheckpoint();progress.textContent='저장 대기';word.textContent='교실 서버 연결을 기다리고 있어요.';feedback.textContent=`이번 ${score}점은 이 기기에 임시 보관했어요. 서버가 돌아온 뒤 다시 저장해 주세요.`;feedback.className='library-feedback error';next.hidden=false;next.textContent='결과 다시 저장하기 ↻';next.onclick=finish}finally{saving=false}}
  close.addEventListener('click',()=>{if(!saving){clearTimeout(advanceTimer);panel.hidden=true}});window.addEventListener('studyvillage:open-library-game',open);
})();
