/* v0.9.58 live village event presentation + resilient server receiver.
   Reconnecting students resume from the latest broadcast, and polling runs only while the student game is visible. */
(()=>{
  const game=document.querySelector('#game-screen'),queue=[],MAX_QUEUE=5,DUPLICATE_WINDOW_MS=10000,REQUEST_TIMEOUT_MS=4000;let showing=false,cursor=null,timer=null,polling=false,lastShownKey='',lastShownAt=0,authExpired=false;
  const style=document.createElement('style');style.textContent=`#studyvillage-live-events{position:fixed;left:50%;top:82px;transform:translateX(-50%);z-index:9998;width:min(92vw,620px);pointer-events:none;display:flex;justify-content:center;align-items:flex-start}#studyvillage-live-events .live-event-card{max-width:100%;padding:13px 18px;border-radius:18px;background:#fffdf2;border:2px solid #f0cf68;box-shadow:0 10px 28px #2d50382d;color:#2e4937;font-weight:900;text-align:center;opacity:0;transform:translateY(-12px);transition:opacity .22s ease,transform .22s ease}@media(max-width:760px){#studyvillage-live-events{top:116px;width:min(94vw,560px)}#studyvillage-live-events .live-event-card{padding:11px 14px;font-size:14px}}`;document.head.appendChild(style);
  const host=document.createElement('div');host.id='studyvillage-live-events';host.dataset.lane='top-announcement';host.setAttribute('aria-live','polite');document.body.appendChild(host);const card=document.createElement('div');card.className='live-event-card';card.hidden=true;host.appendChild(card);
  const safe=v=>String(v??'').slice(0,160),keyOf=e=>`${safe(e.icon||'✨')}|${safe(e.message||'')}`,active=()=>!authExpired&&!document.hidden&&navigator.onLine&&(!game||game.classList.contains('active'));
  function next(){if(showing||!queue.length)return;showing=true;const e=queue.shift(),key=keyOf(e);lastShownKey=key;lastShownAt=Date.now();card.textContent=`${safe(e.icon||'✨')} ${safe(e.message||'마을에 새로운 소식이 있어요!')}`;card.hidden=false;requestAnimationFrame(()=>{card.style.opacity='1';card.style.transform='translateY(0)'});setTimeout(()=>{card.style.opacity='0';card.style.transform='translateY(-12px)';setTimeout(()=>{card.hidden=true;showing=false;next()},240)},Math.max(1800,Math.min(6000,Number(e.duration)||3600)))}
  function show(event={}){const item={icon:event.icon||'✨',message:event.message||'',duration:event.duration||3600,type:event.type||'celebration'},key=keyOf(item),now=Date.now();if((key===lastShownKey&&now-lastShownAt<DUPLICATE_WINDOW_MS)||queue.some(e=>keyOf(e)===key))return false;if(queue.length>=MAX_QUEUE)queue.shift();queue.push(item);next();return true}
  async function poll(){if(polling||!active())return;const headers=window.StudyVillageAuth?.authHeaders?.()||{};if(!headers.Authorization)return;polling=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const after=cursor===null?'latest':String(cursor),r=await fetch(`/api/live-events?after=${encodeURIComponent(after)}`,{headers,cache:'no-store',signal:controller.signal});if(r.status===401){authExpired=true;stop();return}if(!r.ok)return;const d=await r.json();if(Number.isFinite(Number(d.cursor)))cursor=Number(d.cursor);for(const e of d.events||[])show(e)}catch{}finally{clearTimeout(timeout);polling=false}}
  function start(immediate=true){if(timer||!active())return;if(immediate)poll();timer=setInterval(poll,3000)}function stop(){if(timer){clearInterval(timer);timer=null}}function resumeFromLatest(){authExpired=false;cursor=null;start(true)}
  window.addEventListener('studyvillage:live-event',e=>show(e.detail||{}));window.addEventListener('studyvillage:session-ready',resumeFromLatest);window.addEventListener('online',()=>{if(!authExpired)resumeFromLatest()});window.addEventListener('offline',stop);window.addEventListener('focus',()=>{start(true);poll()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else start()});
  if(game){const observer=new MutationObserver(()=>{if(game.classList.contains('active'))resumeFromLatest();else stop()});observer.observe(game,{attributes:true,attributeFilter:['class']})}
  setTimeout(start,1500);window.StudyVillageLiveEvents={show,poll,lane:'top-announcement',maxQueue:MAX_QUEUE};
})();
