/* v2.2 randomized village NPC encounters. */
(()=>{
  const game=document.querySelector('#game-screen'),map=document.querySelector('#world-map'),player=document.querySelector('#player'),talk=document.querySelector('#talk-button');
  if(!game||!map||!player)return;
  const roster=[
    {id:'wizard',icon:'🧙',name:'별빛 마법사',lines:['호기심은 새로운 길을 여는 가장 멋진 주문이란다.','생각의 숲에서는 서두르지 말고 단서를 천천히 살펴봐.','틀린 답도 다음 정답으로 가는 중요한 발자국이야.']},
    {id:'ghost',icon:'👻',name:'책방 유령',lines:['놀라지 마! 나는 재미있는 이야기를 모으는 유령이야.','책마루의 낱말을 익히면 숨은 문장이 보일지도 몰라.','오늘 새로 알게 된 낱말 하나를 마음속 보물상자에 넣어 둬.']},
    {id:'dragon',icon:'🐲',name:'꼬마 용',lines:['도전의 산 정상에는 끝까지 해낸 사람만 보는 풍경이 있어.','어려운 문제를 만나면 보기부터 하나씩 살펴보자.','용기도 연습할수록 자란대. 나와 함께 한 번 더 도전해 봐!']},
    {id:'fox',icon:'🦊',name:'숲길 여우',lines:['길이 헷갈리면 지나온 곳과 아직 안 가 본 곳을 나눠 봐.','생각의 숲 수수께끼는 말 속에 단서가 숨어 있어.','같은 탐험도 문제와 순서가 바뀌니 매번 새롭게 살펴봐!']},
    {id:'robot',icon:'🤖',name:'기록 로봇',lines:['삐빅! 작은 도전도 차곡차곡 기록되고 있어.','내 기록에서 점수뿐 아니라 꾸준히 도전한 횟수도 확인해 봐.','오늘의 목표를 하나 정하면 성장 기록이 더 또렷해져.']},
    {id:'owl',icon:'🦉',name:'지혜 부엉이',lines:['정답을 고르기 전에 문제에서 가장 중요한 말을 찾아보렴.','아는 것과 짐작한 것을 구분하면 생각이 더 선명해져.','밤에도 낮에도 좋은 질문은 반짝반짝 빛난단다.']}
  ];
  const spots=[{x:38,y:18},{x:73,y:20},{x:19,y:38},{x:80,y:62},{x:35,y:76},{x:68,y:78}];
  const shuffle=values=>{const out=[...values];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
  const selected=shuffle(roster).slice(0,3),selectedSpots=shuffle(spots).slice(0,3);
  const style=document.createElement('style');style.textContent=`
    .sv-random-npc{position:absolute;z-index:5;width:82px;text-align:center;user-select:none;filter:drop-shadow(0 6px 5px #24472d2e)}.sv-random-npc-icon{display:block;font-size:50px;transition:transform .18s}.sv-random-npc:hover .sv-random-npc-icon,.sv-random-npc.near .sv-random-npc-icon{transform:translateY(-4px)}.sv-random-npc-name{display:inline-block;padding:4px 8px;border:2px solid #fff;border-radius:10px;background:#fffdf1ed;color:#35553d;font-size:11px;font-weight:1000;white-space:nowrap;transform:translateX(-10%)}.sv-random-npc-bubble{position:absolute;left:50%;bottom:76px;transform:translateX(-50%);padding:6px 9px;border-radius:12px;background:#fff;color:#426048;font-size:11px;font-weight:1000;white-space:nowrap;box-shadow:0 5px 15px #24472d30;opacity:0;pointer-events:none}.sv-random-npc.near .sv-random-npc-bubble{opacity:1}.sv-npc-dialogue{position:absolute;left:50%;bottom:18px;z-index:175;width:min(760px,calc(100vw - 28px));min-height:142px;transform:translateX(-50%);display:grid;grid-template-columns:86px 1fr auto;align-items:center;gap:16px;padding:19px 21px;border:5px solid #fff;border-radius:28px;background:linear-gradient(145deg,#fff9dc,#eef8e9);box-shadow:0 20px 60px #17382266}.sv-npc-dialogue[hidden]{display:none}.sv-npc-dialogue-icon{font-size:55px;text-align:center}.sv-npc-dialogue strong{color:#345a3f;font-size:18px}.sv-npc-dialogue p{margin:8px 0 0;color:#526858;font-size:17px;font-weight:800;line-height:1.45}.sv-npc-dialogue button{border:0;border-radius:14px;padding:12px 17px;background:#ffca4b;color:#5d4505;font-weight:1000;cursor:pointer}@media(max-width:700px),(pointer:coarse){.sv-random-npc{width:68px}.sv-random-npc-icon{font-size:44px}.sv-npc-dialogue{bottom:102px;grid-template-columns:58px 1fr;padding:16px}.sv-npc-dialogue-icon{font-size:43px}.sv-npc-dialogue button{grid-column:1/3;width:100%}}
  `;document.head.appendChild(style);
  const elements=selected.map((npc,index)=>{const spot=selectedSpots[index],el=document.createElement('div');el.className='sv-random-npc obstacle';el.dataset.npcId=npc.id;el.style.left=`${spot.x}%`;el.style.top=`${spot.y}%`;el.innerHTML=`<span class="sv-random-npc-bubble">✨ 가까이에서 대화</span><span class="sv-random-npc-icon">${npc.icon}</span><span class="sv-random-npc-name">${npc.name}</span>`;map.appendChild(el);return{...npc,el}});
  const panel=document.createElement('section');panel.className='sv-npc-dialogue';panel.hidden=true;panel.innerHTML='<div class="sv-npc-dialogue-icon"></div><div><strong></strong><p></p></div><button type="button">다음 ▶</button>';game.appendChild(panel);
  const panelIcon=panel.querySelector('.sv-npc-dialogue-icon'),panelName=panel.querySelector('strong'),panelText=panel.querySelector('p'),next=panel.querySelector('button');
  let active=null,line=0,near=null;
  function distance(el){const a=player.getBoundingClientRect(),b=el.getBoundingClientRect();return Math.hypot(a.left+a.width/2-(b.left+b.width/2),a.top+a.height/2-(b.top+b.height/2))}
  function nearest(){let best=null;for(const npc of elements){const d=distance(npc.el);if(d<145&&(!best||d<best.distance))best={npc,distance:d}}return best?.npc||null}
  function remember(npc){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);fetch('/api/player/me/exploration-collection',{method:'POST',headers:{'Content-Type':'application/json',...(window.StudyVillageAuth?.authHeaders?.()||{})},body:JSON.stringify({kind:'npc',id:npc.id}),signal:controller.signal}).then(response=>{if(response.ok)window.dispatchEvent(new Event('studyvillage:exploration-collection-refresh'))}).catch(()=>{}).finally(()=>clearTimeout(timer))}
  function open(npc){active=npc;line=Math.floor(Math.random()*npc.lines.length);window.dispatchEvent(new Event('blur'));panelIcon.textContent=npc.icon;panelName.textContent=npc.name;panelText.textContent=npc.lines[line];next.textContent=npc.lines.length>1?'다음 ▶':'닫기';panel.hidden=false;remember(npc)}
  function advance(){if(!active)return close();line=(line+1)%active.lines.length;if(line===0)return close();panelText.textContent=active.lines[line];next.textContent=line===active.lines.length-1?'대화 마치기 ✓':'다음 ▶'}
  function close(){panel.hidden=true;active=null}
  function interact(event){if(!panel.hidden){event?.preventDefault();event?.stopImmediatePropagation();advance();return true}const npc=nearest();if(!npc)return false;event?.preventDefault();event?.stopImmediatePropagation();open(npc);return true}
  window.addEventListener('keydown',event=>{if(!panel.hidden){if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();close();return}if(event.code==='Space'||event.key==='Enter'){interact(event);return}const key=typeof event.key==='string'?event.key.toLowerCase():'';if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(key)){event.preventDefault();event.stopImmediatePropagation()}return}if(event.code==='Space'||event.key==='Enter')interact(event)},true);
  talk?.addEventListener('click',event=>interact(event),true);next.onclick=advance;
  function loop(){if(game.classList.contains('active')&&panel.hidden){const current=nearest();if(current!==near){near?.el.classList.remove('near');current?.el.classList.add('near');near=current}if(talk)talk.textContent=current?`💬 ${current.name}`:'✨ 상호작용'}requestAnimationFrame(loop)}
  requestAnimationFrame(loop);
})();
