/* v1.9 student star shop panel. Purchasing is atomic on the server and refreshes star/ownership records. */
(()=>{
  const panel=document.querySelector('#customize-panel');if(!panel)return;
  const icons={'cap-blue':'🧢','crown-gold':'👑','glasses-round':'👓','backpack':'🎒','pet-chick':'🐣','pet-cat':'🐱','leaf-cap':'🍃','scholar-cap':'🎓','explorer-goggles':'🥽','star-monocle':'🔭','field-satchel':'🧰','book-pack':'📚','pet-owl':'🦉','pet-fox':'🦊'};
  const headers=()=>window.StudyVillageAuth?.authHeaders?.()||{};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const REQUEST_TIMEOUT_MS=5000;
  const shop=document.createElement('section');shop.className='inventory-group student-shop';shop.innerHTML='<div class="student-shop-head"><h3>⭐ 별 상점</h3><strong id="student-shop-balance">0별</strong></div><p id="student-shop-status" class="record-message">상점 정보를 불러오는 중이에요.</p><div id="student-shop-filters" class="student-shop-filters" role="group" aria-label="아이템 종류"><button type="button" data-shop-slot="all" aria-pressed="true">전체</button><button type="button" data-shop-slot="hat">모자</button><button type="button" data-shop-slot="glasses">안경</button><button type="button" data-shop-slot="bag">가방</button><button type="button" data-shop-slot="pet">친구</button></div><div id="student-shop-items" class="inventory-items"></div>';
  const inventory=document.querySelector('#inventory-list');inventory?.before(shop);
  const balance=shop.querySelector('#student-shop-balance'),status=shop.querySelector('#student-shop-status'),filters=shop.querySelector('#student-shop-filters'),list=shop.querySelector('#student-shop-items');
  let busy=false,loadPromise=null,activeSlot='all',lastData=null;
  async function timedFetch(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
  function render(data={}){
    lastData=data;const owned=new Set(Array.isArray(data.ownedItems)?data.ownedItems:[]);balance.textContent=`${Math.max(0,Number(data.balance)||0)}별`;list.innerHTML='';
    if(!data.enabled){status.textContent='지금은 선생님이 상점을 닫아 두었어요.';filters.hidden=true;list.hidden=true;return}
    filters.hidden=false;list.hidden=false;status.textContent='별로 원하는 아이템을 살 수 있어요. 구매 기록은 내 별 장부에 남아요.';
    const items=(data.items||[]).filter(item=>activeSlot==='all'||item.slot===activeSlot);for(const item of items){const bought=owned.has(item.id),available=item.available!==false,salePending=item.salePending===true,saleEnded=item.saleEnded===true,requiredLevel=Math.max(1,Number(item.requiredLevel)||1),levelOk=(Number(data.currentLevel)||1)>=requiredLevel,startLabel=item.saleStartsAt?new Date(item.saleStartsAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'',endLabel=item.saleEndsAt?new Date(item.saleEndsAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'',b=document.createElement('button');b.type='button';b.className=`inventory-item ${bought?'selected':''}`;b.disabled=bought||!available||salePending||saleEnded||!levelOk||busy;b.innerHTML=`<span>${icons[item.id]||'🎁'}</span><strong>${esc(item.name)}${item.limited?`<em title="${esc(endLabel?`${endLabel} 종료`:'한정 판매')}">한정</em>`:''}</strong><small>${bought?'구매 완료':!available?'판매 중지':salePending?`판매 예정 · ${esc(startLabel)}`:saleEnded?'판매 종료':!levelOk?`Lv.${requiredLevel}부터 구매`:`${Number(item.price)||0}별 · 구매${item.limited&&endLabel?` · ${esc(endLabel)}까지`:''}`}</small>`;if(!bought&&available&&!salePending&&!saleEnded&&levelOk)b.onclick=()=>purchase(item);list.appendChild(b)}
    if(!items.length)list.innerHTML='<p class="student-shop-empty">이 종류의 아이템은 아직 없어요.</p>';
  }
  async function load(){if(loadPromise)return loadPromise;loadPromise=(async()=>{try{const r=await timedFetch('/api/shop',{headers:headers(),cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error();render(d);return d}catch(err){status.textContent=err?.name==='AbortError'?'상점 정보를 불러오는 시간이 초과됐어요.':'상점 정보를 불러오지 못했어요.';return null}})();try{return await loadPromise}finally{loadPromise=null}}
  async function equipPurchased(itemId){const state=await load();const item=(state?.items||[]).find(x=>x.id===itemId);if(!item)return false;window.dispatchEvent(new CustomEvent('studyvillage:equip-purchased-item',{detail:{itemId,itemName:item.name}}));return true}
  async function purchase(item){if(busy)return;if(!confirm(`${item.name}을(를) ${item.price}별에 살까요?\n구매한 별 사용 기록은 내 별 장부에 남습니다.`))return;busy=true;status.textContent='구매 중…';let refreshed=false;try{const r=await timedFetch('/api/shop/purchase',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({itemId:item.id})}),d=await r.json();if(!r.ok||!d.ok){if(d.code==='insufficient-stars')status.textContent=`별이 부족해요. 현재 ${d.balance||0}별이 있어요.`;else if(d.code==='shop-disabled')status.textContent='상점이 방금 닫혔어요.';else if(d.code==='item-unavailable')status.textContent='이 아이템은 방금 판매가 중지됐어요.';else if(d.code==='sale-pending')status.textContent='아직 판매 시작 전인 한정 아이템이에요.';else if(d.code==='sale-ended')status.textContent='이 한정 아이템의 판매 시간이 끝났어요.';else if(d.code==='level-required')status.textContent='이 아이템은 Lv.'+d.requiredLevel+'부터 살 수 있어요. 현재 Lv.'+d.currentLevel+'이에요.';else if(d.code==='already-owned')status.textContent='이미 가지고 있는 아이템이에요.';else status.textContent='구매하지 못했어요.';return}status.textContent=`🎁 ${d.itemName} 구매 완료! ${d.balance}별이 남았어요.`;window.dispatchEvent(new CustomEvent('studyvillage:shop-purchase',{detail:d}));window.dispatchEvent(new Event('studyvillage:activity-record-refresh'));const state=await load();refreshed=!!state;if(confirm(`${d.itemName} 구매 완료! 🎁\n지금 바로 장착할까요?`)){const found=(state?.items||[]).find(x=>x.id===d.itemId);if(found)window.dispatchEvent(new CustomEvent('studyvillage:equip-purchased-item',{detail:{itemId:d.itemId,itemName:found.name}}))}}catch(err){status.textContent=err?.name==='AbortError'?'구매 요청 시간이 초과됐어요. 잠시 후 별 장부를 확인해 주세요.':'구매 중 연결 문제가 생겼어요.'}finally{busy=false;if(!refreshed)await load()}}
  filters.addEventListener('click',event=>{const button=event.target.closest('button[data-shop-slot]');if(!button)return;activeSlot=button.dataset.shopSlot||'all';for(const candidate of filters.querySelectorAll('button[data-shop-slot]'))candidate.setAttribute('aria-pressed',String(candidate===button));if(lastData)render(lastData)});document.querySelector('#customize-button')?.addEventListener('click',()=>setTimeout(load,0));window.addEventListener('studyvillage:shop-refresh',load);
})();
