/* v1.15 student star shop: base character / one-piece outfit / effect / pet production categories. */
(()=>{
  const game=document.querySelector('#game-screen'),shopButton=document.querySelector('#shop-button');if(!game||!shopButton)return;
  const icons={'character-boy-02':'👦','character-boy-03':'👦','character-boy-04':'👦','character-boy-05':'👦','character-girl-02':'👧','character-girl-03':'👧','character-girl-04':'👧','character-girl-05':'👧','outfit-silver-knight':'🛡️','outfit-star-mage-production':'🪄','outfit-school-scientist':'🔬','outfit-forest-archer-production':'🏹','outfit-pirate-captain-production':'🏴‍☠️','outfit-moon-priest-production':'🌙','outfit-starlight-dress-production':'🌟','outfit-flower-fairy-production':'🌸','outfit-ribbon-magical-girl-production':'🎀','pet-maltese-production':'🐶','pet-toy-poodle-production':'🐩','pet-corgi-production':'🐶','pet-cheese-cat-production':'🐱','pet-lop-rabbit-production':'🐰','pet-baby-dragon-production':'🐲','aurora-effect':'🌈','candy':'🍬','stationery':'✏️'};
  const headers=()=>window.StudyVillageAuth?.authHeaders?.()||{};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const REQUEST_TIMEOUT_MS=5000;
  document.querySelector('#student-shop-panel')?.remove();
  const panel=document.createElement('section');panel.id='student-shop-panel';panel.className='record-panel student-shop-panel';panel.hidden=true;
  panel.innerHTML='<div class="record-header"><div><span class="record-badge">별 상점</span><h2>⭐ 꾸미기 상점</h2></div><button id="student-shop-close" class="quiz-close" type="button">✕</button></div><p class="student-shop-help">여기서는 기본 캐릭터, 한벌 의상, 효과, 펫을 구매해요. 구매한 것은 위쪽의 <b>내 옷장</b>에서 조합할 수 있어요.</p>';
  const shop=document.createElement('section');shop.className='inventory-group student-shop';shop.innerHTML='<div class="student-shop-head"><h3>판매 목록</h3><strong id="student-shop-balance">0별</strong></div><p id="student-shop-status" class="record-message">상점 정보를 불러오는 중이에요.</p><div id="student-shop-filters" class="student-shop-filters" role="group" aria-label="아이템 종류"><button type="button" data-shop-slot="all" aria-pressed="true">전체</button><button type="button" data-shop-slot="character">기본 캐릭터</button><button type="button" data-shop-slot="outfit">한벌 의상</button><button type="button" data-shop-slot="effect">효과</button><button type="button" data-shop-slot="pet">펫</button><button type="button" data-shop-slot="physical">실물</button></div><div id="student-shop-items" class="inventory-items"></div>';
  panel.appendChild(shop);game.appendChild(panel);
  if(!document.querySelector('#student-shop-panel-style')){const style=document.createElement('style');style.id='student-shop-panel-style';style.textContent='#student-shop-panel{width:min(760px,calc(100vw - 28px));max-height:min(86dvh,760px);overflow:auto;z-index:251}.student-shop-help{padding:10px 13px;border-radius:14px;background:#eef7e9;color:#49624f;font-weight:800}#student-shop-panel #student-shop-items{max-height:none}';document.head.appendChild(style)}
  const balance=shop.querySelector('#student-shop-balance'),status=shop.querySelector('#student-shop-status'),filters=shop.querySelector('#student-shop-filters'),list=shop.querySelector('#student-shop-items');
  let busy=false,loadPromise=null,activeSlot='all',lastData=null,transitionTimer=null;
  async function timedFetch(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
  function scheduleTransition(data){if(transitionTimer){clearTimeout(transitionTimer);transitionTimer=null}if(!data?.enabled)return;const serverNow=Date.parse(data.serverNow);if(!Number.isFinite(serverNow))return;const future=[];for(const item of data.items||[]){if(!item.limited)continue;for(const value of [item.saleStartsAt,item.saleEndsAt]){const time=Date.parse(value);if(Number.isFinite(time)&&time>serverNow)future.push(time)}}if(!future.length)return;const delay=Math.min(2147483000,Math.max(250,Math.min(...future)-serverNow+250));transitionTimer=setTimeout(()=>{transitionTimer=null;load()},delay)}
  function paintProductPreview(button,item,baseCharacter='student-boy'){const renderer=window.StudyVillageAvatar;if(['physical','effect'].includes(item.slot)||!renderer)return;const host=button.querySelector('span');if(!host)return;host.className='shop-wearable-preview';host.replaceChildren();if(item.slot==='character'){const base=document.createElement('i');base.className='shop-preview-base';host.append(base);renderer.paintBase(base,item.id);return}if(!renderer.ASSETS?.[item.id])return;const base=document.createElement('i'),part=document.createElement('i'),previewBase=renderer.BASES?.[baseCharacter]?baseCharacter:'student-boy';base.className=item.slot==='outfit'?'shop-preview-base shop-preview-head-only':'shop-preview-base';part.className=`shop-preview-part shop-preview-${item.slot}`;host.append(base);renderer.paintBase(base,previewBase);host.append(part);renderer.paintItem(part,item.id)}
  function render(data={}){const fresh=data!==lastData;lastData=data;if(fresh)scheduleTransition(data);const owned=new Set(Array.isArray(data.ownedItems)?data.ownedItems:[]);balance.textContent=`${Math.max(0,Number(data.balance)||0)}별`;list.innerHTML='';if(!data.enabled){status.textContent='지금은 선생님이 상점을 닫아 두었어요.';filters.hidden=true;list.hidden=true;return}filters.hidden=false;list.hidden=false;const pending=(data.deliveryRequests||[]).filter(row=>row.status==='pending').length;status.textContent=pending?`별로 원하는 아이템을 살 수 있어요. 선생님 전달을 기다리는 실물 요청이 ${pending}개 있어요.`:'별로 원하는 아이템을 살 수 있어요. 구매 기록은 내 별 장부에 남아요.';const currentBalance=Math.max(0,Number(data.balance)||0),items=(data.items||[]).filter(item=>activeSlot==='all'||item.slot===activeSlot);for(const item of items){const physical=item.fulfillment==='teacher-delivery',bought=!physical&&owned.has(item.id),available=item.available!==false,salePending=item.salePending===true,saleEnded=item.saleEnded===true,price=Math.max(0,Number(item.price)||0),affordable=currentBalance>=price,missingStars=Math.max(0,price-currentBalance),requiredLevel=Math.max(1,Number(item.requiredLevel)||1),levelOk=(Number(data.currentLevel)||1)>=requiredLevel,startLabel=item.saleStartsAt?new Date(item.saleStartsAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'',endLabel=item.saleEndsAt?new Date(item.saleEndsAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'',b=document.createElement('button');b.type='button';b.className=`inventory-item ${bought?'selected':''}`;b.disabled=bought||!available||salePending||saleEnded||!levelOk||!affordable||busy;b.innerHTML=`<span>${icons[item.id]||'🎁'}</span><strong>${esc(item.name)}${item.limited?`<em title="${esc(endLabel?`${endLabel} 종료`:'한정 판매')}">한정</em>`:''}</strong><small>${bought?'구매 완료':!available?'판매 중지':salePending?`판매 예정 · ${esc(startLabel)}`:saleEnded?'판매 종료':!levelOk?`Lv.${requiredLevel}부터 구매`:!affordable?`${price}별 · ${missingStars}별 더 필요`:physical?`${price}별 · 선생님께 전달 요청`:`${price}별 · 구매${item.limited&&endLabel?` · ${esc(endLabel)}까지`:''}`}</small>`;if(!bought&&available&&!salePending&&!saleEnded&&levelOk&&affordable)b.onclick=()=>purchase(item);paintProductPreview(b,item,data.baseCharacter);list.appendChild(b)}if(!items.length)list.innerHTML='<p class="student-shop-empty">이 종류의 아이템은 아직 없어요.</p>'}
  async function load(){if(loadPromise)return loadPromise;loadPromise=(async()=>{try{const r=await timedFetch('/api/shop',{headers:headers(),cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error();render(d);return d}catch(err){status.textContent=err?.name==='AbortError'?'상점 정보를 불러오는 시간이 초과됐어요.':'상점 정보를 불러오지 못했어요.';return null}})();try{return await loadPromise}finally{loadPromise=null}}
  async function purchase(item){if(busy)return;const physical=item.fulfillment==='teacher-delivery',question=physical?`${item.name}을(를) ${item.price}별에 신청할까요?\n별은 지금 바로 차감되고 선생님께 전달 요청이 남습니다.`:`${item.name}을(를) ${item.price}별에 살까요?\n구매한 별 사용 기록은 내 별 장부에 남습니다.`;if(!confirm(question))return;busy=true;status.textContent=physical?'전달 요청 중…':'구매 중…';let refreshed=false;try{const r=await timedFetch('/api/shop/purchase',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({itemId:item.id})}),d=await r.json();if(!r.ok||!d.ok){if(d.code==='insufficient-stars')status.textContent=`별이 부족해요. 현재 ${d.balance||0}별이 있어요.`;else if(d.code==='shop-disabled')status.textContent='상점이 방금 닫혔어요.';else if(d.code==='item-unavailable')status.textContent='이 아이템은 방금 판매가 중지됐어요.';else if(d.code==='sale-pending')status.textContent='아직 판매 시작 전인 한정 아이템이에요.';else if(d.code==='sale-ended')status.textContent='이 한정 아이템의 판매 시간이 끝났어요.';else if(d.code==='level-required')status.textContent='이 아이템은 Lv.'+d.requiredLevel+'부터 살 수 있어요. 현재 Lv.'+d.currentLevel+'이에요.';else if(d.code==='already-owned')status.textContent='이미 가지고 있는 아이템이에요.';else status.textContent='구매하지 못했어요.';return}status.textContent=d.fulfillment==='teacher-delivery'?`📦 ${d.itemName} 전달 요청 완료! ${d.balance}별이 남았어요. 선생님이 물건을 전달하면 완료 처리합니다.`:`🎁 ${d.itemName} 구매 완료! ${d.balance}별이 남았어요.`;window.dispatchEvent(new CustomEvent('studyvillage:shop-purchase',{detail:d}));window.dispatchEvent(new Event('studyvillage:activity-record-refresh'));busy=false;const state=await load();refreshed=!!state;if(d.fulfillment==='teacher-delivery')return;const found=(state?.items||[]).find(x=>x.id===d.itemId);if(found?.slot==='effect'){status.textContent='🌈 '+d.itemName+' 구매 완료! 성장 효과가 자동으로 켜졌어요.';window.dispatchEvent(new Event('studyvillage:shop-refresh'))}else if(confirm(`${d.itemName} 구매 완료! 🎁\n지금 바로 장착할까요?`)){if(found)window.dispatchEvent(new CustomEvent('studyvillage:equip-purchased-item',{detail:{itemId:d.itemId,itemName:found.name}}))}}catch(err){status.textContent=err?.name==='AbortError'?'구매 요청 시간이 초과됐어요. 잠시 후 별 장부를 확인해 주세요.':'구매 중 연결 문제가 생겼어요.'}finally{busy=false;if(!refreshed)await load()}}
  async function openShop(){document.querySelector('#customize-panel')?.setAttribute('hidden','');panel.hidden=false;status.textContent='상점 정보를 불러오는 중이에요.';await load()}
  function closeShop(){if(busy)return;panel.hidden=true;shopButton.focus?.()}
  filters.addEventListener('click',event=>{const button=event.target.closest('button[data-shop-slot]');if(!button)return;activeSlot=button.dataset.shopSlot||'all';for(const candidate of filters.querySelectorAll('button[data-shop-slot]'))candidate.setAttribute('aria-pressed',String(candidate===button));if(lastData)render(lastData)});shopButton.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();openShop()},true);panel.querySelector('#student-shop-close')?.addEventListener('click',closeShop);window.addEventListener('keydown',event=>{if(event.key==='Escape'&&!panel.hidden){event.preventDefault();event.stopImmediatePropagation();closeShop()}},true);window.addEventListener('studyvillage:shop-refresh',load);window.addEventListener('studyvillage:stars-refresh',()=>{if(!panel.hidden)load()});window.addEventListener('pagehide',()=>{if(transitionTimer)clearTimeout(transitionTimer)},{once:true});window.addEventListener('focus',()=>{if(!panel.hidden)load()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!panel.hidden)load()});
})();
