/* Village layout + student-facing theme + classroom ranking.
   Exploration is intentionally owned by assets/student-study-menu.js only. */
(()=>{
  const map=document.querySelector('#world-map');
  if(!map)return;
  const style=document.createElement('style');
  style.textContent=`
    .village-road{position:absolute;z-index:0;background:#e7d29d;border:5px solid #d3ba7d;border-radius:30px;box-shadow:inset 0 0 0 3px #f1dfae}
    .road-h{left:8%;top:48%;width:84%;height:120px}.road-v{left:47%;top:7%;width:140px;height:86%}
    .road-nw{left:24%;top:27%;width:34%;height:90px;transform:rotate(-28deg);transform-origin:left center}.road-ne{left:50%;top:27%;width:29%;height:90px;transform:rotate(24deg);transform-origin:left center}
    .road-sw{left:22%;top:58%;width:36%;height:90px;transform:rotate(26deg);transform-origin:left center}.road-se{left:50%;top:58%;width:35%;height:90px;transform:rotate(-25deg);transform-origin:left center}
    .village-plaza{position:absolute;left:50%;top:52%;width:310px;height:250px;transform:translate(-50%,-50%);z-index:1;border-radius:48%;background:#f2dfa9;border:10px solid #d7bd7c;box-shadow:0 10px 24px #56733d2c,inset 0 0 0 8px #f8ebc8}
    .village-plaza:after{content:'🌳 마을 광장';position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);padding:10px 18px;border-radius:18px;background:#ffffffe8;color:#426044;font-weight:900;white-space:nowrap}
    .shop-zone{position:absolute;left:35%;top:65%;bottom:auto;z-index:5;font-size:72px;text-align:center}.shop-zone span{display:block;margin-top:-8px;padding:5px 10px;border-radius:13px;background:#ffffffe8;color:#31513a;font-size:14px;font-weight:900}
    .flower{position:absolute;z-index:1;font-size:30px;opacity:.9}.f1{left:36%;top:40%}.f2{left:61%;top:66%}.f3{left:19%;top:70%}.f4{right:20%;top:35%}
  `;
  document.head.appendChild(style);
  const add=(cls,html='')=>{const el=document.createElement('div');el.className=cls;el.innerHTML=html;map.appendChild(el);return el};
  add('village-road road-h');add('village-road road-v');add('village-road road-nw');add('village-road road-ne');add('village-road road-sw');add('village-road road-se');add('village-plaza');
  add('shop-zone obstacle','🏪<span>꾸미기 상점</span>');
  const schoolLabel=map.querySelector('.school span');if(schoolLabel)schoolLabel.textContent='교과 배움터';
  add('flower f1','🌼');add('flower f2','🌷');add('flower f3','🌻');add('flower f4','🌸');
})();

/* student-facing interior theme and live classroom ranking */
(()=>{
  const game=document.querySelector('#game-screen'),hud=document.querySelector('.hud-right');
  if(!game||!hud)return;
  const style=document.createElement('style');
  style.textContent=`
    #game-screen{background:#63ad50}.hud{position:relative;z-index:150;min-height:68px;background:#fffdf3f5;border-bottom:1px solid #dce8d8;box-shadow:0 5px 20px #264e3420}.hud>strong{display:flex;align-items:center;gap:6px;color:#285a39;letter-spacing:-.03em}.hud-right{flex-wrap:wrap;justify-content:flex-end}.record-button{border:1px solid #d9e8d6;background:#f1f8ee;color:#356243;box-shadow:0 2px 7px #315d3b12;transition:transform .15s,background .15s}.record-button:active{transform:translateY(1px)}#customize-button{background:#fff3df;color:#875c22;border-color:#f1dab7}#record-button{background:#edf3ff;color:#4d5f8e;border-color:#d9e3f7}#student-exit-button{background:#fff0ef;color:#974c49;border-color:#f1d6d3}.player-profile{border:1px solid #e1eadf;box-shadow:0 3px 10px #315d3b10}.large-world-viewport{background:linear-gradient(#75c861,#69b655)}.world-map{border-radius:28px;box-shadow:inset 0 0 0 8px #ffffff18}.building,.shop-zone{filter:drop-shadow(0 8px 6px #29492f28)}.building span,.shop-zone span{border:2px solid #fff;box-shadow:0 5px 12px #29492f22}.interaction-hint{bottom:18px;padding:10px 17px;background:#244b32f2;box-shadow:0 7px 20px #18342138}
    .quiz-panel,.record-panel{border:1px solid #e4eadf;border-radius:26px;background:#fffdf8;box-shadow:0 24px 70px #17382255}.quiz-header,.record-header{padding-bottom:13px;border-bottom:1px solid #edf0e9}.quiz-option,.library-option{border-width:2px;box-shadow:0 3px 10px #51447c0d;transition:transform .15s}.quiz-option:active,.library-option:active{transform:scale(.99)}.inventory-group{padding:14px;border-radius:18px;background:#f5f8f2}.inventory-item{box-shadow:0 4px 12px #315d3b0e}.student-shop{background:#fff8e6!important;border:1px solid #f2dfad}.student-shop-head{display:flex;align-items:center;justify-content:space-between}.student-shop-head h3{margin:0}.student-shop-head strong{padding:6px 10px;border-radius:999px;background:#ffe89a;color:#74570b}
    #building-interior{background:linear-gradient(135deg,#e7f2dc,#f6ecd6)}.interior-room{border:1px solid #ffffffdd;background:linear-gradient(#fffdf8 0 76%,#f1dfbd 76%);box-shadow:0 26px 75px #203c2942,0 0 0 8px #ffffff5c}.interior-exit{border:1px solid #dce8d8;background:#fff;box-shadow:0 4px 12px #315d3b15}.interior-icon{filter:drop-shadow(0 8px 7px #315d3b22)}.interior-label{background:#6d9d75}.interior-primary{background:linear-gradient(#ffdb68,#ffc846);box-shadow:0 6px 0 #d99d18,0 12px 24px #d99d1828}.interior-coming{border:1px dashed #cddac9;background:#f6f9f4;color:#657568}
    #library-game{background:#1739238c;backdrop-filter:blur(6px)}.library-card{border:1px solid #ffffffdd;background:linear-gradient(145deg,#fffef9,#f7fbf4);box-shadow:0 25px 75px #152d1d55,0 0 0 8px #ffffff40}.library-badge{background:#559264}.library-status{border:1px solid #d9ead3}.library-word{padding:17px;border-radius:19px;background:#f2efff;letter-spacing:-.04em}
    .activity-summary-box{border:1px solid #e0e9dd;background:#f4f8f2}.activity-summary-box:nth-of-type(2){background:#f3f6ff;border-color:#e0e5f5}.activity-summary-box:nth-of-type(3){background:#fff8df;border-color:#f0e1ad}.activity-subject-group,.activity-summary-card{border:1px solid #e4ece2;box-shadow:0 3px 10px #315d3b0b}.score-ledger-delta.is-plus{padding:4px 7px;border-radius:999px;background:#e7f6eb}.score-ledger-delta.is-minus{padding:4px 7px;border-radius:999px;background:#fff0ef}
    .sv-quick-button{border:1px solid #dce7da;border-radius:12px;padding:8px 10px;background:#fff;color:#315d3b;font-weight:900;cursor:pointer;white-space:nowrap}.sv-quick-button.ranking{background:#fff5d8;color:#7b5c0e}.sv-hub-panel{position:absolute;inset:68px 0 0;z-index:145;display:grid;place-items:center;padding:20px;background:#17392385;backdrop-filter:blur(5px)}.sv-hub-panel[hidden]{display:none}.sv-hub-card{width:min(620px,92vw);max-height:min(680px,78vh);overflow:auto;padding:25px;border:1px solid #ffffffcc;border-radius:27px;background:#fffdf7;box-shadow:0 25px 75px #10271955}.sv-hub-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;padding-bottom:14px;border-bottom:1px solid #e7ece3}.sv-hub-head h2{margin:0;color:#315d3b}.sv-hub-head p{margin:5px 0 0;color:#728077;font-weight:700}.sv-hub-close{border:0;border-radius:12px;padding:9px 12px;background:#edf3e9;color:#315d3b;font-weight:900;cursor:pointer}.sv-ranking-list{display:grid;gap:9px;margin-top:17px}.sv-rank-row{display:grid;grid-template-columns:42px 72px 1fr;align-items:center;gap:10px;padding:12px 14px;border-radius:15px;background:#f4f7f1}.sv-rank-row.me{background:#fff3c8;box-shadow:inset 0 0 0 2px #f0ce62}.sv-rank-number{font-size:20px;font-weight:1000;text-align:center}.sv-rank-avatar{position:relative;width:62px;height:62px;display:grid;place-items:center;border-radius:50%;background:#fff;box-shadow:0 3px 10px #315d3b18}.sv-rank-avatar>span{position:absolute;display:grid;place-items:center;line-height:1}.sv-rank-base{font-size:39px}.sv-rank-hat{top:-7px;z-index:3;font-size:23px}.sv-rank-glasses{top:18px;z-index:4;font-size:20px}.sv-rank-bag{right:-7px;top:29px;z-index:2;font-size:20px}.sv-rank-pet{right:-10px;bottom:-6px;z-index:5;font-size:19px}.sv-rank-avatar .image-asset img{width:28px;height:28px;object-fit:contain}.sv-rank-avatar .sv-rank-base.image-asset img{width:45px;height:45px}.sv-rank-name{display:grid;gap:3px;color:#315d3b}.sv-rank-name small{color:#859087}.sv-rank-level{width:max-content;padding:3px 8px;border-radius:999px;background:#e7f4df;color:#315d3b;font-size:12px}.sv-rank-title{display:inline-block;width:max-content;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:2px 7px;border-radius:999px;background:#eee9ff;color:#66569b;font-size:10px;font-weight:1000}
    @media(max-width:760px),(pointer:coarse){.hud{min-height:60px}.sv-quick-button{padding:7px 8px;font-size:11px}.sv-hub-panel{inset:60px 0 94px;padding:10px}.sv-hub-card{max-height:100%;padding:18px}.quiz-panel,.record-panel{width:min(680px,94vw)}}
  `;
  document.head.appendChild(style);
  const makeButton=(className,text)=>{const b=document.createElement('button');b.type='button';b.className=`sv-quick-button ${className}`;b.textContent=text;return b};
  const rankingButton=makeButton('ranking','🏆 랭킹');
  const customize=document.querySelector('#customize-button');hud.insertBefore(rankingButton,customize);
  const ranking=document.createElement('section');ranking.id='student-ranking-panel';ranking.className='sv-hub-panel';ranking.hidden=true;ranking.innerHTML='<div class="sv-hub-card" role="dialog" aria-modal="true" aria-labelledby="student-ranking-panel-title"><header class="sv-hub-head"><div><h2 id="student-ranking-panel-title">🏆 우리 반 레벨 랭킹</h2><p>레벨과 칭호, 친구들의 꾸민 캐릭터를 함께 확인해 보세요.</p></div><button class="sv-hub-close" type="button">닫기 ✕</button></header><div id="student-ranking-list" class="sv-ranking-list"><p class="activity-summary-empty">랭킹을 불러오는 중이에요.</p></div></div>';game.appendChild(ranking);
  ranking.querySelector('.sv-hub-close').onclick=()=>ranking.hidden=true;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let rankingRequestId=0;
  async function refreshRanking(){if(ranking.hidden)return;const requestId=++rankingRequestId,list=ranking.querySelector('#student-ranking-list'),me=document.querySelector('#profile-name')?.textContent?.trim();list.innerHTML='<p class="activity-summary-empty">랭킹을 불러오는 중이에요.</p>';try{const players=await window.StudyVillageData.listPlayers();if(requestId!==rankingRequestId||ranking.hidden)return;players.sort((a,b)=>(Number(b.level)||1)-(Number(a.level)||1)||(Number(b.xp)||0)-(Number(a.xp)||0)||String(a.name).localeCompare(String(b.name),'ko'));list.innerHTML='';if(!players.length){list.innerHTML='<p class="activity-summary-empty">아직 랭킹 기록이 없어요.</p>';return}players.slice(0,30).forEach((p,i)=>{const row=document.createElement('article'),currentTitle=String(p.title||'새싹 주민'),equipment=p.equipment&&typeof p.equipment==='object'?p.equipment:{};row.className=`sv-rank-row${p.name===me?' me':''}`;row.innerHTML=`<span class="sv-rank-number">${i<3?['🥇','🥈','🥉'][i]:i+1}</span><span class="sv-rank-avatar"><span class="sv-rank-hat"></span><span class="sv-rank-glasses"></span><span class="sv-rank-base"></span><span class="sv-rank-bag"></span><span class="sv-rank-pet"></span></span><span class="sv-rank-name"><b class="sv-rank-level">Lv.${Number(p.level)||1}</b><span class="sv-rank-title" title="${esc(currentTitle)}">🏷️ ${esc(currentTitle)}</span><strong>${esc(p.name)}${p.name===me?' · 나':''}</strong></span>`;list.appendChild(row);const renderer=window.StudyVillageAvatar;renderer?.paintBase(row.querySelector('.sv-rank-base'),p.baseCharacter||'student-default');renderer?.paintItem(row.querySelector('.sv-rank-hat'),equipment.hat);renderer?.paintItem(row.querySelector('.sv-rank-glasses'),equipment.glasses);renderer?.paintItem(row.querySelector('.sv-rank-bag'),equipment.bag);renderer?.paintItem(row.querySelector('.sv-rank-pet'),equipment.pet)})}catch{if(requestId===rankingRequestId&&!ranking.hidden)list.innerHTML='<p class="activity-summary-empty">랭킹을 불러오지 못했어요. 연결을 확인해 주세요.</p>'}}
  function openRanking(){ranking.hidden=false;refreshRanking()}
  rankingButton.onclick=openRanking;
  window.addEventListener('studyvillage:ranking-refresh',refreshRanking);window.addEventListener('studyvillage:activity-record-refresh',refreshRanking);
  window.addEventListener('keydown',event=>{if(event.key!=='Escape'||ranking.hidden)return;event.preventDefault();event.stopImmediatePropagation();ranking.hidden=true},true);
})();
