/* v1.16 atomic item shop + teacher delivery fulfillment.
   Digital purchases commit star deduction + permanent wardrobe ownership together.
   Physical purchases commit star deduction + teacher delivery request together.
   Teacher cancellation refunds stars exactly once.
   Admin availability is authoritative for every supported avatar slot. */
import Database from 'better-sqlite3';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseOwnedItems,serializeOwnedItems,validateOwnedItemsStrict } from './item-ownership.js';
import { avatarShopPackV3 } from './avatar-shop-pack-v3.js';

const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const PRICE_KEY='shop:prices:v1',ENABLED_KEY='shop:enabled:v1',AVAILABILITY_KEY='shop:availability:v1',LEVEL_REQUIREMENTS_KEY='shop:level-requirements:v1',LIMITED_KEY='shop:limited:v1',SALE_STARTS_KEY='shop:sale-starts:v1',SALE_ENDS_KEY='shop:sale-ends:v1',AVATAR_RESET_KEY='avatar:whole-character-reset:v1',REMOVED_STYLE_RESET_KEY='avatar:removed-face-hat-glasses:v2',MAX_STARS=1000000;
const DEFAULT_PRICES=Object.freeze({'bottom-jeans':22,'bottom-shorts':18,'bottom-skirt':24,'cap-blue':10,'crown-gold':50,'glasses-round':15,'backpack':30,'pet-chick':25,'pet-cat':50,'leaf-cap':18,'scholar-cap':35,'explorer-goggles':22,'star-monocle':40,'field-satchel':28,'book-pack':38,'pet-owl':45,'pet-fox':60,'hair-short':12,'hair-bob':12,'hair-ponytail':16,'hair-blue':28,'hat-wizard':42,'hat-pirate':38,'hat-flower':20,'glasses-sun':24,'glasses-heart':28,'outfit-hoodie':25,'outfit-uniform':32,'outfit-wizard':55,'outfit-armor':65,'shoes-sneakers':18,'shoes-boots':26,'shoes-wing':70,'bag-art':24,'bag-rocket':68,'hand-sword':45,'hand-wand':48,'hand-book':22,'hand-magnifier':24,'pet-dog':42,'pet-rabbit':38,'pet-dragon':75,'pet-slime':32,'hair-curly':16,'hair-sidepart':14,'hair-twintail':18,'hair-green':20,'hat-cap-red':12,'hat-beanie-green':14,'glasses-square':13,'glasses-blue':14,'outfit-tee-red':18,'outfit-tee-blue':18,'outfit-stripe':20,'outfit-sweater-green':22,'bottom-pants-black':20,'bottom-shorts-sport':18,'bottom-skirt-navy':22,'shoes-sneakers-red':18,'shoes-sneakers-black':18,'shoes-slipon-yellow':16,'bag-mini':20,'hand-pencil':12,'hand-notebook':16,'pet-hamster':30,'face-oval':10,'face-square':10,'face-warm':12,'expression-wink':8,'expression-happy':8,'expression-focus':8,'expression-surprise':8,'hair-buzz':12,'hair-long':18,'hair-silver':22,'hat-bucket-yellow':14,'hat-ribbon':12,'outfit-tee-white':18,'outfit-jacket-black':24,'bottom-cargo-khaki':22,'shoes-hightop-blue':20,'bag-crossbody':22,'hand-ball':16,'pet-panda':36,'pet-cloud':40,'aurora-effect':150,'candy':5,'stationery':15,...Object.fromEntries(Object.entries(avatarShopPackV3).map(([id,item])=>[id,item.price]))});
const DEFAULT_LEVEL_REQUIREMENTS=Object.freeze(Object.fromEntries(Object.keys(DEFAULT_PRICES).map(id=>[id,id==='aurora-effect'?50:1])));
const ITEM_NAMES=Object.freeze({'bottom-jeans':'튼튼한 청바지','bottom-shorts':'활동 반바지','bottom-skirt':'단정한 치마','cap-blue':'파란 모자','crown-gold':'황금 왕관','glasses-round':'동그란 안경','backpack':'모험 가방','pet-chick':'병아리 친구','pet-cat':'고양이 친구','leaf-cap':'새싹 탐험모','scholar-cap':'별빛 학사모','explorer-goggles':'숲빛 고글','star-monocle':'별 관측경','field-satchel':'탐험 도구 가방','book-pack':'책마루 가방','pet-owl':'부엉이 친구','pet-fox':'여우 친구','hair-short':'씩씩한 짧은 머리','hair-bob':'단정한 단발머리','hair-ponytail':'활동적인 포니테일','hair-blue':'별빛 파란 머리','hat-wizard':'마법사 모자','hat-pirate':'해적 모자','hat-flower':'꽃 장식 모자','glasses-sun':'멋쟁이 선글라스','glasses-heart':'하트 안경','outfit-hoodie':'편안한 후드','outfit-uniform':'학습마을 교복','outfit-wizard':'별빛 마법사 옷','outfit-armor':'마을 수호자 갑옷','shoes-sneakers':'달리기 운동화','shoes-boots':'탐험 장화','shoes-wing':'바람 날개 신발','bag-art':'미술 도구 가방','bag-rocket':'로켓 가방','hand-sword':'용사의 검','hand-wand':'별빛 지팡이','hand-book':'지혜의 책','hand-magnifier':'탐정 돋보기','pet-dog':'강아지 친구','pet-rabbit':'토끼 친구','pet-dragon':'꼬마 용 친구','pet-slime':'말랑 슬라임 친구','hair-curly':'몽글 곱슬머리','hair-sidepart':'깔끔한 옆가르마','hair-twintail':'쌍갈래 머리','hair-green':'숲빛 머리','hat-cap-red':'빨간 별 모자','hat-beanie-green':'초록 비니','glasses-square':'네모 안경','glasses-blue':'하늘빛 안경','outfit-tee-red':'빨간 티셔츠','outfit-tee-blue':'파란 티셔츠','outfit-stripe':'줄무늬 티셔츠','outfit-sweater-green':'초록 스웨터','bottom-pants-black':'검정 바지','bottom-shorts-sport':'운동 반바지','bottom-skirt-navy':'남색 치마','shoes-sneakers-red':'빨간 운동화','shoes-sneakers-black':'검정 운동화','shoes-slipon-yellow':'노란 슬립온','bag-mini':'작은 가죽 가방','hand-pencil':'연필','hand-notebook':'공책','pet-hamster':'햄스터 친구','face-oval':'갸름한 얼굴','face-square':'각진 얼굴','face-warm':'따뜻한 피부 얼굴','expression-wink':'윙크 표정','expression-happy':'활짝 웃는 표정','expression-focus':'집중 표정','expression-surprise':'깜짝 표정','hair-buzz':'짧은 스포츠 머리','hair-long':'긴 생머리','hair-silver':'은빛 머리','hat-bucket-yellow':'노란 버킷햇','hat-ribbon':'분홍 리본','outfit-tee-white':'하얀 티셔츠','outfit-jacket-black':'검정 재킷','bottom-cargo-khaki':'카키 카고바지','shoes-hightop-blue':'파란 하이탑','bag-crossbody':'크로스백','hand-ball':'주황 공','pet-panda':'판다 친구','pet-cloud':'구름 친구','aurora-effect':'오로라 성장 효과','candy':'사탕','stationery':'학용품',...Object.fromEntries(Object.entries(avatarShopPackV3).map(([id,item])=>[id,item.name]))});
const ITEM_SLOTS=Object.freeze({'bottom-jeans':'bottom','bottom-shorts':'bottom','bottom-skirt':'bottom','cap-blue':'hat','crown-gold':'hat','glasses-round':'glasses','backpack':'bag','pet-chick':'pet','pet-cat':'pet','leaf-cap':'hat','scholar-cap':'hat','explorer-goggles':'glasses','star-monocle':'glasses','field-satchel':'bag','book-pack':'bag','pet-owl':'pet','pet-fox':'pet','hair-short':'hair','hair-bob':'hair','hair-ponytail':'hair','hair-blue':'hair','hat-wizard':'hat','hat-pirate':'hat','hat-flower':'hat','glasses-sun':'glasses','glasses-heart':'glasses','outfit-hoodie':'outfit','outfit-uniform':'outfit','outfit-wizard':'outfit','outfit-armor':'outfit','shoes-sneakers':'shoes','shoes-boots':'shoes','shoes-wing':'shoes','bag-art':'bag','bag-rocket':'bag','hand-sword':'hand','hand-wand':'hand','hand-book':'hand','hand-magnifier':'hand','pet-dog':'pet','pet-rabbit':'pet','pet-dragon':'pet','pet-slime':'pet','hair-curly':'hair','hair-sidepart':'hair','hair-twintail':'hair','hair-green':'hair','hat-cap-red':'hat','hat-beanie-green':'hat','glasses-square':'glasses','glasses-blue':'glasses','outfit-tee-red':'outfit','outfit-tee-blue':'outfit','outfit-stripe':'outfit','outfit-sweater-green':'outfit','bottom-pants-black':'bottom','bottom-shorts-sport':'bottom','bottom-skirt-navy':'bottom','shoes-sneakers-red':'shoes','shoes-sneakers-black':'shoes','shoes-slipon-yellow':'shoes','bag-mini':'bag','hand-pencil':'hand','hand-notebook':'hand','pet-hamster':'pet','face-oval':'face','face-square':'face','face-warm':'face','expression-wink':'expression','expression-happy':'expression','expression-focus':'expression','expression-surprise':'expression','hair-buzz':'hair','hair-long':'hair','hair-silver':'hair','hat-bucket-yellow':'hat','hat-ribbon':'hat','outfit-tee-white':'outfit','outfit-jacket-black':'outfit','bottom-cargo-khaki':'bottom','shoes-hightop-blue':'shoes','bag-crossbody':'bag','hand-ball':'hand','pet-panda':'pet','pet-cloud':'pet','aurora-effect':'effect','candy':'physical','stationery':'physical',...Object.fromEntries(Object.entries(avatarShopPackV3).map(([id,item])=>[id,item.slot]))});
const PHYSICAL_ITEM_IDS=new Set(['candy','stationery']);
const REMOVED_STYLE_SLOTS=new Set(['face','expression','hat','glasses']);
const ACTIVE_ITEM_IDS=Object.freeze(Object.keys(DEFAULT_PRICES).filter(id=>!REMOVED_STYLE_SLOTS.has(ITEM_SLOTS[id])));
const FEATURED_ITEM_IDS=new Set(['crown-gold','star-monocle','pet-fox']);
const SLOT_NAMES=new Set(['hair','outfit','bottom','shoes','bag','hand','pet','effect']);
const BUILTIN_STYLE_SLOTS=Object.freeze({'face-round':'face','face-soft':'face','face-brave':'face','expression-smile':'expression','expression-calm':'expression','expression-sparkle':'expression'});
const RANKING_SLOTS=['hair','outfit','bottom','shoes','bag','hand','pet','effect'];
const clean=(v,n=160)=>String(v??'').trim().slice(0,n),mirrorKey=name=>`compat:stars:${encodeURIComponent(clean(name,12))}`;
const compatibilityKeysFor=name=>['compat:stars:','compat:base-character:','compat:owned-items:'].map(prefix=>`${prefix}${encodeURIComponent(clean(name,12))}`);
const validStarBalance=value=>Number.isSafeInteger(value)&&value>=0&&value<=MAX_STARS;
const xpForLevel=level=>{const n=Math.max(0,(Number(level)||1)-1);return 200*n+25*n*(n-1)};
const levelFromXp=xp=>{const value=Math.max(0,Number(xp)||0);let level=1;while(value>=xpForLevel(level+1))level++;return level};
function openDb(){const dataDir=process.env.STUDYVILLAGE_DATA_DIR||__dirname,db=new Database(path.join(dataDir,'studyvillage.db'));db.pragma('busy_timeout = 3000');return db}
function getSetting(db,key){return db.prepare('SELECT value FROM settings WHERE key=?').get(key)?.value||null}
function setSetting(db,key,value){db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,value)}
function ensureSchema(db){
  const cols=db.prepare('PRAGMA table_info(players)').all().map(r=>r.name);
  if(!cols.includes('stars'))db.exec('ALTER TABLE players ADD COLUMN stars INTEGER NOT NULL DEFAULT 0');
  if(!cols.includes('owned_items_json'))db.exec("ALTER TABLE players ADD COLUMN owned_items_json TEXT NOT NULL DEFAULT '[]'");
  if(!cols.includes('level'))db.exec('ALTER TABLE players ADD COLUMN level INTEGER NOT NULL DEFAULT 1');
  if(cols.includes('xp')){const rows=db.prepare('SELECT name,xp,level FROM players').all(),update=db.prepare('UPDATE players SET level=? WHERE name=?');for(const row of rows){const level=levelFromXp(row.xp);if(Number(row.level)!==level)update.run(level,row.name)}}
  db.exec(`
CREATE TABLE IF NOT EXISTS star_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,player_name TEXT NOT NULL,before_value INTEGER NOT NULL,after_value INTEGER NOT NULL,delta INTEGER NOT NULL,kind TEXT NOT NULL,reference_id TEXT,detail TEXT,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_star_ledger_player_id ON star_ledger(player_name,id DESC);
CREATE TABLE IF NOT EXISTS shop_delivery_requests(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_name TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_name TEXT NOT NULL,
  stars_spent INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  requested_at TEXT NOT NULL,
  resolved_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_shop_delivery_status_id ON shop_delivery_requests(status,id DESC);
CREATE INDEX IF NOT EXISTS idx_shop_delivery_player_id ON shop_delivery_requests(player_name,id DESC);
`);
  if(getSetting(db,PRICE_KEY)===null)setSetting(db,PRICE_KEY,JSON.stringify(DEFAULT_PRICES));
  if(getSetting(db,ENABLED_KEY)===null)setSetting(db,ENABLED_KEY,JSON.stringify(Object.fromEntries(ACTIVE_ITEM_IDS.map(id=>[id,true]))));
  if(getSetting(db,AVAILABILITY_KEY)===null)setSetting(db,AVAILABILITY_KEY,JSON.stringify(Object.fromEntries(ACTIVE_ITEM_IDS.map(id=>[id,{available:true}]))));
  if(getSetting(db,LEVEL_REQUIREMENTS_KEY)===null)setSetting(db,LEVEL_REQUIREMENTS_KEY,JSON.stringify(DEFAULT_LEVEL_REQUIREMENTS));
  if(getSetting(db,LIMITED_KEY)===null)setSetting(db,LIMITED_KEY,JSON.stringify({}));
  if(getSetting(db,SALE_STARTS_KEY)===null)setSetting(db,SALE_STARTS_KEY,JSON.stringify({}));
  if(getSetting(db,SALE_ENDS_KEY)===null)setSetting(db,SALE_ENDS_KEY,JSON.stringify({}));
}
function safeJson(raw,fallback){try{const parsed=JSON.parse(raw);return parsed&&typeof parsed==='object'?parsed:fallback}catch{return fallback}}
function readPrices(db){return {...DEFAULT_PRICES,...safeJson(getSetting(db,PRICE_KEY),{})}}
function readEnabled(db){return {...Object.fromEntries(ACTIVE_ITEM_IDS.map(id=>[id,true])),...safeJson(getSetting(db,ENABLED_KEY),{})}}
function readAvailability(db){return {...Object.fromEntries(ACTIVE_ITEM_IDS.map(id=>[id,{available:true}])),...safeJson(getSetting(db,AVAILABILITY_KEY),{})}}
function readLevelRequirements(db){return {...DEFAULT_LEVEL_REQUIREMENTS,...safeJson(getSetting(db,LEVEL_REQUIREMENTS_KEY),{})}}
function readLimited(db){return safeJson(getSetting(db,LIMITED_KEY),{})}
function readSaleStarts(db){return safeJson(getSetting(db,SALE_STARTS_KEY),{})}
function readSaleEnds(db){return safeJson(getSetting(db,SALE_ENDS_KEY),{})}
function availabilityFor(availability,id){const value=availability[id];return value&&typeof value==='object'?value:{available:value!==false}}
function saleActive(id,enabled,availability,saleStarts,saleEnds,now=Date.now()){if(enabled[id]===false)return false;const a=availabilityFor(availability,id);if(a.available===false)return false;const start=Date.parse(saleStarts[id]||a.saleStarts||'');if(Number.isFinite(start)&&now<start)return false;const end=Date.parse(saleEnds[id]||a.saleEnds||'');if(Number.isFinite(end)&&now>end)return false;return true}
function itemInfo(id,prices,levelRequirements,limited){return{id,name:ITEM_NAMES[id]||id,price:Number(prices[id]),slot:ITEM_SLOTS[id]||null,levelRequired:Math.max(1,Number(levelRequirements[id])||1),limited:Boolean(limited[id]),featured:FEATURED_ITEM_IDS.has(id)}}
function writeStarLedger(db,name,before,after,delta,kind,referenceId,detail){if(!validStarBalance(before)||!validStarBalance(after)||!Number.isSafeInteger(delta)||after-before!==delta)throw new Error('invalid-star-ledger-entry');db.prepare('INSERT INTO star_ledger(player_name,before_value,after_value,delta,kind,reference_id,detail,created_at) VALUES(?,?,?,?,?,?,?,?)').run(name,before,after,delta,kind,referenceId||null,detail||null,new Date().toISOString())}
function resetLegacyAvatarSelections(db){
  if(getSetting(db,AVATAR_RESET_KEY)!=='done'){
    const cols=db.prepare('PRAGMA table_info(players)').all().map(r=>r.name);
    if(cols.includes('base_character'))db.prepare("UPDATE players SET base_character='student-boy' WHERE base_character IS NULL OR base_character='' OR base_character NOT IN ('student-boy','student-girl')").run();
    setSetting(db,AVATAR_RESET_KEY,'done');
  }
  if(getSetting(db,REMOVED_STYLE_RESET_KEY)!=='done'){
    const rows=db.prepare('SELECT name,equipment_json FROM players').all(),update=db.prepare('UPDATE players SET equipment_json=? WHERE name=?');
    const tx=db.transaction(()=>{for(const row of rows){let equipment={};try{equipment=JSON.parse(row.equipment_json||'{}')||{}}catch{}for(const slot of REMOVED_STYLE_SLOTS)delete equipment[slot];update.run(JSON.stringify(equipment),row.name)}});tx();setSetting(db,REMOVED_STYLE_RESET_KEY,'done');
  }
}
function normalizeOwned(raw){return parseOwnedItems(raw).filter(id=>ACTIVE_ITEM_IDS.includes(id))}
function validateOwnedItemIds(ids){const parsed=validateOwnedItemsStrict(ids);return parsed.ok&&parsed.items.every(id=>ACTIVE_ITEM_IDS.includes(id))?parsed:{ok:false,code:'invalid-owned-items'}}
function installItemShop(app,{requireSession,requireAdmin}){
  const db=openDb();ensureSchema(db);resetLegacyAvatarSelections(db);
  app.get('/api/shop/items',requireSession,(req,res)=>{const prices=readPrices(db),enabled=readEnabled(db),availability=readAvailability(db),levelRequirements=readLevelRequirements(db),limited=readLimited(db),saleStarts=readSaleStarts(db),saleEnds=readSaleEnds(db),player=db.prepare('SELECT name,stars,owned_items_json,level FROM players WHERE name=?').get(req.session.name);if(!player)return res.status(404).json({ok:false});const owned=normalizeOwned(player.owned_items_json);const items=ACTIVE_ITEM_IDS.map(id=>({...itemInfo(id,prices,levelRequirements,limited),available:saleActive(id,enabled,availability,saleStarts,saleEnds),owned:owned.includes(id)}));res.json({ok:true,stars:player.stars,level:player.level,items})});
  app.post('/api/shop/buy',requireSession,(req,res)=>{const itemId=String(req.body?.itemId||''),prices=readPrices(db),enabled=readEnabled(db),availability=readAvailability(db),levelRequirements=readLevelRequirements(db),limited=readLimited(db),saleStarts=readSaleStarts(db),saleEnds=readSaleEnds(db),price=Number(prices[itemId]),levelRequired=Math.max(1,Number(levelRequirements[itemId])||1),slot=ITEM_SLOTS[itemId];if(!ACTIVE_ITEM_IDS.includes(itemId)||!Number.isInteger(price)||price<0||!slot)return res.status(400).json({ok:false,code:'invalid-item'});if(!saleActive(itemId,enabled,availability,saleStarts,saleEnds))return res.status(409).json({ok:false,code:'not-for-sale'});const name=req.session.name;try{const result=db.transaction(()=>{const player=db.prepare('SELECT name,stars,owned_items_json,level FROM players WHERE name=?').get(name);if(!player)throw Object.assign(new Error('player-not-found'),{status:404});if(!validStarBalance(player.stars))throw Object.assign(new Error('invalid-star-balance'),{status:409});if((Number(player.level)||1)<levelRequired)throw Object.assign(new Error('level-locked'),{status:409,levelRequired});if(PHYSICAL_ITEM_IDS.has(itemId)){if(player.stars<price)throw Object.assign(new Error('not-enough-stars'),{status:409});const after=player.stars-price;db.prepare('UPDATE players SET stars=? WHERE name=?').run(after,name);const info=db.prepare("INSERT INTO shop_delivery_requests(player_name,item_id,item_name,stars_spent,status,requested_at) VALUES(?,?,?,?, 'pending',?)").run(name,itemId,ITEM_NAMES[itemId]||itemId,price,new Date().toISOString());writeStarLedger(db,name,player.stars,after,-price,'shop-physical-purchase',`delivery:${info.lastInsertRowid}`,itemId);return{stars:after,deliveryRequestId:Number(info.lastInsertRowid),physical:true}}const owned=parseOwnedItems(player.owned_items_json);if(owned.includes(itemId))return{stars:player.stars,ownedItems:owned,alreadyOwned:true};if(player.stars<price)throw Object.assign(new Error('not-enough-stars'),{status:409});const next=[...owned,itemId],after=player.stars-price;if(!validStarBalance(after))throw Object.assign(new Error('invalid-star-balance'),{status:409});db.prepare('UPDATE players SET stars=?,owned_items_json=? WHERE name=?').run(after,serializeOwnedItems(next),name);writeStarLedger(db,name,player.stars,after,-price,'shop-purchase',`item:${itemId}`,itemId);return{stars:after,ownedItems:next,physical:false}})();res.json({ok:true,...result})}catch(error){res.status(error.status||500).json({ok:false,code:error.message,levelRequired:error.levelRequired})}});
  app.get('/api/shop/equipment',requireSession,(req,res)=>{const row=db.prepare('SELECT equipment_json,owned_items_json FROM players WHERE name=?').get(req.session.name);if(!row)return res.status(404).json({ok:false});let saved={};try{saved=JSON.parse(row.equipment_json||'{}')||{}}catch{}const owned=normalizeOwned(row.owned_items_json),equipment={};for(const slot of RANKING_SLOTS){const id=saved[slot];if(id&&owned.includes(id)&&ITEM_SLOTS[id]===slot)equipment[slot]=id}res.json({ok:true,equipment,ownedItems:owned})});
  app.put('/api/shop/equipment',requireSession,(req,res)=>{const row=db.prepare('SELECT equipment_json,owned_items_json FROM players WHERE name=?').get(req.session.name);if(!row)return res.status(404).json({ok:false});const incoming=req.body?.equipment;if(!incoming||typeof incoming!=='object'||Array.isArray(incoming))return res.status(400).json({ok:false,code:'invalid-equipment'});let current={};try{current=JSON.parse(row.equipment_json||'{}')||{}}catch{}const owned=normalizeOwned(row.owned_items_json);for(const [slot,id] of Object.entries(incoming)){if(!SLOT_NAMES.has(slot))return res.status(400).json({ok:false,code:'invalid-slot'});if(id==null||id===''){delete current[slot];continue}if(typeof id!=='string'||!owned.includes(id)||ITEM_SLOTS[id]!==slot)return res.status(400).json({ok:false,code:'invalid-equipment'});current[slot]=id}db.prepare('UPDATE players SET equipment_json=? WHERE name=?').run(JSON.stringify(current),req.session.name);res.json({ok:true,equipment:current})});
  app.get('/api/admin/shop/items',requireAdmin,(req,res)=>{const prices=readPrices(db),enabled=readEnabled(db),availability=readAvailability(db),levelRequirements=readLevelRequirements(db),limited=readLimited(db),saleStarts=readSaleStarts(db),saleEnds=readSaleEnds(db);res.json({ok:true,items:ACTIVE_ITEM_IDS.map(id=>({...itemInfo(id,prices,levelRequirements,limited),enabled:enabled[id]!==false,availability:availabilityFor(availability,id),saleStarts:saleStarts[id]||null,saleEnds:saleEnds[id]||null}))})});
  app.put('/api/admin/shop/items/:id',requireAdmin,(req,res)=>{const id=String(req.params.id||'');if(!ACTIVE_ITEM_IDS.includes(id))return res.status(404).json({ok:false});const prices=readPrices(db),enabled=readEnabled(db),availability=readAvailability(db),levelRequirements=readLevelRequirements(db),limited=readLimited(db),saleStarts=readSaleStarts(db),saleEnds=readSaleEnds(db);if(req.body?.price!==undefined){const price=Number(req.body.price);if(!Number.isInteger(price)||price<0||price>MAX_STARS)return res.status(400).json({ok:false,code:'invalid-price'});prices[id]=price}if(req.body?.enabled!==undefined)enabled[id]=Boolean(req.body.enabled);if(req.body?.availability!==undefined)availability[id]=typeof req.body.availability==='object'?{...availabilityFor(availability,id),...req.body.availability}:{available:Boolean(req.body.availability)};if(req.body?.levelRequired!==undefined){const level=Number(req.body.levelRequired);if(!Number.isInteger(level)||level<1||level>999)return res.status(400).json({ok:false,code:'invalid-level'});levelRequirements[id]=level}if(req.body?.limited!==undefined)limited[id]=Boolean(req.body.limited);if(req.body?.saleStarts!==undefined)saleStarts[id]=clean(req.body.saleStarts,40)||null;if(req.body?.saleEnds!==undefined)saleEnds[id]=clean(req.body.saleEnds,40)||null;setSetting(db,PRICE_KEY,JSON.stringify(prices));setSetting(db,ENABLED_KEY,JSON.stringify(enabled));setSetting(db,AVAILABILITY_KEY,JSON.stringify(availability));setSetting(db,LEVEL_REQUIREMENTS_KEY,JSON.stringify(levelRequirements));setSetting(db,LIMITED_KEY,JSON.stringify(limited));setSetting(db,SALE_STARTS_KEY,JSON.stringify(saleStarts));setSetting(db,SALE_ENDS_KEY,JSON.stringify(saleEnds));res.json({ok:true,item:{...itemInfo(id,prices,levelRequirements,limited),enabled:enabled[id]!==false,availability:availabilityFor(availability,id),saleStarts:saleStarts[id]||null,saleEnds:saleEnds[id]||null}})});
  app.get('/api/admin/shop/deliveries',requireAdmin,(req,res)=>{const rows=db.prepare("SELECT id,player_name AS playerName,item_id AS itemId,item_name AS itemName,stars_spent AS starsSpent,status,requested_at AS requestedAt,resolved_at AS resolvedAt FROM shop_delivery_requests ORDER BY id DESC LIMIT 500").all();res.json({ok:true,requests:rows})});
  app.post('/api/admin/shop/deliveries/:id/complete',requireAdmin,(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({ok:false});const result=db.prepare("UPDATE shop_delivery_requests SET status='completed',resolved_at=? WHERE id=? AND status='pending'").run(new Date().toISOString(),id);if(!result.changes)return res.status(409).json({ok:false,code:'already-resolved'});res.json({ok:true})});
  app.post('/api/admin/shop/deliveries/:id/cancel',requireAdmin,(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({ok:false});try{const result=db.transaction(()=>{const request=db.prepare('SELECT * FROM shop_delivery_requests WHERE id=?').get(id);if(!request)throw Object.assign(new Error('not-found'),{status:404});if(request.status!=='pending')throw Object.assign(new Error('already-resolved'),{status:409});const player=db.prepare('SELECT stars FROM players WHERE name=?').get(request.player_name);if(!player||!validStarBalance(player.stars))throw Object.assign(new Error('invalid-star-balance'),{status:409});const after=player.stars+request.stars_spent;if(!validStarBalance(after))throw Object.assign(new Error('invalid-star-balance'),{status:409});db.prepare('UPDATE players SET stars=? WHERE name=?').run(after,request.player_name);db.prepare("UPDATE shop_delivery_requests SET status='cancelled',resolved_at=? WHERE id=?").run(new Date().toISOString(),id);writeStarLedger(db,request.player_name,player.stars,after,request.stars_spent,'shop-physical-refund',`delivery:${id}`,request.item_id);return{stars:after}})();res.json({ok:true,...result})}catch(error){res.status(error.status||500).json({ok:false,code:error.message})}});
  return{db,DEFAULT_PRICES,ITEM_NAMES,ITEM_SLOTS,ACTIVE_ITEM_IDS};
}

export{installItemShop};
