/* v1.12 atomic item shop foundation.
   Star deduction + permanent wardrobe ownership are committed together.
   Prices are stored in settings and can be changed by the teacher.
   Purchased items can be equipped through the shop route without changing legacy unlock rules. */
import Database from 'better-sqlite3';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { serializeOwnedItems,validateOwnedItemsStrict } from './item-ownership.js';

const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const PRICE_KEY='shop:prices:v1',ENABLED_KEY='shop:enabled:v1',AVAILABILITY_KEY='shop:availability:v1',LEVEL_REQUIREMENTS_KEY='shop:level-requirements:v1',LIMITED_KEY='shop:limited:v1',SALE_STARTS_KEY='shop:sale-starts:v1',SALE_ENDS_KEY='shop:sale-ends:v1',MAX_STARS=1000000;
const DEFAULT_PRICES=Object.freeze({'cap-blue':10,'crown-gold':50,'glasses-round':15,'backpack':30,'pet-chick':25,'pet-cat':50,'leaf-cap':18,'scholar-cap':35,'explorer-goggles':22,'star-monocle':40,'field-satchel':28,'book-pack':38,'pet-owl':45,'pet-fox':60});
const ITEM_NAMES=Object.freeze({'cap-blue':'파란 모자','crown-gold':'황금 왕관','glasses-round':'동그란 안경','backpack':'모험 가방','pet-chick':'병아리 친구','pet-cat':'고양이 친구','leaf-cap':'새싹 탐험모','scholar-cap':'별빛 학사모','explorer-goggles':'숲빛 고글','star-monocle':'별 관측경','field-satchel':'탐험 도구 가방','book-pack':'책마루 가방','pet-owl':'부엉이 친구','pet-fox':'여우 친구'});
const ITEM_SLOTS=Object.freeze({'cap-blue':'hat','crown-gold':'hat','glasses-round':'glasses','backpack':'bag','pet-chick':'pet','pet-cat':'pet','leaf-cap':'hat','scholar-cap':'hat','explorer-goggles':'glasses','star-monocle':'glasses','field-satchel':'bag','book-pack':'bag','pet-owl':'pet','pet-fox':'pet'});
const FEATURED_ITEM_IDS=new Set(['crown-gold','star-monocle','pet-fox']);
const SLOT_NAMES=new Set(['hat','glasses','bag','pet']);
const clean=(v,n=160)=>String(v??'').trim().slice(0,n),mirrorKey=name=>`compat:stars:${encodeURIComponent(clean(name,12))}`;
const compatibilityKeysFor=name=>['compat:stars:','compat:base-character:','compat:owned-items:'].map(prefix=>`${prefix}${encodeURIComponent(clean(name,12))}`);
const validStarBalance=value=>Number.isSafeInteger(value)&&value>=0&&value<=MAX_STARS;
function openDb(){const dataDir=process.env.STUDYVILLAGE_DATA_DIR||__dirname,db=new Database(path.join(dataDir,'studyvillage.db'));db.pragma('busy_timeout = 3000');return db}
function getSetting(db,key){return db.prepare('SELECT value FROM settings WHERE key=?').get(key)?.value||null}
function setSetting(db,key,value){db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,value)}
function ensureSchema(db){const cols=db.prepare('PRAGMA table_info(players)').all().map(r=>r.name);if(!cols.includes('stars'))db.exec('ALTER TABLE players ADD COLUMN stars INTEGER NOT NULL DEFAULT 0');if(!cols.includes('owned_items_json'))db.exec("ALTER TABLE players ADD COLUMN owned_items_json TEXT NOT NULL DEFAULT '[]'");db.exec(`CREATE TABLE IF NOT EXISTS star_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,player_name TEXT NOT NULL,before_value INTEGER NOT NULL,after_value INTEGER NOT NULL,delta INTEGER NOT NULL,kind TEXT NOT NULL,reference_id TEXT,detail TEXT,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_star_ledger_player_id ON star_ledger(player_name,id DESC);`);if(getSetting(db,PRICE_KEY)===null)setSetting(db,PRICE_KEY,JSON.stringify(DEFAULT_PRICES));if(getSetting(db,ENABLED_KEY)===null)setSetting(db,ENABLED_KEY,'false');if(getSetting(db,AVAILABILITY_KEY)===null)setSetting(db,AVAILABILITY_KEY,JSON.stringify(Object.fromEntries(Object.keys(DEFAULT_PRICES).map(id=>[id,true]))));if(getSetting(db,LEVEL_REQUIREMENTS_KEY)===null)setSetting(db,LEVEL_REQUIREMENTS_KEY,JSON.stringify(Object.fromEntries(Object.keys(DEFAULT_PRICES).map(id=>[id,1]))));if(getSetting(db,LIMITED_KEY)===null)setSetting(db,LIMITED_KEY,JSON.stringify(Object.fromEntries(Object.keys(DEFAULT_PRICES).map(id=>[id,false]))));if(getSetting(db,SALE_STARTS_KEY)===null)setSetting(db,SALE_STARTS_KEY,JSON.stringify(Object.fromEntries(Object.keys(DEFAULT_PRICES).map(id=>[id,null]))));if(getSetting(db,SALE_ENDS_KEY)===null)setSetting(db,SALE_ENDS_KEY,JSON.stringify(Object.fromEntries(Object.keys(DEFAULT_PRICES).map(id=>[id,null]))))}
function readPrices(db){try{const raw=JSON.parse(getSetting(db,PRICE_KEY)||'{}'),out={};for(const id of Object.keys(DEFAULT_PRICES)){const v=Number(raw[id]);out[id]=Number.isInteger(v)&&v>=0&&v<=100000?v:DEFAULT_PRICES[id]}return out}catch{return{...DEFAULT_PRICES}}}
function readAvailability(db){let raw={};try{const parsed=JSON.parse(getSetting(db,AVAILABILITY_KEY)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))raw=parsed}catch{}const out={};for(const id of Object.keys(DEFAULT_PRICES))out[id]=typeof raw[id]==='boolean'?raw[id]:true;return out}
function readLevelRequirements(db){let raw={};try{const parsed=JSON.parse(getSetting(db,LEVEL_REQUIREMENTS_KEY)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))raw=parsed}catch{}const out={};for(const id of Object.keys(DEFAULT_PRICES)){const level=Number(raw[id]);out[id]=Number.isInteger(level)&&level>=1&&level<=100?level:1}return out}
function readLimited(db){let raw={};try{const parsed=JSON.parse(getSetting(db,LIMITED_KEY)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))raw=parsed}catch{}const out={};for(const id of Object.keys(DEFAULT_PRICES))out[id]=typeof raw[id]==='boolean'?raw[id]:false;return out}
function normalizeSaleEnd(value){if(value===null||value==='')return null;if(typeof value!=='string')return undefined;const time=Date.parse(value);if(!Number.isFinite(time)||time<Date.UTC(2020,0,1)||time>Date.UTC(2100,0,1))return undefined;return new Date(time).toISOString()}
function readSaleStarts(db){let raw={};try{const parsed=JSON.parse(getSetting(db,SALE_STARTS_KEY)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))raw=parsed}catch{}const out={};for(const id of Object.keys(DEFAULT_PRICES)){const value=normalizeSaleEnd(raw[id]);out[id]=value===undefined?null:value}return out}
function readSaleEnds(db){let raw={};try{const parsed=JSON.parse(getSetting(db,SALE_ENDS_KEY)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))raw=parsed}catch{}const out={};for(const id of Object.keys(DEFAULT_PRICES)){const value=normalizeSaleEnd(raw[id]);out[id]=value===undefined?null:value}return out}
function validateEquipment(value){let raw;try{raw=JSON.parse(value||'{}')}catch{return{ok:false,code:'corrupt-equipment',equipment:null}};if(!raw||typeof raw!=='object'||Array.isArray(raw))return{ok:false,code:'corrupt-equipment',equipment:null};const out={hat:null,glasses:null,bag:null,pet:null};for(const key of Object.keys(raw))if(!SLOT_NAMES.has(key))return{ok:false,code:'corrupt-equipment',equipment:null};for(const slot of Object.keys(out)){const value=raw?.[slot];if(value===undefined||value===null||value===''){out[slot]=null;continue}if(typeof value!=='string'||ITEM_SLOTS[value]!==slot)return{ok:false,code:'corrupt-equipment',equipment:null};out[slot]=value}return{ok:true,equipment:out}}
function writeStarMirror(db,name){const player=db.prepare('SELECT stars FROM players WHERE name=?').get(name);if(!player||!validStarBalance(player.stars))return false;const entries=db.prepare('SELECT before_value AS beforeValue,after_value AS afterValue,delta,kind,reference_id AS referenceId,detail,created_at AS createdAt FROM star_ledger WHERE player_name=? ORDER BY id DESC LIMIT 500').all(name).reverse();setSetting(db,mirrorKey(name),JSON.stringify({balance:player.stars,entries}));return true}
export function cleanupDeletedPlayerCompatibility(playerName){const name=clean(playerName,12);if(!name)return false;let db;try{db=openDb();const keys=compatibilityKeysFor(name),tx=db.transaction(()=>{for(const key of keys)db.prepare('DELETE FROM settings WHERE key=?').run(key);try{db.prepare('DELETE FROM star_ledger WHERE player_name=?').run(name)}catch{}});tx();return true}finally{try{db?.close()}catch{}}}
export function shopState(){let db;try{db=openDb();ensureSchema(db);const prices=readPrices(db),availability=readAvailability(db),levelRequirements=readLevelRequirements(db),limited=readLimited(db),saleStarts=readSaleStarts(db),saleEnds=readSaleEnds(db),now=Date.now();return{enabled:getSetting(db,ENABLED_KEY)==='true',prices,availability,levelRequirements,limited,saleStarts,saleEnds,items:Object.keys(DEFAULT_PRICES).map(id=>({id,name:ITEM_NAMES[id],slot:ITEM_SLOTS[id],price:prices[id],available:availability[id],requiredLevel:levelRequirements[id],limited:limited[id],saleStartsAt:saleStarts[id],salePending:!!(limited[id]&&saleStarts[id]&&Date.parse(saleStarts[id])>now),saleEndsAt:saleEnds[id],saleEnded:!!(limited[id]&&saleEnds[id]&&Date.parse(saleEnds[id])<=now)}))}}finally{try{db?.close()}catch{}}}
export function playerShopState(playerName){let db;try{db=openDb();ensureSchema(db);const name=clean(playerName,12),player=db.prepare('SELECT level,stars,owned_items_json,equipment_json FROM players WHERE name=?').get(name);if(!player)return null;if(!validStarBalance(player.stars))return{ok:false,code:'corrupt-star-balance'};const owned=validateOwnedItemsStrict(player.owned_items_json);if(!owned.ok)return{ok:false,code:'corrupt-owned-items'};const equipped=validateEquipment(player.equipment_json);if(!equipped.ok)return{ok:false,code:'corrupt-equipment'};const base=shopState();return{ok:true,...base,balance:player.stars,currentLevel:Number(player.level)||1,ownedItems:owned.items,equipment:equipped.equipment}}finally{try{db?.close()}catch{}}}
export function configureShop({enabled,prices,availability,levelRequirements,limited,saleStarts,saleEnds}={}){let db;try{db=openDb();ensureSchema(db);const current=readPrices(db),next={...current},currentAvailability=readAvailability(db),nextAvailability={...currentAvailability},currentLevels=readLevelRequirements(db),nextLevels={...currentLevels},currentLimited=readLimited(db),nextLimited={...currentLimited},currentSaleStarts=readSaleStarts(db),nextSaleStarts={...currentSaleStarts},currentSaleEnds=readSaleEnds(db),nextSaleEnds={...currentSaleEnds};if(prices&&typeof prices==='object')for(const id of Object.keys(DEFAULT_PRICES)){if(!(id in prices))continue;const value=Number(prices[id]);if(!Number.isInteger(value)||value<0||value>100000)return{ok:false,code:'invalid-price',itemId:id};next[id]=value}if(availability&&typeof availability==='object'&&!Array.isArray(availability))for(const id of Object.keys(DEFAULT_PRICES)){if(!(id in availability))continue;if(typeof availability[id]!=='boolean')return{ok:false,code:'invalid-availability',itemId:id};nextAvailability[id]=availability[id]}if(levelRequirements&&typeof levelRequirements==='object'&&!Array.isArray(levelRequirements))for(const id of Object.keys(DEFAULT_PRICES)){if(!(id in levelRequirements))continue;const level=Number(levelRequirements[id]);if(!Number.isInteger(level)||level<1||level>100)return{ok:false,code:'invalid-required-level',itemId:id};nextLevels[id]=level}if(limited&&typeof limited==='object'&&!Array.isArray(limited))for(const id of Object.keys(DEFAULT_PRICES)){if(!(id in limited))continue;if(typeof limited[id]!=='boolean')return{ok:false,code:'invalid-limited',itemId:id};nextLimited[id]=limited[id]}if(saleStarts&&typeof saleStarts==='object'&&!Array.isArray(saleStarts))for(const id of Object.keys(DEFAULT_PRICES)){if(!(id in saleStarts))continue;const value=normalizeSaleEnd(saleStarts[id]);if(value===undefined)return{ok:false,code:'invalid-sale-start',itemId:id};nextSaleStarts[id]=value}if(saleEnds&&typeof saleEnds==='object'&&!Array.isArray(saleEnds))for(const id of Object.keys(DEFAULT_PRICES)){if(!(id in saleEnds))continue;const value=normalizeSaleEnd(saleEnds[id]);if(value===undefined)return{ok:false,code:'invalid-sale-end',itemId:id};nextSaleEnds[id]=value}for(const id of Object.keys(DEFAULT_PRICES))if(nextSaleStarts[id]&&nextSaleEnds[id]&&Date.parse(nextSaleStarts[id])>=Date.parse(nextSaleEnds[id]))return{ok:false,code:'invalid-sale-window',itemId:id};const tx=db.transaction(()=>{setSetting(db,PRICE_KEY,JSON.stringify(next));setSetting(db,AVAILABILITY_KEY,JSON.stringify(nextAvailability));setSetting(db,LEVEL_REQUIREMENTS_KEY,JSON.stringify(nextLevels));setSetting(db,LIMITED_KEY,JSON.stringify(nextLimited));setSetting(db,SALE_STARTS_KEY,JSON.stringify(nextSaleStarts));setSetting(db,SALE_ENDS_KEY,JSON.stringify(nextSaleEnds));if(typeof enabled==='boolean')setSetting(db,ENABLED_KEY,enabled?'true':'false')});tx();return{ok:true,...shopState()}}finally{try{db?.close()}catch{}}}
export function purchaseItem(playerName,itemId){const name=clean(playerName,12),id=clean(itemId,80);if(!name||!(id in DEFAULT_PRICES))return{ok:false,code:'invalid-item'};let db;try{db=openDb();ensureSchema(db);const tx=db.transaction(()=>{if(getSetting(db,ENABLED_KEY)!=='true')return{ok:false,code:'shop-disabled'};if(!readAvailability(db)[id])return{ok:false,code:'item-unavailable',itemId:id};const saleStart=readSaleStarts(db)[id],saleEnd=readSaleEnds(db)[id];if(readLimited(db)[id]&&saleStart&&Date.parse(saleStart)>Date.now())return{ok:false,code:'sale-pending',itemId:id,saleStartsAt:saleStart};if(readLimited(db)[id]&&saleEnd&&Date.parse(saleEnd)<=Date.now())return{ok:false,code:'sale-ended',itemId:id,saleEndsAt:saleEnd};const player=db.prepare('SELECT level,stars,owned_items_json FROM players WHERE name=?').get(name);if(!player)return{ok:false,code:'player-not-found'};const requiredLevel=readLevelRequirements(db)[id],currentLevel=Number(player.level)||1;if(currentLevel<requiredLevel)return{ok:false,code:'level-required',itemId:id,currentLevel,requiredLevel};if(!validStarBalance(player.stars))return{ok:false,code:'corrupt-star-balance'};const validatedOwned=validateOwnedItemsStrict(player.owned_items_json);if(!validatedOwned.ok)return{ok:false,code:'corrupt-owned-items'};const owned=validatedOwned.items;if(owned.includes(id))return{ok:false,code:'already-owned'};const price=readPrices(db)[id],before=player.stars;if(before<price)return{ok:false,code:'insufficient-stars',balance:before,price};const after=before-price,now=new Date().toISOString(),next=[...owned,id];const changed=db.prepare('UPDATE players SET stars=?,owned_items_json=?,updated_at=? WHERE name=? AND stars=?').run(after,serializeOwnedItems(next),now,name,before);if(changed.changes!==1)return{ok:false,code:'balance-changed'};db.prepare('INSERT INTO star_ledger(player_name,before_value,after_value,delta,kind,reference_id,detail,created_at) VALUES(?,?,?,?,?,?,?,?)').run(name,before,after,-price,'item-purchase',id,`${ITEM_NAMES[id]} 구매`,now);writeStarMirror(db,name);return{ok:true,itemId:id,itemName:ITEM_NAMES[id],slot:ITEM_SLOTS[id],price,balance:after,ownedItems:next,createdAt:now}});return tx()}finally{try{db?.close()}catch{}}}
export function saveOwnedEquipment(playerName,equipment={}){const name=clean(playerName,12);if(!name)return{ok:false,code:'invalid-player'};let db;try{db=openDb();ensureSchema(db);const player=db.prepare('SELECT owned_items_json,equipment_json FROM players WHERE name=?').get(name);if(!player)return{ok:false,code:'player-not-found'};const validatedOwned=validateOwnedItemsStrict(player.owned_items_json);if(!validatedOwned.ok)return{ok:false,code:'corrupt-owned-items'};const validatedEquipment=validateEquipment(player.equipment_json);if(!validatedEquipment.ok)return{ok:false,code:'corrupt-equipment'};const owned=new Set(validatedOwned.items),current=validatedEquipment.equipment,next={...current};for(const slot of SLOT_NAMES){if(!(slot in equipment))continue;const raw=equipment?.[slot];if(raw===null||raw===''){next[slot]=null;continue}const id=clean(raw,80);if(ITEM_SLOTS[id]!==slot)return{ok:false,code:'invalid-slot',slot};if(!owned.has(id))return{ok:false,code:'item-not-owned',itemId:id};next[slot]=id}const now=new Date().toISOString(),changed=db.prepare('UPDATE players SET equipment_json=?,updated_at=? WHERE name=?').run(JSON.stringify(next),now,name);return changed.changes?{ok:true,equipment:next,updatedAt:now}:{ok:false,code:'player-not-found'}}finally{try{db?.close()}catch{}}}
export function grantItemByTeacher(playerName,itemId,reason){const name=clean(playerName,12),id=clean(itemId,80),why=clean(reason,200);if(!name||!(id in DEFAULT_PRICES))return{ok:false,code:'invalid-item'};if(why.length<3)return{ok:false,code:'invalid-reason'};let db;try{db=openDb();ensureSchema(db);const tx=db.transaction(()=>{const player=db.prepare('SELECT stars,owned_items_json FROM players WHERE name=?').get(name);if(!player)return{ok:false,code:'player-not-found'};if(!validStarBalance(player.stars))return{ok:false,code:'corrupt-star-balance'};const validated=validateOwnedItemsStrict(player.owned_items_json);if(!validated.ok)return{ok:false,code:'corrupt-owned-items'};if(validated.items.includes(id))return{ok:true,alreadyOwned:true,itemId:id,itemName:ITEM_NAMES[id],ownedItems:validated.items,balance:player.stars};const owned=[...validated.items,id],now=new Date().toISOString();db.prepare('UPDATE players SET owned_items_json=?,updated_at=? WHERE name=?').run(serializeOwnedItems(owned),now,name);db.prepare('INSERT INTO star_ledger(player_name,before_value,after_value,delta,kind,reference_id,detail,created_at) VALUES(?,?,?,?,?,?,?,?)').run(name,player.stars,player.stars,0,'teacher-item-grant',id,`교사 지급 · ${ITEM_NAMES[id]} · ${why}`,now);writeStarMirror(db,name);return{ok:true,alreadyOwned:false,itemId:id,itemName:ITEM_NAMES[id],ownedItems:owned,balance:player.stars,createdAt:now}});return tx()}finally{try{db?.close()}catch{}}}
export function installItemShopRoutes(app,{requireSession,requireAdmin,publishLiveEvent}={}){if(typeof requireSession==='function'){app.get('/api/shop',requireSession,(req,res)=>{try{const state=playerShopState(req.session.name);if(!state)return res.status(404).json({ok:false,code:'player-not-found'});if(state.ok===false)return res.status(409).json(state);res.json(state)}catch(err){res.status(500).json({ok:false,code:'shop-read-failed',message:clean(err?.message||err,160)})}});app.post('/api/shop/purchase',requireSession,(req,res)=>{try{const result=purchaseItem(req.session.name,req.body?.itemId);if(!result.ok)return res.status(result.code==='player-not-found'?404:409).json(result);if(FEATURED_ITEM_IDS.has(result.itemId)){try{publishLiveEvent?.('🎁',`${req.session.name} 학생이 특별 아이템 “${result.itemName}”을 획득했습니다!`,'featured-item')}catch{}}res.json(result)}catch(err){res.status(500).json({ok:false,code:'purchase-failed',message:clean(err?.message||err,160)})}});app.put('/api/shop/equipment',requireSession,(req,res)=>{try{const result=saveOwnedEquipment(req.session.name,req.body?.equipment||{});if(!result.ok)return res.status(result.code==='player-not-found'?404:409).json(result);res.json(result)}catch(err){res.status(500).json({ok:false,code:'shop-equipment-save-failed',message:clean(err?.message||err,160)})}})}if(typeof requireAdmin==='function'){app.get('/api/admin/shop',requireAdmin,(_req,res)=>{try{res.json({ok:true,...shopState()})}catch(err){res.status(500).json({ok:false,code:'shop-read-failed',message:clean(err?.message||err,160)})}});app.put('/api/admin/shop',requireAdmin,(req,res)=>{try{const result=configureShop({enabled:req.body?.enabled,prices:req.body?.prices,availability:req.body?.availability,levelRequirements:req.body?.levelRequirements,limited:req.body?.limited,saleStarts:req.body?.saleStarts,saleEnds:req.body?.saleEnds});if(!result.ok)return res.status(400).json(result);res.json(result)}catch(err){res.status(500).json({ok:false,code:'shop-update-failed',message:clean(err?.message||err,160)})}});app.post('/api/admin/player/:name/items',requireAdmin,(req,res)=>{try{const result=grantItemByTeacher(req.params?.name,req.body?.itemId,req.body?.reason);if(!result.ok)return res.status(result.code==='player-not-found'?404:400).json(result);res.json(result)}catch(err){res.status(500).json({ok:false,code:'teacher-item-grant-failed',message:clean(err?.message||err,160)})}});if(typeof app.delete==='function')app.delete('/api/admin/player/:name',requireAdmin,(req,res,next)=>{const name=clean(req.params?.name,12);if(typeof res.on==='function')res.on('finish',()=>{if(res.statusCode>=200&&res.statusCode<300)try{cleanupDeletedPlayerCompatibility(name)}catch{}});next()})}}
export const defaultShopPrices=DEFAULT_PRICES;
