/* v1.9.7 classroom network discovery.
   Discover classroom IPv4 addresses through Node plus two independent Windows PowerShell paths,
   with ipconfig as a final fallback. Get-NetIPAddress is intentionally queried directly because
   Get-NetIPConfiguration can omit an otherwise usable Wi-Fi IPv4 on some classroom Windows setups. */
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import QRCode from 'qrcode';

const execFileAsync=promisify(execFile);
const clean=v=>String(v??'').trim();
const VIRTUAL_HINTS=/(virtual|vmware|vbox|hyper-v|vethernet|docker|wsl|tailscale|zerotier|vpn|loopback|bluetooth|pseudo|tunnel)/i;
const PHYSICAL_HINTS=/(wi-?fi|wireless|wlan|802\.11|ethernet|lan|이더넷|무선)/i;
const WIRED_HINTS=/(ethernet|lan|이더넷)/i;
const WIRELESS_HINTS=/(wi-?fi|wireless|wlan|802\.11|무선)/i;
const IPV4_RE=/\b((?:\d{1,3}\.){3}\d{1,3})\b/;
const isPrivateIpv4=address=>{const parts=String(address||'').split('.').map(Number);if(parts.length!==4||parts.some(n=>!Number.isInteger(n)||n<0||n>255))return false;return parts[0]===10||(parts[0]===172&&parts[1]>=16&&parts[1]<=31)||(parts[0]===192&&parts[1]===168)};
const isLinkLocalIpv4=address=>/^169\.254\./.test(String(address||''));
const isUsableIpv4=address=>{const parts=String(address||'').split('.').map(Number);return parts.length===4&&parts.every(n=>Number.isInteger(n)&&n>=0&&n<=255)&&address!=='0.0.0.0'&&!/^127\./.test(address)};
function adapterText(row){return clean([row?.adapter,row?.description].filter(Boolean).join(' '))}
function connectionKind(value){const name=typeof value==='object'?adapterText(value):clean(value);if(VIRTUAL_HINTS.test(name))return'virtual';if(WIRELESS_HINTS.test(name))return'wireless';if(WIRED_HINTS.test(name))return'wired';return'other'}
function scoreAddress(row){const name=adapterText(row),kind=connectionKind(row);let score=0;if(kind==='wireless')score+=160;else if(kind==='wired')score+=100;else if(PHYSICAL_HINTS.test(name))score+=70;else score+=20;if(isPrivateIpv4(row.address))score+=40;else score-=20;if(VIRTUAL_HINTS.test(name))score-=180;if(isLinkLocalIpv4(row.address))score-=220;if(row.source==='powershell-ipaddress')score+=16;if(row.source==='powershell-ipconfig')score+=12;if(row.source==='ipconfig')score+=2;if(/up|connected|연결됨/i.test(clean(row.status)))score+=10;if(/down|disconnected|연결 끊김/i.test(clean(row.status)))score-=80;return score}
function recommendationFor(row,isRecommended){if(isLinkLocalIpv4(row.address))return'자동 할당 주소(169.254)라 학생 접속용으로 사용하지 않는 것을 권장';if(row.kind==='virtual')return'가상/VPN 어댑터일 수 있어 학생 접속용으로 권장하지 않음';if(isRecommended&&row.kind==='wireless')return'Windows에서 확인된 Wi-Fi 교실망 주소를 우선 추천';if(isRecommended&&row.kind==='wired')return'Windows에서 확인된 유선 교실망 주소를 우선 추천';if(row.kind==='wireless')return'Wi-Fi 대체 접속 주소';if(row.kind==='wired')return'유선 대체 접속 주소';return'Windows에서 확인된 대체 접속 주소'}
function nodeCandidates(){const rows=[];for(const[adapter,entries]of Object.entries(os.networkInterfaces()))for(const n of entries||[]){if(n.family!=='IPv4'||n.internal||!isUsableIpv4(n.address))continue;rows.push({adapter,address:n.address,source:'node',status:'up'})}return rows}
export function parseWindowsPowerShell(text='',source='powershell-ipaddress'){const raw=clean(text);if(!raw)return[];try{const parsed=JSON.parse(raw),items=Array.isArray(parsed)?parsed:[parsed];return items.map(item=>({adapter:clean(item.adapter||item.InterfaceAlias||'Windows 네트워크'),description:clean(item.description||item.InterfaceDescription),address:clean(item.address||item.IPAddress),status:clean(item.status||item.Status),source})).filter(row=>isUsableIpv4(row.address))}catch{return[]}}
export function parseWindowsIpconfig(text=''){const rows=[];let adapter='Windows 네트워크';for(const rawLine of String(text).split(/\r?\n/)){const line=rawLine.trim();if(!line)continue;if(/adapter\s+.+:$/i.test(line)||/어댑터\s+.+:$/.test(line))adapter=line.replace(/:$/,'').replace(/^.*?adapter\s+/i,'').replace(/^.*?어댑터\s+/,'').trim()||adapter;if(!/IPv4/i.test(line))continue;const match=line.match(IPV4_RE);if(!match||!isUsableIpv4(match[1]))continue;rows.push({adapter,address:match[1],source:'ipconfig'})}return rows}
async function runPowerShell(script,source){if(process.platform!=='win32')return[];try{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',`[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;${script}`],{windowsHide:true,encoding:'utf8',timeout:9000,maxBuffer:1024*1024});return parseWindowsPowerShell(stdout,source)}catch{return[]}}
async function windowsPowerShellIpAddressCandidates(){const script="$rows=@();Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | ForEach-Object {$ip=$_;$adapter=Get-NetAdapter -InterfaceIndex $ip.InterfaceIndex -ErrorAction SilentlyContinue | Select-Object -First 1;$rows += [pscustomobject]@{adapter=$ip.InterfaceAlias;description=$adapter.InterfaceDescription;status=$adapter.Status;address=$ip.IPAddress}};$rows | ConvertTo-Json -Compress";return runPowerShell(script,'powershell-ipaddress')}
async function windowsPowerShellIpConfigurationCandidates(){const script="$rows=@();Get-NetIPConfiguration -ErrorAction SilentlyContinue | ForEach-Object {$a=$_.InterfaceAlias;$d=$_.InterfaceDescription;$s=$_.NetAdapter.Status;foreach($ip in @($_.IPv4Address)) {if($ip.IPAddress){$rows += [pscustomobject]@{adapter=$a;description=$d;status=$s;address=$ip.IPAddress}}}};$rows | ConvertTo-Json -Compress";return runPowerShell(script,'powershell-ipconfig')}
async function windowsIpconfigCandidates(){if(process.platform!=='win32')return[];try{const {stdout}=await execFileAsync('ipconfig',['/all'],{windowsHide:true,encoding:'utf8',timeout:5000,maxBuffer:1024*1024});return parseWindowsIpconfig(stdout)}catch{return[]}}
function rankCandidates(candidates,port){const byAddress=new Map();for(const candidate of candidates){if(!isUsableIpv4(candidate.address))continue;const old=byAddress.get(candidate.address);if(!old||scoreAddress(candidate)>scoreAddress(old))byAddress.set(candidate.address,candidate)}const rows=[...byAddress.values()].map(row=>{const kind=connectionKind(row),address=row.address;return{adapter:row.adapter||row.description||'네트워크',description:row.description||'',address,url:`http://${address}:${port}`,kind,source:row.source,private:isPrivateIpv4(address),linkLocal:isLinkLocalIpv4(address),status:row.status||'',score:scoreAddress(row)}});rows.sort((a,b)=>b.score-a.score||a.adapter.localeCompare(b.adapter,'ko')||a.address.localeCompare(b.address));const preferredIndex=rows.findIndex(row=>!row.linkLocal&&row.kind==='wireless'&&row.private&&row.status!=='Down');const physicalPrivateIndex=preferredIndex>=0?preferredIndex:rows.findIndex(row=>!row.linkLocal&&row.kind!=='virtual'&&row.private&&row.status!=='Down');const physicalIndex=physicalPrivateIndex>=0?physicalPrivateIndex:rows.findIndex(row=>!row.linkLocal&&row.kind!=='virtual'&&row.status!=='Down');const recommendedIndex=physicalIndex>=0?physicalIndex:(rows.length?0:-1);return rows.map((row,index)=>({...row,recommended:index===recommendedIndex,recommendation:recommendationFor(row,index===recommendedIndex)}))}
export function classroomNetworkAddresses(port){return rankCandidates(nodeCandidates(),port)}
export async function discoverClassroomNetworkAddresses(port){const [ipAddresses,ipConfigurations]=await Promise.all([windowsPowerShellIpAddressCandidates(),windowsPowerShellIpConfigurationCandidates()]),ipconfig=await windowsIpconfigCandidates();return rankCandidates([...nodeCandidates(),...ipAddresses,...ipConfigurations,...ipconfig],port)}
export function installNetworkAccessRoute(app,{port}){app.get('/api/network',async(_req,res)=>{try{const rows=await discoverClassroomNetworkAddresses(port),urls=[];for(const row of rows)urls.push({...row,qr:await QRCode.toDataURL(row.url,{width:300,margin:1})});const recommended=urls.find(x=>x.recommended)||null,wirelessCount=urls.filter(x=>x.kind==='wireless'&&!x.linkLocal).length,wiredCount=urls.filter(x=>x.kind==='wired'&&!x.linkLocal).length;const baseGuidance='교사 PC가 유선이어도 학생 패드가 Wi-Fi인 것은 정상입니다. 학교 유선망과 Wi-Fi망 사이의 기기 통신이 허용되어 있으면 접속할 수 있습니다. 교사 PC와 학생 패드는 같은 학교 내부망에서 서로 통신할 수 있어야 합니다.';const foundByPowerShell=urls.some(x=>String(x.source).startsWith('powershell-')),foundByIpconfig=urls.some(x=>x.source==='ipconfig');const discoveryNote=foundByPowerShell?' Windows의 IPv4 목록과 네트워크 구성을 각각 직접 검색했습니다.':foundByIpconfig?' Windows의 실제 네트워크 구성(ipconfig)까지 자동 검색했습니다.':' 현재 운영체제가 제공한 네트워크 주소를 사용합니다.';const missingWifi=wirelessCount===0&&wiredCount>0?' 현재 Wi-Fi IPv4 주소는 발견되지 않았습니다. 학생 패드가 Wi-Fi라면 교사 PC의 Wi-Fi가 실제로 연결되어 IPv4를 받은 상태인지 확인한 뒤 이 화면의 새로고침을 누르세요.':'';const classroomNote=recommended?.kind==='wireless'?`${baseGuidance}${discoveryNote} 학생 패드가 Wi-Fi를 사용한다면 추천 주소를 먼저 시험하고, 안 되면 다른 접속 주소를 직접 선택하세요.`:recommended?.kind==='wired'?`${baseGuidance}${discoveryNote}${missingWifi} 현재 유선 교실망 주소를 추천했습니다. Wi-Fi 주소가 표시되면 학생 패드와 같은 망의 Wi-Fi 주소도 반드시 시험하세요.`:`${baseGuidance}${discoveryNote}${missingWifi} 자동 추천이 맞지 않을 수 있으므로 표시된 주소 중 학생 패드에서 열리는 주소를 직접 선택하세요.`;res.json({ok:true,urls,recommendedUrl:recommended?.url||null,classroomNote,wirelessCount,wiredCount,discovery:'node+windows-powershell-ipaddress+ipconfiguration+ipconfig'})}catch(err){res.status(500).json({ok:false,code:'network-address-read-failed',message:String(err?.message||err).slice(0,160)})}})}
