/* StudyVillage ranking v2: read-only live rankings plus durable Mon-Fri hall-of-fame snapshots. */
const KST_OFFSET_MS=9*60*60*1000;
function kstParts(date=new Date()){const shifted=new Date(date.getTime()+KST_OFFSET_MS);return{year:shifted.getUTCFullYear(),month:shifted.getUTCMonth()+1,day:shifted.getUTCDate(),weekday:shifted.getUTCDay()}}
function utcFromKst(year,month,day){return new Date(Date.UTC(year,month-1,day)-KST_OFFSET_MS)}
function weekWindow(date=new Date()){const p=kstParts(date),daysFromMonday=(p.weekday+6)%7,monday=utcFromKst(p.year,p.month,p.day-daysFromMonday),saturday=new Date(monday.getTime()+5*86400000),friday=new Date(monday.getTime()+4*86400000),fp=kstParts(friday),mp=kstParts(monday);return{key:`${mp.year}-${String(mp.month).padStart(2,'0')}-${String(mp.day).padStart(2,'0')}`,start:monday.toISOString(),end:saturday.toISOString(),label:`${fp.month}월 ${Math.ceil(fp.day/7)}주 랭킹`,semester:fp.month>=9&&fp.month<=12}}
function ensureSchema(db){db.exec(`CREATE TABLE IF NOT EXISTS weekly_ranking_snapshots (week_key TEXT PRIMARY KEY,label TEXT NOT NULL,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,rankings_json TEXT NOT NULL,created_at TEXT NOT NULL);`)}
function weeklyScores(db,window){const deltas=new Map(db.prepare(`SELECT player_name AS name,COALESCE(SUM(delta),0) AS score FROM score_ledger WHERE scope='player' AND field='total_score' AND created_at>=? AND created_at<? GROUP BY player_name`).all(window.start,window.end).map(row=>[row.name,Math.max(0,Number(row.score)||0)]));return db.prepare('SELECT name,xp,total_score AS totalScore,stars FROM players').all().map(row=>({...row,weeklyScore:deltas.get(row.name)||0}))}
function ranked(rows,metric){return [...rows].sort((a,b)=>(Number(b[metric])||0)-(Number(a[metric])||0)||(Number(b.xp)||0)-(Number(a.xp)||0)||String(a.name).localeCompare(String(b.name),'ko')).map((row,index)=>({...row,rank:index+1}))}
function completePastWeeks(db,now=new Date()){const current=weekWindow(now),first=db.prepare("SELECT MIN(created_at) AS value FROM score_ledger WHERE scope='player' AND field='total_score'").get()?.value;if(!first)return;let cursor=weekWindow(new Date(first)).start,guard=0;while(cursor<current.start&&guard++<80){const window=weekWindow(new Date(cursor));if(window.semester&&!db.prepare('SELECT 1 FROM weekly_ranking_snapshots WHERE week_key=?').get(window.key)){const rows=ranked(weeklyScores(db,window),'weeklyScore').filter(row=>row.weeklyScore>0).map(({name,weeklyScore,rank})=>({name,weeklyScore,rank}));db.prepare('INSERT INTO weekly_ranking_snapshots(week_key,label,starts_at,ends_at,rankings_json,created_at) VALUES(?,?,?,?,?,?)').run(window.key,window.label,window.start,window.end,JSON.stringify(rows),new Date().toISOString())}cursor=new Date(new Date(window.start).getTime()+7*86400000).toISOString()}}
export function installRankingV2Routes(app,{db,requireSession,playerView}){ensureSchema(db);app.get('/api/ranking/v2',requireSession,(_req,res)=>{try{completePastWeeks(db);const current=weekWindow(),base=db.prepare('SELECT * FROM players').all().map(row=>{const view=playerView(row);return{name:view.name,xp:view.xp,level:view.level,title:view.title,totalScore:view.totalScore,stars:Number(row.stars)||0,baseCharacter:view.baseCharacter,equipment:view.equipment}}),weeklyByName=new Map(weeklyScores(db,current).map(row=>[row.name,row.weeklyScore])),live=base.map(row=>({...row,weeklyScore:weeklyByName.get(row.name)||0})),hall=db.prepare('SELECT week_key AS weekKey,label,starts_at AS startsAt,ends_at AS endsAt,rankings_json AS rankingsJson FROM weekly_ranking_snapshots ORDER BY week_key DESC').all().map(row=>({...row,rankings:JSON.parse(row.rankingsJson||'[]')}));res.json({ok:true,timezone:'Asia/Seoul',week:{key:current.key,label:current.label,startsAt:current.start,endsAt:current.end},rankings:{level:ranked(live,'level'),totalScore:ranked(live,'totalScore'),stars:ranked(live,'stars'),weeklyScore:ranked(live,'weeklyScore')},hallOfFame:hall})}catch(error){res.status(500).json({ok:false,code:'ranking-v2-read-failed',message:String(error?.message||error).slice(0,160)})}})}
export const rankingWeekWindow=weekWindow;
