/* v1.9: existing classroom APIs preserved; question review state is stored in backed-up settings. */
import express from 'express';
import Database from 'better-sqlite3';
import crypto from 'node:crypto';
import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import QRCode from 'qrcode';
import { fileURLToPath } from 'node:url';
import { installActivityStateRoutes } from './activity-state.js';
import { installQuestionReviewRoutes } from './question-review.js';
import { installStarLedgerRoutes } from './star-ledger.js';
import { CURRENT_BACKUP_VERSION } from './backup-migrator.js';

const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),rootDir=path.resolve(__dirname,'..');
const dataDir=process.env.STUDYVILLAGE_DATA_DIR||__dirname;fs.mkdirSync(dataDir,{recursive:true});
const dbPath=path.join(dataDir,'studyvillage.db'),db=new Database(dbPath),app=express(),PORT=Number(process.env.PORT)||3000;
const sessions=new Map(),adminSessions=new Map(),presence=new Map();
const liveEvents=[];let liveEventSeq=0;
const STUDENT_SESSION_TTL_MS=12*60*60*1000,ADMIN_SESSION_TTL_MS=12*60*60*1000,PRESENCE_TTL_MS=5*60*1000;
app.use(express.json({limit:'2mb'}));app.use(express.static(rootDir));db.pragma('journal_mode = WAL');db.pragma('busy_timeout = 5000');
db.exec(`
CREATE TABLE IF NOT EXISTS players (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,total_score INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,best_score INTEGER NOT NULL DEFAULT 0,last_score INTEGER NOT NULL DEFAULT 0,login_count INTEGER NOT NULL DEFAULT 0,last_login_at TEXT,xp INTEGER NOT NULL DEFAULT 0,base_character TEXT NOT NULL DEFAULT 'student-default',equipment_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity_log (id INTEGER PRIMARY KEY AUTOINCREMENT,player_name TEXT NOT NULL,type TEXT NOT NULL,detail TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity_records (id INTEGER PRIMARY KEY AUTOINCREMENT,player_name TEXT NOT NULL,activity_id TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,best_score INTEGER NOT NULL DEFAULT 0,last_score INTEGER NOT NULL DEFAULT 0,total_score INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,UNIQUE(player_name,activity_id));
CREATE TABLE IF NOT EXISTS error_reports (id INTEGER PRIMARY KEY AUTOINCREMENT,player_name TEXT,report_id TEXT NOT NULL UNIQUE,kind TEXT,message TEXT,stack TEXT,page TEXT,version TEXT,user_agent TEXT,online INTEGER,mode TEXT,extra_json TEXT,recent_events_json TEXT,created_at TEXT NOT NULL);
`);
function ensurePlayerColumn(name,definition){const cols=db.prepare('PRAGMA table_info(players)').all().map(r=>r.name);if(!cols.includes(name))db.exec(`ALTER TABLE players ADD COLUMN ${name} ${definition}`)}
ensurePlayerColumn('login_count','INTEGER NOT NULL DEFAULT 0');ensurePlayerColumn('last_login_at','TEXT');ensurePlayerColumn('xp','INTEGER NOT NULL DEFAULT 0');ensurePlayerColumn('base_character',`TEXT NOT NULL DEFAULT 'student-default'`);ensurePlayerColumn('equipment_json',`TEXT NOT NULL DEFAULT '{}'`);
const levelFromXp=xp=>Math.max(1,Math.floor((Number(xp)||0)/200)+1),xpIntoLevel=xp=>(Number(xp)||0)%200;
function rewardsFor(r){const level=levelFromXp(r.xp),badges=[];if((r.attempts||0)>=1)badges.push({id:'first-challenge',icon:'🌱',name:'첫 도전'});if((r.best_score||0)>=1000)badges.push({id:'perfect',icon:'🏆',name:'수수께끼 마스터'});if((r.attempts||0)>=10)badges.push({id:'persistent',icon:'🔥',name:'꾸준한 도전자'});if((r.login_count||0)>=10)badges.push({id:'regular',icon:'📅',name:'마을 단골'});if(level>=3)badges.push({id:'growing',icon:'⭐',name:'성장하는 학습자'});if(level>=5)badges.push({id:'scholar',icon:'🎓',name:'학습 탐험가'});let title='새싹 주민';if(level>=2)title='배움 여행자';if(level>=3)title='성장하는 도전자';if(level>=5)title='학습 탐험가';if((r.best_score||0)>=1000)title='수수께끼 마스터';return{title,badges}}
const BASE_CHARACTERS=[{id:'student-default',icon:'🧑‍🎓',name:'기본 학생'},{id:'student-boy',icon:'👦',name:'소년 탐험가'},{id:'student-girl',icon:'👧',name:'소녀 탐험가'},{id:'student-hero',icon:'🧑‍🚀',name:'우주 탐험가'}];
const BASE_IDS=new Set(BASE_CHARACTERS.map(c=>c.id));
const ITEM_CATALOG=[{id:'cap-blue',slot:'hat',icon:'🧢',name:'파란 모자',unlock:r=>levelFromXp(r.xp)>=2,condition:'Lv.2 달성'},{id:'crown-gold',slot:'hat',icon:'👑',name:'황금 왕관',unlock:r=>(r.best_score||0)>=1000,condition:'퀴즈 만점 달성'},{id:'glasses-round',slot:'glasses',icon:'👓',name:'동그란 안경',unlock:r=>levelFromXp(r.xp)>=3,condition:'Lv.3 달성'},{id:'backpack',slot:'bag',icon:'🎒',name:'모험 가방',unlock:r=>(r.attempts||0)>=5,condition:'도전 5회 완료'},{id:'pet-chick',slot:'pet',icon:'🐣',name:'병아리 친구',unlock:r=>(r.login_count||0)>=10,condition:'로그인 10회'},{id:'pet-cat',slot:'pet',icon:'🐱',name:'고양이 친구',unlock:r=>levelFromXp(r.xp)>=5,condition:'Lv.5 달성'}];
const ITEM_BY_ID=new Map(ITEM_CATALOG.map(item=>[item.id,item]));
function parseEquipment(r){try{const v=JSON.parse(r.equipment_json||'{}'),out={hat:null,glasses:null,bag:null,pet:null};for(const slot of Object.keys(out)){const id=v?.[slot],item=ITEM_BY_ID.get(id);if(item?.slot===slot)out[slot]=id}return out}catch{return{hat:null,glasses:null,bag:null,pet:null}}}
function inventoryFor(r){return ITEM_CATALOG.map(item=>({id:item.id,slot:item.slot,icon:item.icon,name:item.name,condition:item.condition,unlocked:!!item.unlock(r)}))}
function sanitizeEquipment(r,equipment){const inv=inventoryFor(r),allowed=new Map(inv.filter(i=>i.unlocked).map(i=>[i.id,i]));const out={hat:null,glasses:null,bag:null,pet:null};for(const slot of Object.keys(out)){const id=equipment?.[slot];if(id&&allowed.get(id)?.slot===slot)out[slot]=id}return out}
function activityRecordsFor(name){return db.prepare('SELECT activity_id AS activityId,attempts,best_score AS bestScore,last_score AS lastScore,total_score AS totalScore,updated_at AS updatedAt FROM activity_records WHERE player_name=? ORDER BY activity_id').all(name)}
function hashPassword(password,salt){return crypto.scryptSync(password,salt,64).toString('hex')}
function safePlayer(r){const rewards=rewardsFor(r),equipment=parseEquipment(r);return{name:r.name,totalScore:r.total_score,attempts:r.attempts,bestScore:r.best_score,lastScore:r.last_score,loginCount:r.login_count||0,lastLoginAt:r.last_login_at||null,xp:r.xp||0,level:levelFromXp(r.xp),xpIntoLevel:xpIntoLevel(r.xp),xpToNext:200,title:rewards.title,badges:rewards.badges,baseCharacter:BASE_IDS.has(r.base_character)?r.base_character:'student-default',baseCharacters:BASE_CHARACTERS,inventory:inventoryFor(r),equipment,activities:activityRecordsFor(r.name),updatedAt:r.updated_at}}
function logActivity(name,type,detail=''){db.prepare('INSERT INTO activity_log(player_name,type,detail,created_at) VALUES(?,?,?,?)').run(name,type,detail,new Date().toISOString())}
const bearer=req=>{const a=String(req.headers.authorization||'');return a.startsWith('Bearer ')?a.slice(7):''};
function pruneSessions(map,ttl,now=Date.now()){for(const[token,session]of map.entries())if(now-(session?.lastSeenAt||session?.createdAt||0)>ttl)map.delete(token)}
function sessionFrom(map,token,ttl){const s=map.get(token);if(!s)return null;if(Date.now()-s.lastSeenAt>ttl){map.delete(token);return null}s.lastSeenAt=Date.now();return s}
function requireSession(req,res,next){const s=sessionFrom(sessions,bearer(req),STUDENT_SESSION_TTL_MS);if(!s)return res.status(401).json({ok:false,code:'not-authenticated'});req.session=s;next()}
function requireAdmin(req,res,next){if(!sessionFrom(adminSessions,bearer(req),ADMIN_SESSION_TTL_MS))return res.status(401).json({ok:false,code:'admin-not-authenticated'});next()}
const createSession=name=>{const t=crypto.randomBytes(32).toString('hex'),now=Date.now();pruneSessions(sessions,STUDENT_SESSION_TTL_MS,now);sessions.set(t,{name,createdAt:now,lastSeenAt:now});return t},createAdminSession=()=>{const t=crypto.randomBytes(32).toString('hex'),now=Date.now();pruneSessions(adminSessions,ADMIN_SESSION_TTL_MS,now);adminSessions.set(t,{createdAt:now,lastSeenAt:now});return t};
function classroomUrls(){const u=[];for(const[adapter,entries]of Object.entries(os.networkInterfaces()))for(const n of entries||[])if(n.family==='IPv4'&&!n.internal)u.push({adapter,address:n.address,url:`http://${n.address}:${PORT}`});return u}
function prunePresence(now=Date.now()){for(const[name,seen]of presence.entries())if(now-seen>PRESENCE_TTL_MS)presence.delete(name)}
function activePresenceNames(){const now=Date.now();prunePresence(now);return new Set([...presence.entries()].filter(([,seen])=>now-seen<=45000).map(([name])=>name))}
function pruneLiveEvents(){const now=Date.now();while(liveEvents.length&&(liveEvents[0].expiresAt<=now||liveEvents.length>50))liveEvents.shift()}
const getSetting=k=>db.prepare('SELECT value FROM settings WHERE key=?').get(k)?.value||null,setSetting=(k,v)=>db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,v);
function ensureAdminPassword(){if(getSetting('admin_hash')&&getSetting('admin_salt'))return;const initial=process.env.STUDYVILLAGE_ADMIN_PASSWORD||'teacher1234',salt=crypto.randomBytes(16).toString('hex');setSetting('admin_salt',salt);setSetting('admin_hash',hashPassword(initial,salt));console.log('초기 관리자 비밀번호: teacher1234 (첫 로그인 후 변경 권장)')};ensureAdminPassword();
installActivityStateRoutes(app,{getSetting,setSetting,requireAdmin});
installQuestionReviewRoutes(app,{getSetting,setSetting,requireAdmin});
installStarLedgerRoutes(app,{requireSession,requireAdmin});
app.post('/api/login',(req,res)=>{const name=String(req.body?.name||'').trim().replace(/\s+/g,' ').slice(0,12),password=String(req.body?.password||'');if(!name||password.length<4||password.length>72)return res.status(400).json({ok:false,code:'invalid-input'});let row=db.prepare('SELECT * FROM players WHERE name=?').get(name),isNew=false;const now=new Date().toISOString();if(!row){const salt=crypto.randomBytes(16).toString('hex');db.prepare('INSERT INTO players(name,password_hash,password_salt,login_count,last_login_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(name,hashPassword(password,salt),salt,1,now,now,now);isNew=true;logActivity(name,'account-created','첫 계정 생성')}else{const a=Buffer.from(row.password_hash,'hex'),c=Buffer.from(hashPassword(password,row.password_salt),'hex');if(!(a.length===c.length&&crypto.timingSafeEqual(a,c)))return res.status(401).json({ok:false,code:'wrong-password'});db.prepare('UPDATE players SET login_count=login_count+1,last_login_at=?,updated_at=? WHERE name=?').run(now,now,name);logActivity(name,'login','마을 접속')}row=db.prepare('SELECT * FROM players WHERE name=?').get(name);res.json({ok:true,isNew,token:createSession(name),player:safePlayer(row)})});
app.get('/api/player/me',requireSession,(req,res)=>{const r=db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name);if(!r)return res.status(404).json({ok:false});res.json({ok:true,player:safePlayer(r)})});
app.get('/api/player/me/score-ledger',requireSession,(req,res)=>{try{const limit=Math.max(1,Math.min(300,Number(req.query.limit)||100)),entries=db.prepare(`SELECT id,scope,activity_id AS activityId,field,before_value AS beforeValue,after_value AS afterValue,delta,source,created_at AS createdAt FROM score_ledger WHERE player_name=? ORDER BY id DESC LIMIT ?`).all(req.session.name,limit);res.json({ok:true,entries})}catch(err){res.status(500).json({ok:false,code:'score-ledger-read-failed',message:String(err?.message||err).slice(0,160)})}});
app.post('/api/presence/heartbeat',requireSession,(req,res)=>{presence.set(req.session.name,Date.now());res.json({ok:true})});
app.get('/api/admin/presence',requireAdmin,(_req,res)=>{const now=Date.now();prunePresence(now);const players=db.prepare('SELECT name,last_login_at AS lastLoginAt FROM players ORDER BY name').all().map(p=>{const seen=presence.get(p.name)||0,age=seen?now-seen:null;let status='offline';if(age!==null&&age<=45000)status='online';else if(age!==null&&age<=120000)status='recent';return{name:p.name,status,lastSeenAt:seen?new Date(seen).toISOString():null,lastLoginAt:p.lastLoginAt}});res.json({ok:true,heartbeatSeconds:15,onlineWindowSeconds:45,recentWindowSeconds:120,players})});
app.get('/api/live-events',requireSession,(req,res)=>{pruneLiveEvents();const latest=liveEventSeq;if(String(req.query.after||'')==='latest')return res.json({ok:true,cursor:latest,events:[]});const after=Math.max(0,Number(req.query.after)||0),name=req.session.name,events=liveEvents.filter(e=>e.id>after&&e.audience.has(name)).map(e=>({id:e.id,icon:e.icon,message:e.message,type:e.type,createdAt:e.createdAt}));res.json({ok:true,cursor:latest,events})});
app.post('/api/admin/live-events',requireAdmin,(req,res)=>{const message=String(req.body?.message||'').trim().slice(0,160),icon=String(req.body?.icon||'✨').slice(0,8),type=String(req.body?.type||'celebration').slice(0,40);if(!message)return res.status(400).json({ok:false,code:'message-required'});const audience=activePresenceNames(),now=Date.now(),event={id:++liveEventSeq,icon,message,type,audience,createdAt:new Date(now).toISOString(),expiresAt:now+15000};liveEvents.push(event);pruneLiveEvents();res.json({ok:true,eventId:event.id,recipients:audience.size})});
app.post('/api/player/me/record',requireSession,(req,res)=>{const e=db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name);if(!e)return res.status(404).json({ok:false});const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0)),totalScore=clamp(req.body?.totalScore,0,100000000),attempts=clamp(req.body?.attempts,0,1000000),bestScore=clamp(req.body?.bestScore,0,1000),lastScore=clamp(req.body?.lastScore,0,1000),now=new Date().toISOString();let xp=e.xp||0;if(attempts>e.attempts){const gained=20+Math.floor(lastScore/10);xp+=gained;logActivity(req.session.name,'quiz-complete',`${lastScore}점 · +${gained}XP`)}db.prepare('UPDATE players SET total_score=?,attempts=?,best_score=?,last_score=?,xp=?,updated_at=? WHERE name=?').run(totalScore,attempts,bestScore,lastScore,xp,now,req.session.name);res.json({ok:true,player:safePlayer(db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name))})});
app.post('/api/player/me/activity',requireSession,(req,res)=>{const activityId=String(req.body?.activityId||'').trim().slice(0,40),score=Math.max(0,Math.min(1000,Number(req.body?.score)||0));if(!/^[a-z0-9-]+$/.test(activityId))return res.status(400).json({ok:false,code:'invalid-activity'});const player=db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name);if(!player)return res.status(404).json({ok:false});const now=new Date().toISOString(),existing=db.prepare('SELECT * FROM activity_records WHERE player_name=? AND activity_id=?').get(req.session.name,activityId),attempts=(existing?.attempts||0)+1,best=Math.max(existing?.best_score||0,score),total=(existing?.total_score||0)+score,gained=20+Math.floor(score/10);db.prepare(`INSERT INTO activity_records(player_name,activity_id,attempts,best_score,last_score,total_score,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(player_name,activity_id) DO UPDATE SET attempts=excluded.attempts,best_score=excluded.best_score,last_score=excluded.last_score,total_score=excluded.total_score,updated_at=excluded.updated_at`).run(req.session.name,activityId,attempts,best,score,total,now);db.prepare('UPDATE players SET xp=xp+?,updated_at=? WHERE name=?').run(gained,now,req.session.name);logActivity(req.session.name,`activity-${activityId}`,`${score}점 · +${gained}XP`);const updated=db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name);res.json({ok:true,gainedXp:gained,record:{activityId,attempts,bestScore:best,lastScore:score,totalScore:total,updatedAt:now},player:safePlayer(updated)})});
app.post('/api/player/me/equipment',requireSession,(req,res)=>{const r=db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name);if(!r)return res.status(404).json({ok:false});const equipment=sanitizeEquipment(r,req.body?.equipment||{}),baseCharacter=BASE_IDS.has(req.body?.baseCharacter)?req.body.baseCharacter:(BASE_IDS.has(r.base_character)?r.base_character:'student-default'),now=new Date().toISOString();db.prepare('UPDATE players SET base_character=?,equipment_json=?,updated_at=? WHERE name=?').run(baseCharacter,JSON.stringify(equipment),now,req.session.name);logActivity(req.session.name,'equipment-change',`캐릭터/꾸미기 변경 · ${baseCharacter}`);res.json({ok:true,player:safePlayer(db.prepare('SELECT * FROM players WHERE name=?').get(req.session.name))})});
app.post('/api/error-report',requireSession,(req,res)=>{const r=req.body||{},reportId=String(r.id||'').slice(0,100);if(!reportId)return res.status(400).json({ok:false});const safe=(v,n)=>String(v??'').replace(/Bearer\s+[A-Za-z0-9._-]+/gi,'Bearer [REDACTED]').slice(0,n);try{db.prepare('INSERT OR IGNORE INTO error_reports(player_name,report_id,kind,message,stack,page,version,user_agent,online,mode,extra_json,recent_events_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(req.session.name,reportId,safe(r.kind,80),safe(r.message,1800),safe(r.stack,5000),safe(r.page,500),safe(r.version,40),safe(r.userAgent,500),r.online?1:0,safe(r.mode,80),JSON.stringify(r.extra||{}).slice(0,6000),JSON.stringify(Array.isArray(r.recentEvents)?r.recentEvents.slice(-20):[]).slice(0,12000),safe(r.at,60)||new Date().toISOString());res.json({ok:true})}catch{return res.status(500).json({ok:false})}});
app.post('/api/admin/login',(req,res)=>{const p=String(req.body?.password||''),salt=getSetting('admin_salt'),expected=getSetting('admin_hash'),a=Buffer.from(expected,'hex'),c=Buffer.from(hashPassword(p,salt),'hex');if(!(a.length===c.length&&crypto.timingSafeEqual(a,c)))return res.status(401).json({ok:false});res.json({ok:true,token:createAdminSession()})});
app.post('/api/admin/password',requireAdmin,(req,res)=>{const p=String(req.body?.password||'');if(p.length<6||p.length>72)return res.status(400).json({ok:false});const salt=crypto.randomBytes(16).toString('hex'),now=new Date().toISOString();setSetting('admin_salt',salt);setSetting('admin_hash',hashPassword(p,salt));adminSessions.clear();res.json({ok:true,changedAt:now})});
app.get('/api/admin/players',requireAdmin,(_req,res)=>res.json({ok:true,players:db.prepare('SELECT * FROM players ORDER BY xp DESC,best_score DESC,total_score DESC,name ASC').all().map(safePlayer)}));
app.get('/api/admin/activity',requireAdmin,(_req,res)=>res.json({ok:true,activities:db.prepare('SELECT player_name AS playerName,type,detail,created_at AS createdAt FROM activity_log ORDER BY id DESC LIMIT 100').all()}));
app.get('/api/admin/errors',requireAdmin,(_req,res)=>res.json({ok:true,errors:db.prepare('SELECT id,player_name AS playerName,report_id AS reportId,kind,message,stack,page,version,user_agent AS userAgent,online,mode,extra_json AS extraJson,recent_events_json AS recentEventsJson,created_at AS createdAt FROM error_reports ORDER BY id DESC LIMIT 200').all()}));
app.get('/api/admin/errors/export',requireAdmin,(_req,res)=>{const errors=db.prepare('SELECT * FROM error_reports ORDER BY id DESC LIMIT 500').all();const payload={format:'studyvillage-server-error-report',version:'0.9.63',exportedAt:new Date().toISOString(),privacyNotice:'비밀번호와 인증 토큰은 저장하지 않도록 설계됨',errors};res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="Studyvillage-server-errors-${new Date().toISOString().slice(0,10)}.json"`);res.send(JSON.stringify(payload,null,2))});
app.delete('/api/admin/errors',requireAdmin,(_req,res)=>{db.prepare('DELETE FROM error_reports').run();res.json({ok:true})});
function clearStudentSessions(name){for(const[token,session]of sessions.entries())if(session?.name===name)sessions.delete(token);presence.delete(name)}
app.post('/api/admin/player/:name/reset-password',requireAdmin,(req,res)=>{const name=String(req.params.name||'').trim(),password=String(req.body?.password||'');if(password.length<4||password.length>72)return res.status(400).json({ok:false,code:'invalid-password'});if(!db.prepare('SELECT id FROM players WHERE name=?').get(name))return res.status(404).json({ok:false,code:'student-not-found'});const salt=crypto.randomBytes(16).toString('hex'),now=new Date().toISOString();db.prepare('UPDATE players SET password_hash=?,password_salt=?,updated_at=? WHERE name=?').run(hashPassword(password,salt),salt,now,name);clearStudentSessions(name);logActivity(name,'password-reset','교사가 학생 비밀번호 변경');res.json({ok:true})});
const resetStudentRecord=db.transaction(n=>{const now=new Date().toISOString(),changed=db.prepare(`UPDATE players SET total_score=0,attempts=0,best_score=0,last_score=0,xp=0,base_character='student-default',equipment_json='{}',updated_at=? WHERE name=?`).run(now,n);if(!changed.changes)return false;db.prepare('DELETE FROM activity_records WHERE player_name=?').run(n);logActivity(n,'record-reset','교사가 학습 기록/XP/꾸미기 초기화');return true});
app.post('/api/admin/player/:name/reset-record',requireAdmin,(req,res)=>{const name=String(req.params.name||'').trim();if(!resetStudentRecord(name))return res.status(404).json({ok:false});res.json({ok:true})});
app.post('/api/admin/players/:name/reset',requireAdmin,(req,res)=>{const name=String(req.params.name||'').trim();if(!resetStudentRecord(name))return res.status(404).json({ok:false});res.json({ok:true})});
const deleteStudentData=db.transaction(name=>{if(!db.prepare('SELECT id FROM players WHERE name=?').get(name))return false;try{db.prepare('DELETE FROM score_alert_reviews WHERE ledger_id IN (SELECT id FROM score_ledger WHERE player_name=?)').run(name)}catch{}try{db.prepare('DELETE FROM score_corrections WHERE player_name=?').run(name)}catch{}try{db.prepare('DELETE FROM score_ledger WHERE player_name=?').run(name)}catch{}try{db.prepare('DELETE FROM star_ledger WHERE player_name=?').run(name)}catch{}db.prepare('DELETE FROM activity_records WHERE player_name=?').run(name);db.prepare('DELETE FROM activity_log WHERE player_name=?').run(name);db.prepare('DELETE FROM error_reports WHERE player_name=?').run(name);db.prepare('DELETE FROM settings WHERE key=?').run(`compat:stars:${encodeURIComponent(name)}`);db.prepare('DELETE FROM players WHERE name=?').run(name);return true});
app.delete('/api/admin/player/:name',requireAdmin,(req,res)=>{const name=String(req.params.name||'').trim().slice(0,12);if(!name)return res.status(400).json({ok:false,code:'invalid-student'});if(!deleteStudentData(name))return res.status(404).json({ok:false,code:'student-not-found'});clearStudentSessions(name);res.json({ok:true,name})});
app.get('/api/admin/classroom-info',requireAdmin,async(_req,res)=>{const urls=classroomUrls(),preferred=urls[0]?.url||`http://${'localhost'}:${PORT}`,qrDataUrl=await QRCode.toDataURL(preferred,{width:300,margin:1});res.json({ok:true,port:PORT,urls,preferred,qrDataUrl})});
app.get('/api/admin/backup',requireAdmin,(_req,res)=>{const all=t=>{try{return db.prepare(`SELECT * FROM ${t} ORDER BY id`).all()}catch{return[]}},payload={format:'studyvillage-backup',version:CURRENT_BACKUP_VERSION,exportedAt:new Date().toISOString(),players:all('players'),settings:db.prepare('SELECT * FROM settings ORDER BY key').all(),activities:all('activity_log'),activityRecords:all('activity_records'),errorReports:all('error_reports'),scoreLedger:all('score_ledger'),scoreAlertReviews:db.prepare('SELECT * FROM score_alert_reviews ORDER BY ledger_id').all(),scoreCorrections:all('score_corrections')};res.setHeader('Content-Type','application/json; charset=utf-8');res.send(JSON.stringify(payload,null,2))});
app.post('/api/admin/restore',requireAdmin,(req,res)=>{const b=req.body;if(b?.format!=='studyvillage-backup')return res.status(400).json({ok:false});const restore=db.transaction(()=>{for(const t of ['score_corrections','score_alert_reviews','score_ledger','star_ledger','activity_records','activity_log','error_reports','players','settings']){try{db.prepare(`DELETE FROM ${t}`).run()}catch{}};const insert=(sql,rows)=>{const s=db.prepare(sql);for(const r of rows||[])s.run(r)};insert('INSERT INTO players(id,name,password_hash,password_salt,total_score,attempts,best_score,last_score,login_count,last_login_at,xp,base_character,equipment_json,owned_items_json,created_at,updated_at) VALUES(@id,@name,@password_hash,@password_salt,@total_score,@attempts,@best_score,@last_score,@login_count,@last_login_at,@xp,@base_character,@equipment_json,@owned_items_json,@created_at,@updated_at)',b.players);insert('INSERT INTO settings(key,value) VALUES(@key,@value)',b.settings);insert('INSERT INTO activity_log(id,player_name,type,detail,created_at) VALUES(@id,@player_name,@type,@detail,@created_at)',b.activities);insert('INSERT INTO activity_records(id,player_name,activity_id,attempts,best_score,last_score,total_score,updated_at) VALUES(@id,@player_name,@activity_id,@attempts,@best_score,@last_score,@total_score,@updated_at)',b.activityRecords);insert('INSERT INTO error_reports(id,player_name,report_id,kind,message,stack,page,version,user_agent,online,mode,extra_json,recent_events_json,created_at) VALUES(@id,@player_name,@report_id,@kind,@message,@stack,@page,@version,@user_agent,@online,@mode,@extra_json,@recent_events_json,@created_at)',b.errorReports);insert('INSERT INTO score_ledger(id,player_name,scope,activity_id,field,before_value,after_value,delta,source,created_at) VALUES(@id,@player_name,@scope,@activity_id,@field,@before_value,@after_value,@delta,@source,@created_at)',b.scoreLedger);insert('INSERT INTO score_alert_reviews(ledger_id,status,note,reviewed_at) VALUES(@ledger_id,@status,@note,@reviewed_at)',b.scoreAlertReviews);insert('INSERT INTO score_corrections(id,ledger_id,correction_ledger_id,player_name,scope,activity_id,field,before_value,after_value,reason,corrected_at,undone_at,undo_ledger_id) VALUES(@id,@ledger_id,@correction_ledger_id,@player_name,@scope,@activity_id,@field,@before_value,@after_value,@reason,@corrected_at,@undone_at,@undo_ledger_id)',b.scoreCorrections)});restore();ensureAdminPassword();adminSessions.clear();sessions.clear();presence.clear();liveEvents.length=0;liveEventSeq=0;res.json({ok:true,players:b.players?.length||0,auditEntries:b.scoreLedger?.length||0})});
app.get('/api/health',(_req,res)=>res.json({ok:true,server:'Studyvillage classroom server',dataPath:dbPath}));
export function startClassroomServer(){return app.listen(PORT,'0.0.0.0',()=>console.log(`\
Studyvillage classroom server: http://localhost:${PORT}\
학생 접속 주소:`),...classroomUrls().map(x=>console.log(` - ${x.url}`)))}
if(process.env.STUDYVILLAGE_EMBEDDED!=='1')startClassroomServer();